### ISSUE TITLE
Bug in GeoIP module on Windows servers

### ISSUE THREAD

**Issue by fearworksmedia** [padams/Open-Web-Analytics#1]
There seems to be an issue with the GeoIP module when OWA is running on a Windows server.

In the file:

modules/maxmind_geoip/classes/maxmind.php

there is a colon (:) hard-coded as a separator in the two lines containing: set_include_path

This might work in Linux, but on Windows servers the separator needs to be a semi-colon (;). I was getting a blank screen when trying to get to the module admin page.

The solution for compatability with both Linux and Windows is to replace the hard-coded colon (:) with the PATH_SEPARATOR predefined constant (see http://php.net/manual/en/dir.constants.php for more info), so that those sections of code look like this:

if (!class_exists('PEAR_Exception')) {
	set_include_path(get_include_path(). PATH_SEPARATOR .OWA_MODULES_DIR.'maxmind_geoip/includes/PEAR-1.9.1/');
}

and

set_include_path(
	get_include_path(). PATH_SEPARATOR .
	OWA_MODULES_DIR.'maxmind_geoip/includes/Net_GeoIP-1.0.0/'
);

Thanks,

Keith

**Comment by padams** [comment]
This is fixed in master but requires the use of the new MaxMind cityLite2 DB format.
