### ISSUE TITLE
Not loading blank.php via HTTPS

### ISSUE THREAD

**Issue by erickarbe** [padams/Open-Web-Analytics#101]
I am using the OWA WordPress plugin and my site is secured with an SSL. My 'OWA_PUBLIC_URL' is set to 'https' - however I am still getting a console error because the plugin is trying to load 'plugins/owa/blank.php' via http. Any suggestions on where I can change this?

**Comment by pratham2003** [comment]
I'm facing the same problem

**Comment by robocoder** [comment]
There are a couple of possibilities that I can think of here.

1) in owa_lib.php's get_current_url() , change this:
```
                if( isset( $_SERVER['HTTPS'] ) && strtolower( $_SERVER['HTTPS'] ) == 'on') {
```
to:
```
                if( isset( $_SERVER['HTTPS'] ) && ($_SERVER['HTTPS'] === true || strtolower( $_SERVER['HTTPS'] ) == 'on')) {
```

2. Alternately, drop the protocol/scheme entirely, and use a protocol-relative (network path reference) URL by changing these lines:
```
                $url = 'http';

                // check for https
                if( isset( $_SERVER['HTTPS'] ) && strtolower( $_SERVER['HTTPS'] ) == 'on') {
                        $url.= 's';
                } elseif ( isset( $_SERVER['SERVER_PORT'] ) && $_SERVER['SERVER_PORT'] == 443 ) {
                        $url.= 's';
                }

                if ( isset( $_SERVER['HTTP_HOST'] ) ) {
                        // contains port number
                        $domain = $_SERVER['HTTP_HOST'];
                } else {
                        // does not contain port number.
                        $domain = $_SERVER['SERVER_NAME'];
                        if( $_SERVER['SERVER_PORT'] != 80 ) {
                                $domain .= ':' . $_SERVER['SERVER_PORT'];
                        }
                }

                $url .= '://'.$domain;
```
to simply:
```
                $url = '//'.$domain;
```

**Comment by thob** [comment]
doesn't work for me. Chrome still has an issue with 
`requested an insecure form action 'http://owa/blank.php'`

**Comment by cFire** [comment]
I'm having the same issue using the regular javascript tracking code. It seems to be going wrong when the postFromIframe() function is used.

**Comment by cFire** [comment]
Delving into this further, it appears this happens because $_SERVER['HTTPS'] does not get set. This happens for https connections to the OWA server when they are loadbalanced/proxied by something that does not initiate https connections to the backend OWA server, but accepts https on the public side for the OWA domain.

My suggestion would be to look at $_SERVER['HTTP_REFERER'] or $_SERVER['HTTP_ORIGIN'] in this case, as both of these variables retain the protocol string. (https://domain.etc.etc)

**Comment by padams** [comment]
fix in master.
