### ISSUE TITLE
Open web analyitcs foot prints

### ISSUE THREAD

**Issue by cyberking1** [padams/Open-Web-Analytics#103]
Does "open web analytics" leave foot prints for google to find, if so what is the best way around that?.

**Comment by padams** [comment]
I'm not sure what that means. Please clarify.

**Comment by cyberking1** [comment]
If I'M tracking hundreds of websites on the same server, can i use OWA to track each of the websites without Google finding them through OWA?.

**Comment by padams** [comment]
I don’t see how Google would find them via OWA. The only identifier you place in the OWA tracking ta is a site ID (not domain).
