### ISSUE TITLE
Filter Referral Spam

### ISSUE THREAD

**Issue by pixeltopf** [padams/Open-Web-Analytics#105]
Hi everybody,

is there a possibility to filter specific referral page URLs in OWA?
For example: Disable the referral URL http://success-seo.com/... to filter out spam in the view?

Regards!

**Comment by padams** [comment]
Yes you can write a filter function for nearly every tracking param.

**Comment by pixeltopf** [comment]
Thank you very much for your quick reply padams. 
Can you point me into the right direction to find a tutorial on this matter?

**Comment by pixeltopf** [comment]
again: is there an option in open web analytics to filter out specific URLs that i'm missing?
