### ISSUE TITLE
Hide URL 

### ISSUE THREAD

**Issue by JosephBloggs** [padams/Open-Web-Analytics#106]
Could someone please advise if it is possible to track a website in OWA without revealing the OWA server URL?

This can be avoided in Piwik, https://github.com/piwik/piwik/tree/master/misc/proxy-hide-piwik-url#piwik-proxy-hide-url

Confirmation either way would help.

Thank you.

**Comment by padams** [comment]
There is no feature like that.

**Comment by axelsnoski** [comment]
I am looking for the same thing, I might look at adding something I like the look and feel of OWA Better than piwik, Currently have piwik installed and not sure I like it...
