### ISSUE TITLE
OWA GUI -> Top Pages Issue: Not showing more than 30 entries

### ISSUE THREAD

**Issue by TomBrady** [padams/Open-Web-Analytics#107]
Hey All,

Our OWA 1.5.4 is not showing more than 30 entries under the Top Pages "Secondary Dimension" GUI page. There is a Page Scroll option, but it is holding at 30 pages no matter how many times the site gets hit.

Has anyone seen this before?

Thanks in advance.
Tom

**Comment by padams** [comment]
Not seeing this. re-open if you are still having issues with the latest code in master. Be sure to always post debugs info from the HTTP request that the API is making.
