### ISSUE TITLE
Data is not getting track 

### ISSUE THREAD

**Issue by Yogeshschaudhari** [padams/Open-Web-Analytics#108]
Hi All,
I have host OWA application in IIS of windows 2008 R2 server,by installing below required software .
1. MySQL 4.1 or later version.
2. PHP 5.5.11
3. PHP 5.2.x or later version
It is showing OWA application is getting installed, i have copied java-script tracker code on all the aspx pages of application.
Data is not getting track and stored in database. I cant see any analytic report on OWA aaplication
Can anyone help me to solve this?
Thanks,
Yogesh Chaudhari

**Comment by master-opr** [comment]
I have installed wordpress, and then owa in a separate folder (owa). when i added the tracing code (PHP code) in to index.php i got this error on bottom of my site : 

Warning: Cannot modify header information - headers already sent by (output started at . . . . .  .l\wwwroot\wp-includes\theme.php:1139) in .
.\wwwroot\owa\owa_coreAPI.php on line 1079

the owa admin dashboard works well but still there is not any report for showing.
php 5.3
my sql 5.1

**Comment by padams** [comment]
The OWA WordPress plugin will add the tracking tag for you. Use the latest code in master and follow install instructions for WordPress on the wiki.
