### ISSUE TITLE
OWA 1.5.4 is receiving URL Request with correct params, but not storing them???

### ISSUE THREAD

**Issue by TomBrady** [padams/Open-Web-Analytics#112]
Hey All,

OWA 1.5.4 is receiving URL Request with correct params, but not storing them. The cache (which is on) is saying the request is COLD, but not showing up in storage.

I'm also not seeing any insert or update statements in logs (with DEBUG on) and previously I was, but no changes have been made.

It is showing the correct value received as one of the ARRAY params so everything is good up until storage.

Any thoughts on where to look would be greatly appreciated?

We are running on Windows and IIS.

Thanks,
Tom

**Comment by padams** [comment]
Clear the cache dir using the CLI.
