### ISSUE TITLE
PHP files building up in owa-data/caches directories

### ISSUE THREAD

**Issue by desertlavender** [padams/Open-Web-Analytics#113]
I have noticed a large number of php files -- hundreds of files since installing OWA a few days ago -- building up online in the owa-data/caches/owa_ua and owa-data/caches/owa_visitor directories.  Does anybody know what these files are, and why user data is being logged here and not just in the MySQL database?  And do I need to purge these files on some sort of schedule?

**Comment by padams** [comment]
It's the object cache. You can disable it in The config file or there is a CLI command you can cron to flush the cache periodically.

There is also a memcache version of the object cache.
