### ISSUE TITLE
php.ini and smart quotes

### ISSUE THREAD

**Issue by desertlavender** [padams/Open-Web-Analytics#114]
I have shared hosting on lunarpages so I don't have access to the system php.ini file, but I was able to install and run owa after creating a substitute php.ini file in my website root directory that turned off smart quotes.  However, other php programs began to malfunction, since the substitute ini file did not contain all required settings.  I removed the subsititute php.ini file, which restored the functionality of the other programs.  In OWA admin, my site disappeared, but then reappeared with all the data after I "added" the site.  So, I'm wondering if removing the smart quotes override was only necessary during installation, or is it critical to the program in some other way.  Thank you for your help! I'm thrilled with OWA.  It's much easier to use than Google Analytics and provides immediate access to my most important data.

**Comment by padams** [comment]
Historically it has been required but mileage may vary by host and PHP version.
