### ISSUE TITLE
OWA 1.5.7 with MySQL - Errors being displayed on page?

### ISSUE THREAD

**Issue by TomBrady** [padams/Open-Web-Analytics#115]
Hello All,

I have the latest OWA 1.5.7 running locally with Apache 2.4. Everything seems ok, but the deprecation warnings are being displayed on the user's page - even with this setting : define('OWA_ERROR_HANDLER', 'production')  Thoughts?

Thanks,
Tom

**Comment by padams** [comment]
What version of PHP are you running?
Your PHP may be configured to display errors. Check your ini file.

**Comment by TomBrady** [comment]
Thanks so much…

PHP 5.6.9

The INI is the development version so this may be the culprit.

Appreciate the quick response...

**Comment by padams** [comment]
Yes that would do it.
