### ISSUE TITLE
Undefined variable: page_title

### ISSUE THREAD

**Issue by Globalit** [padams/Open-Web-Analytics#116]
In a clean install on a Mac OS-X with MySql DB as the back end, I have completed the installations scripts and it has issued me a user name and password. 

When ever I attempt to use this Username and password, I get the login screen back. If I enter an incorrect password it tells me I have the credential set wrong, so I know it is passing the authentication step. 

In the Error Logs I am getting these messages. 

[Wed Sep 09 16:41:00.246420 2015] [:error] [pid 35523] [client 10.0.0.10:54052] PHP Notice:  Undefined variable: page_title in /Library/Server/Web/Data/Sites/Default/OWA/modules/base/templates/wrapper_public.tpl on line 6, referer: http://10.0.0.2/OWA/index.php?owa_do=base.loginForm&owa_go=http%3A%2F%2F10.0.0.2%2FOWA%2F&

**Comment by padams** [comment]
Can you try the code in master to see if this is still happening and reopen if it is?
