### ISSUE TITLE
OWA Not Sending Any Forms of Emails and Visitor Is Not Set

### ISSUE THREAD

**Issue by adriantan08** [padams/Open-Web-Analytics#117]
Hi!

We are hosting OWA locally with our own SMTP host. I am wondering if this is the reason why we are not receiving any email notifications of any form from OWA (from password resets to new visitor email).

Looking forward for your help on how and where to change it. 

Also, I got this another problem with Visitor not being set. I am using the Javascript tracker codes. I am getting the hits properly but all Visitors are NOT SET when viewing the report. I tried adding:

owa_cmds.push(['setUserName', 'myuser']);

but it's still reporting to the site as NOT SET. 

Thanks in advanced.

**Comment by fnizam82** [comment]
Have the same problem, have you found any solution for the 'setUserName' issue ?

**Comment by padams** [comment]
These are fixed in master.
