### ISSUE TITLE
Remove login page

### ISSUE THREAD

**Issue by TomoZG** [padams/Open-Web-Analytics#118]
Hi,

is there a way to automatically log in to owa web interface so the user does not have to enter any login credentials?
I've tried to hardcode login info to login form and automatically submit form via javascript but that did not allow to be logged in from multiple places (eg. desktop and smartphone).
Also, I've tried to mess up with login.php and some other files, but with no success.

I'm trying to integrate owa in my own cms.
Ideal solution would be to pick up session information from my site and than allow user to see owa GUI if session is active.

Thanks in advance,
Tomislav

**Comment by padams** [comment]
You can set the auth status of the current user from PHP. 

Look at how the WordPress plugin does it in wp_plugin.php. Basically you filter the auth_status using:

$dispatch->attachFilter('auth_status', ‘yourfunction',0);
