### ISSUE TITLE
Setting time period for statistics

### ISSUE THREAD

**Issue by dachande** [padams/Open-Web-Analytics#119]
This is clone of Issue #45 because that issue has already been closed but it still can be experienced with the latest OWA version which is 1.5.7.

The Time Period Control works perfect on Chrome (45.0.2454.101) and Internet Explorer (IE11) but it doesn't work on Firefox. This has been testet on Linux (Firefox 41.0) and Windows (Firefox 40.0.3).

Looking at the Debug Toolbar I get a ```not wellformed``` error in ```modules/base/templates/filter_period.tpl```

```
<div class="timePeriodControlContainer">

	<table id="owa_reportPeriodLabelContainer" cellpadding="0" cellspacing="0">
		<TR>
			<TD class="owa_reportPeriodLabelText">
			
				<span>
					<*=this.datelabel *>
				</span>						
			</TD>
			
			<TD class="owa_reportRevealControl"></TD>	
		</TR>
	</table>
[...]
</div>
```
With ```<*=this.datelabel *>``` being highlighted.

There is also the following error in the file ```modules/base/js/owa.reporting-combined.min.js```:
```
TypeError: h is undefined
```

I hope this helps identifying, debugging and fixing the problem.

**Comment by padams** [comment]
I can't reproduce this on Firefox 44.0.2 running on OS X. If anyone else can please re-open.
