### ISSUE TITLE
Prior and next pages views is not shown

### ISSUE THREAD

**Issue by dachande** [padams/Open-Web-Analytics#120]
I have a problem with OWA not showing any prior and next pages viewed when showing detail statistics of a page. I have attached some screenhots for a page I used as an example. This page is only viewable by the user after the user has logged in and used the navigation to browse that page hence at least the prior pages views should show something.

I am currently using OWA 1.5.7

![owa_prior_pages_error_01](https://cloud.githubusercontent.com/assets/2108865/10278905/5c1d8a16-6b61-11e5-933d-092de2ad29e9.png)
![owa_prior_pages_error_02](https://cloud.githubusercontent.com/assets/2108865/10278907/606af810-6b61-11e5-950d-038c31cf390c.png)

**Comment by jorgeesparteiro** [comment]
I have the same problem. I cannot see this data in the Page Detail report

**Comment by padams** [comment]
Not a generalized issue. Reopen if you have any specific errors or debug info.
