### ISSUE TITLE
foreach() error

### ISSUE THREAD

**Issue by ChrisAtTheMuseum** [padams/Open-Web-Analytics#121]
I was checking out the demo and found this

Warning: Invalid argument supplied for foreach() in /home/padams/demo.openwebanalytics.com/owa/modules/base/templates/report_dimensionalTrend.php on line 7

 http://demo.openwebanalytics.com/owa/index.php?owa_period=today&owa_do=base.reportReferringSites

**Comment by lizzyfin** [comment]
Hey, I was trying the demo and a couple of warnings popped up so I'm here to report a bug. 

Here's a little more info about that error that @ChrisAtTheMuseum reported.

On this page:

http://demo.openwebanalytics.com/owa/index.php?owa_siteId=c9b7d12e322c7c360fb8f7c72ffe4c41&owa_period=last_seven_days&owa_do=base.reportContent

2 warnings produced.

Clicking on 'Entry & Exits' link gave this warning:

Warning: Invalid argument supplied for foreach() in /home/padams/demo.openwebanalytics.com/owa/modules/base/templates/report_dimensionalTrend.php on line 7

The webaddress was changed to:
http://demo.openwebanalytics.com/owa/index.php?owa_do=base.reportReferringSites

Clicking on "Feeds' link gave the same warning but the address was changed to:
http://demo.openwebanalytics.com/owa/index.php?owa_do=base.reportAnchortext

HTH!

**Comment by padams** [comment]
This is now fixed in master. 6a9e52b
