### ISSUE TITLE
Is it possible for OWA to capture the Search Terms in an HTTP Post (search task)?

### ISSUE THREAD

**Issue by TomBrady** [padams/Open-Web-Analytics#122]
Can anyone recommend a way for OWA to capture the Search Terms in an HTTP Post (search task)? Any examples? Thanks in advance. Tom

**Comment by orangelmx** [comment]
http://stackoverflow.com/questions/15781034/how-to-get-original-referrer-url-from-google-search-with-php
https://googleblog.blogspot.com.es/2011/10/making-search-more-secure.html

**Comment by padams** [comment]
a POST from where? Google? Your web app/page would have ot capture that and then set it as a variable on the OWA tracker.
