### ISSUE TITLE
Documentation?!?

### ISSUE THREAD

**Issue by cmcintosh** [padams/Open-Web-Analytics#123]
The wiki for OWA points to the repo, the repo points back to the Wiki.

**Comment by padams** [comment]
Click the wiki link here on github.

**Comment by cmcintosh** [comment]
Right the link on Github takes you to the project site, which then takes you to the wiki site: http://wiki.openwebanalytics.com/index.php?title=Main_Page which then directs you to the github repo (HERE).

See the problem, its a bit of a infinite loop.  Unless I missed something.

**Comment by padams** [comment]
there is a wiki link on the repo page of Github that will take you to the Github hosted wiki for the project.
