### ISSUE TITLE
Campaign Tracking Not Working

### ISSUE THREAD

**Issue by jwhisenhunt** [padams/Open-Web-Analytics#124]
I set my link up like this https://www.mydomain.net/index.php?owa_medium=email&owa_source=email+blast&owa_campaign=oct+20&owa_ad=25+percent+off&owa_ad_type=emailblast is this right? It won't track my campaigns.

**Comment by padams** [comment]
That looks right. Are they making it into the tracking request? did you turn on debug mode to see if that are getting processed?

**Comment by padams** [comment]
Closing as this is not a generalized issue. re-open if there are specific errors or debug from https requests and OWA's error log files.
