### ISSUE TITLE
 OWA 1.5.7 with Wordpress - 404 Not found and can not see any dashboard

### ISSUE THREAD

**Issue by genggjh** [padams/Open-Web-Analytics#126]
Hi all,
I am trying to integrate the OWA into my wordpress website.

I hit the '404 Not found' error when try to see the websit dashboard in my wordpress admin console.

Request URL:
https://XXXXXXXX/test/index.php?owa_apiAction&owa_siteId=13a24cfb9a3e670cb82c8dc00dcbc30a&owa_period=last_seven_days&owa_startDate=20151028&owa_endDate=20151104&owa_do=getResultSet&owa_metrics=visits,uniqueVisitors,pageViews,bounceRate,pagesPerVisit,visitDuration&owa_dimensions=date&owa_sort=date&owa_format=json

Respone:
404 Not Found

Does anyone know what's wrong with this?

The wordpress version is: 4.3.1
PHP version is: 5.5.9
Nginx is 1.4.6

**Comment by genggjh** [comment]
I am not sure if there are something wrong in my nginx conf file. Anyway I provide the snippet of my nginx.conf fyi.

# Add trailing slash to */wp-admin requests.
rewrite /wp-admin$ $scheme://$host$uri/ permanent;

# Directives to send expires headers and turn off 404 error logging.
location ~* ^.+\.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
       access_log off; log_not_found off; expires max;
}

# Uncomment one of the lines below for the appropriate caching plugin (if used).
#include global/wordpress-wp-super-cache.conf;
#include global/wordpress-w3-total-cache.conf;

# Pass all .php files onto a php-fpm/php-fcgi server.
location ~ [^/]\.php(/|$) {
	fastcgi_split_path_info ^(.+?\.php)(/.*)$;
	if (!-f $document_root$fastcgi_script_name) {
		return 404;
	}
	# This is a robust solution for path info security issue and works with "cgi.fix_pathinfo = 1" in /etc/php.ini (default)

        include fastcgi_params;
	fastcgi_index index.php;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#	fastcgi_intercept_errors on;
	fastcgi_pass php;

}

**Comment by padams** [comment]
One thing to check is that OWA must run under a fully qualified domain name.
Also, are you using the WordPress plugin that comes with the OWA distro? See the WordPress install instructions on the wiki.

**Comment by genggjh** [comment]
@padams, thanks for your quick response.
Yes, I run the WP on a FQDN host, and I download the OWA plugin from https://codeload.github.com/padams/Open-Web-Analytics/tar.gz/1.5.7

And I can update the OWA Settings via 'Edit Profile' but to see any reports.

**Comment by padams** [comment]
Try the latest code in master. there were a lot of WordPress fixes recently.
