### ISSUE TITLE
MediaWiki 1.25.1 intégration 

### ISSUE THREAD

**Issue by FxNion** [padams/Open-Web-Analytics#129]
Hi,

I got an error while trying to use mediawiki integration. 
For the installation, I copied the whole owa directory under the 
extension folder, and activated the _mw_plugin.php_ in my _LocalSettings.php_

Line 503 : A Strict standard message, il rewrote   it in:

``` php
function execute($subPage) { 
```

instead of

``` php
function execute() { 
```

But later, in line 578 the following statement failed:

``` php
$wgMessageCache->addMessages( $langMessages, $lang );
```

it seems that the global $wgMessageCache is no longer used since MW 1.18
And here, this is a Fatal error :(

There is also some deprecated warnings concerning class.inputfilter.php on line 262 and 264 
because of the /e modifier used instead of preg_replace_callback in the preg_replace call.

_Mediawiki_ : 1.25.1
_Php_          : 5.5.12

Did you plan any fix concerning the mediawiki domain ?

Thx for your awesome job.

Fx

**Comment by padams** [comment]
Feel free to submit a patch.

**Comment by FxNion** [comment]
@padams : sorry, i do not have time to patch the whole MW plugin, but i made a very simplistic extension https://github.com/FxNion/OpenWebAnalyticsTracker to adress my needs.

Its goal isn't to do the same as your, but is just to insert the OWA javascript tracker.

Feel free to use it in your own MW extension the day you will time to update it.

**Comment by padams** [comment]
adding reference to #460
