### ISSUE TITLE
Cannot log-in

### ISSUE THREAD

**Issue by innovafire** [padams/Open-Web-Analytics#13]
I have OWA set up at getpanthon.com hosting.  We have it in a /owa subdir and we have added the DB tables to the same DB as our drupal installation.

So far only trying this on our dev environment.  But when I go to the login screen and put in user and pass, it simply refreshes the page.  No error or anything.

OWA IS tracking the site, though.  I can see that in the DB.  But I cannot log-in.

Any ideas?

**Comment by padams** [comment]
OWA needs to run under a fully qualified domain name. IP address is not going to work.
