### ISSUE TITLE
Expanded Documentation on Setting Custom Variables in PHP

### ISSUE THREAD

**Issue by anEffingChamp** [padams/Open-Web-Analytics#130]
I just searched around a bit, and found no documentation about setting custom variables in PHP. The section [here](http://wiki.openwebanalytics.com/index.php?title=Custom_Variables#Setting_Custom_Variables_via_PHP) is blank, and there is no mention in the [PHP invocation](https://github.com/padams/Open-Web-Analytics/wiki/PHP-Invoction) so I hoped for some guidance on this.

**Comment by padams** [comment]
See https://github.com/padams/Open-Web-Analytics/wiki/Tracker#custom-variables

Pretty sure the PHP function signature is the same.
