### ISSUE TITLE
Can't see all of reports due to screen size, no workaround

### ISSUE THREAD

**Issue by TheZenKitteh** [padams/Open-Web-Analytics#132]
I have a fairly small screen (1024x768 resolution) and when trying to view the reports, they are cut off on the right side of the screen. There is no scroll bar and no apparent way to view the report without the Wordpress side bar on the left. Even with the menu collapsed, some of the reports page is cut off. I tried manually finding the location of the reports page and was greeted with a login but my Wordpress credentials don't let me log into it. Is there a workaround to this so I can see all of the reports page? I can't increase my resolution any higher without getting a new monitor which isn't possible right now.

**Comment by padams** [comment]
Run OWA in standalone mode. The UI is more forgiving when not wrapped in WordPRess admin.
