### ISSUE TITLE
Duplicate Visits, Visitors, and Sessions

### ISSUE THREAD

**Issue by mkrawitz** [padams/Open-Web-Analytics#135]
After adding the javascript, I am able to get Open Web Analytics to count views, however each view is being associated with an entirely separate session/visitor.  I.E. if I even just refresh the page, that is counted as a new visit.  What might I be doing wrong? 

I am using Open Web Analytics 1.5.7 with IIS 7.5.7600 on Microsoft Windows Server 2008 R2 ( version 6.1.7601 ).  I am using PHP 5.6.0.  My browser is the latest version of Chrome and I confirmed that cookies and javascript are allowed.

Thanks and let me know if any other information would be helpful.

Marc Krawitz

**Comment by mkrawitz** [comment]
Sorry, what I meant to say is: "After adding the javascript tracker, ..."

**Comment by padams** [comment]
Windows is not officially supported. Not sure that's your issue but it could be. Turn on debug mode and watch the log file to see why it might be creating a new session within the default 30 min period.

Also the last_req timestamp value is used by OWA to determine if the last_req was more than 30 min ago. If your server's time is fubar then that might be an issue as well.

**Comment by arnisjuraga** [comment]
Double check, that everything is OK with PHP sessions.
I had a similar issue, where was "Headers already sent" *before* owa PHP script snippet. 

In this case, owa could not create Cookie and was starting a new session on every request. 

This should be documented and fixed somehow, otherwise there is huge amount of data generated on misconfiguration.

**Comment by padams** [comment]
What exactly was the misconfiguration involving PHP Sessions?

**Comment by arnisjuraga** [comment]
Simply, if I have "any" output _before_ PHP tracker. Something like this:

```php
<html>
<head>
<title>Document</title>
</head>
<body>
 <?php
        require_once('owa_env.php');
        require_once(OWA_DIR.'owa_php.php');
        $owa = new owa_php();
        $owa->setSiteId('your_site_id');
        $owa->setPageTitle('My Web Page Title');
        $owa->setPageType('article');
        $owa->trackPageView(); ?>

Hello, world!
</body>
</html>
```

**Comment by padams** [comment]
Ah. yes that is true but only if you are using the php tracker.
