### ISSUE TITLE
OWA standalone - no traffic from https

### ISSUE THREAD

**Issue by Dranick** [padams/Open-Web-Analytics#136]
Hello,

I am using OWA as a standalone installation. It works fine when tracking http links however I get no traffic from a HTTPS web site even though the JS code is correctly inserted in pages.

Please help.

Thank you.

**Comment by padams** [comment]
Try the latest code in master. Also to help troubleshoot something like this you need ot post the tracker code and any javascript errors the the browser is throwing.
