### ISSUE TITLE
Can't Get Past Login After Install

### ISSUE THREAD

**Issue by alexflanagan** [padams/Open-Web-Analytics#137]
Not running on a bare IP, running on an A record. If my main site is example.com I have a separate box for this A-named to analytics.example.com.

Installed 1.5.7, did installer (to test, configured to track analytics.example.com), loops on Login screen. Tried under Chrome, Safari, Fox.

I have WordPress running on the same machine in a different DB, different directory. Attempting to run standalone, not as a plugin. Top-level rewrite rules currently disabled. Also tried the password reset and "Could not instantiate mail function."

Let me know what other information I can provide.

**Comment by alexflanagan** [comment]
Host is Rackspace.

**Comment by alexflanagan** [comment]
owner:group is the web server user, permissions are 777 for troubleshooting.

**Comment by padams** [comment]
What version of PHP?

Look at the POST requests and see if the password is making it to the server. Then turn on OWA's debug mode and watch the log file to see if the user name and password show up correctly as well as where OWA might be getting stuck.

**Comment by padams** [comment]
Closing. re-open if the current code in master isn't working for you.
