### ISSUE TITLE
Feed Tracking - curious

### ISSUE THREAD

**Issue by diondkb** [padams/Open-Web-Analytics#14]
Hi,

The doc states: RSS/ATOM subscription tracking - track unique feed readers, reader types, and feed requests - how does OWA implement this. My simple understanding is that  a feed reader/aggregator would check for updates at predetermined times using the feed.xml file. Would this request be made to the PHP framework running on the server, which in turn would make an appropriate request to the Server OS? If this is the case, I understand that the stats for downloads can then be saved to a DB.

Thanks.

**Comment by padams** [comment]
Yes. You would have to intercept the request and then hit OWA's log.php to track a tracking event.
