### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ianhaney** [padams/Open-Web-Analytics#140]
Hi

I keep having trouble with logging in on a fresh install, I am putting the correct username and password in but just loads the login form again, I requested a new password and changed it and managed to login in chrome with it but can't seem to in Firefox

Can anyone help please

Thank you

**Comment by Ekwav** [comment]
the right username is admin, did you write admin as username? I also had some trouble with that :)

**Comment by k9dug** [comment]
I also had this problem. Created a database, installed OWA via the installer pages, then when it came to logging in I couldn't. I tried the email address I had registered at installation: didn't work. Maybe I missed the bit where I had to create a username? I don't remember seeing it. I deleted it all and started again. This time I saw that in the final screen of installation it does actually say to log in using the username "admin". A simple oversight.

It might be easier for new users to know their username if the install procedure required one to be entered. (This might also be more secure, as 'admin' is quite guessable...).

OK, now to try it out!

**Comment by Clarin98** [comment]
Same problem here, and I am sure of my user and pass (keepassx help me)... After installation and first login doesn't happen nothing... 

My php version:
PHP 5.6.22-0+deb8u1 (cli) (built: Jun 14 2016 18:21:48) 
Copyright (c) 1997-2016 The PHP Group

MySQL:
+-------------------------+------------------+
| Variable_name           | Value            |
+-------------------------+------------------+
| innodb_version          | 5.5.44           |
| protocol_version        | 10               |
| slave_type_conversions  |                  |
| version                 | 5.5.44-0+deb8u1

**Comment by padams** [comment]
is there a row in the owa_user table? If so, then turn on debug mode and start looking at the log file to see what errors might be happening.
The authentication code definitely works so I’m thinking it an environment issue.

**Comment by Clarin98** [comment]
Yes: 
![captura de pantalla de 2016-06-24 16-50-59](https://cloud.githubusercontent.com/assets/14655066/16351568/39c23bfc-3a2c-11e6-88da-62cbb6cd4367.png)
But sorry, I don't know how to turn on the debug mode, I am novice :(

**Comment by BobDCoder** [comment]
just adding to the possible solution of logging on. and I'm just saying these were some of my observations and my solution to my issue of logging on.

I noticed that when creating the account (installing online web host, not linux or other os) that I was in Https mode. However later when I returned to the index to log back in (after the install) it was Not site secure and other times/sometimes site secure (http, https -secure, https- greyed out) .... those were issues on my host set up, but seem to effect the log in some how.

Lastly I noticed that sometimes the www. would appear in the url and that definitely caused me issues. So I just manually typed in the https url and it seemed to work as I was able to log in. 

So you might consider (in the owa folder) to write an htaccess file to rewrite it to a www or non www, as well as consider the security https. just saying these were some of my observations and my solution to my issue.

**Comment by BobDCoder** [comment]
I offer no conclusions in the above, just some issues I was able to resolve logging in. Use to be a Sys Analyst, DBA, Web Dev, Software App Dev. so maybe I do or don't know what I am talking about here.

**Comment by padams** [comment]
No worries!  But just to be clear, OWA does not rewrite urls. You define the URL of the install in the config file and OWA will faithfully assume you've taken care of the rest.

If you find a hard coded url or http reference please file a bug to have it removed.
