### ISSUE TITLE
WordPress plugin Install not logging anything

### ISSUE THREAD

**Issue by smycroft** [padams/Open-Web-Analytics#141]
Installed the WordPress plug-in. Set-up, etc. and whilst it is recording actions it is not recording any activity on the site (even when I've created the activity/visits/page views, etc).  e.g. "Site Metrics" has everything at zero and says "No data available for this period" (and I've checked the period covers the range I have generated site activity)

Checked the footer.php contains the correct wp_footer() line.  The mySQL WordPress has loads of owa_ prefixed tables.

Any ideas what I might have done wrong or what steps I need to take to diagnose issues ?

**Comment by padams** [comment]
This is fixed in master.
