### ISSUE TITLE
Output sorting

### ISSUE THREAD

**Issue by TheOne98282** [padams/Open-Web-Analytics#146]
I've recently install v1.5.7.  I like the system, but would like to know the proper method to enable sorting of the Site Roster by domain name?  I'm fairly new to PHP, so be gentle.

**Comment by padams** [comment]
You would resort the site list for that page's controller (sites.php)

**Comment by ke4zzy** [comment]
Is there a resort snippet we could use for sites.php? 
Having a list of over 50 sites and all with no listing capability... Well would be nice to have it sorted alphabetically.
