### ISSUE TITLE
Datepicker for period doesn't show up

### ISSUE THREAD

**Issue by mad73923** [padams/Open-Web-Analytics#15]
I have a small webpage running on http://www.square7.ch/ .
Anyhow the datepicker for the period in the top right isn't shown. I ran the firefox-console and got the following message:
"Not well-formed"
This error points on line 8, 39, 40, 41 and 43 in modules/base/templates/filter_period.tpl. I guess it's because of the "<*" characters. This might be a server-sided error but is there a way doing this more compatible? Thanks!

**Comment by padams** [comment]
Strange. Which version/os of firefox are you seeing this on?

**Comment by padams** [comment]
Fix is in master.
