### ISSUE TITLE
action values are not returned by data access API

### ISSUE THREAD

**Issue by mehtanin** [padams/Open-Web-Analytics#150]
Hi,

I have added action tracking in some areas (click areas) of my project by the following code:

> var actionTrackerOne = function(){
>       OWATracker.trackAction('Cooking', 'One',  'Best Chicken Parmesan', 10);
> }
> var actionTrackerTwo = function(){
>       OWATracker.trackAction('Fishing', 'Two',  'Best Chicken Parmesan Recipe', 10);
> }

It tracks actions accordingly in the OWA admin panel.

But when I tried to access the JSON//XML data by data access API i.e. 

> http://yourdomain/owa/api.php
> ?owa_apiKey=b6b9c9b9016d2b8b3b9b52e67eba06a3
> &owa_do=getResultSet
> &owa_metrics=actions,visitDuration,bounces,repeatVisitors,newVisitors,visits,pageViews
> &owa_dimensions=date,browserType
> &owa_constraints=browserType%3d%3dFirefox%203.5
> &owa_startDate=20100312
> &owa_endDate=20100331
> &owa_limit=10
> &owa_siteId=your_site_id
> &owa_format=xml

It gives an exception called:  

```
callback(<br />
<b>Fatal error</b>:  Call to a member function getName() on null in <b>C:\xampp\htdocs\modules\base\classes\resultSetManager.php</b> on line <b>1675</b><br />
```

This is to mention that I had modified the default REST method by adding the keyword "actions" in the owa_metrics section to get my sites action data.

It works fine with the default value i.e. owa_metrics=visitDuration,bounces,repeatVisitors,newVisitors,visits,pageViews. But it gives the above error when I am trying to access action data by it.

How can I get my action data by data access API?

**Comment by padams** [comment]
Its likely you are trying ot do an illegal combination of metrics as I dont think you can mix pageViews with actions.

Do the Action reports in the GUI return data? If so just watch the API requests thatpage makes to see how it's done.
