### ISSUE TITLE
OWA 1.5.7 don't work on MediaWiki 1.25.5

### ISSUE THREAD

**Issue by hikaruhenry** [padams/Open-Web-Analytics#153]
My MediaWiki is 1.25.5 ,PHP is 5.6.18 (apache2handler),Mysql is 5.6.29,and owa is correctly installed.
I can find the owa js tracker code in my website source code but it not run,all statistics is zero or 0%.
What's worng?

**Comment by padams** [comment]
Closing as this ia dupe of #460
