### ISSUE TITLE
Historical data not being saved

### ISSUE THREAD

**Issue by dac2020** [padams/Open-Web-Analytics#154]
Wordpress 4.4.2
OWA 1.5.7 and 1.5.8

Every day is groundhog day with OWA running under WordPress. 
There are no historical details, it's as if it is starting from scratch every so often, even multiple times per day.

Data is always fairly current, long term displays show very little more and yet we can clearly see plenty of traffic. Here are some errors we've seen in the logs. Both seem to mention /wp-login/ and wp-admin so guessing this is not related and something to do with where ever we are protecting wp-admin logins. Just posting them in case one or more is possibly related.

[access_compat:error] AH01797: client denied by server configuration: /var/www/htm
l/wp-admin/admin-ajax.php, referer: https://www.domain.com/

PHP Warning:  fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/wp-content/plugins/owa/includes/Snoopy.class.php on line 1142 
referer: http://www.domain.com/wp-login.php?redirect_to=http%3A%2F%2Fwww.domain.com%2Fwp-admin%2F&reauth=1

PHP Warning:  fsockopen(): unable to connect to api.hostip.info:80 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /var/www/html/wp-content/plugins/owa/includes/Snoopy.class.php on line 1142
referer: http://www.domain.com/wp-login.php?redirect_to=http%3A%2F%2Fwww.domain.com%2Fwp-admin%2F&reauth=1

**Comment by padams** [comment]
turn off geolocation or use the maxmind module to make that error go away.
No idea why you are not seeing historical data. is it in your database?

**Comment by dac2020** [comment]
Hi, yes, we did that also, tried both with and without the module. 

I can look in the DB, which table would contain that?

**Comment by dac2020** [comment]
Here is an example. We have a post we created about a month ago. It's had 152 Likes so we know at least a fair number of people read the article which is on the site itself. 

However, in the reports, if I look to see how many times that article was looked at, the reports say 3 times.

**Comment by padams** [comment]
that could be the way you’ve implemented the tracking tag. hard to tell from here. To debug this, load the page and watch the HTTP connections via firebug or some inspector to see if the request to OWA is getting fired or if there are errors on the console.

**Comment by dac2020** [comment]
As I understood it, when using the wordpress plugin, that tag is automatically handled? Or am I not understanding something?

Do requests look something like this?

<input type="hidden" value="/wp-admin/index.php?page=owa&owa_siteId=b6t32tef5302fee2c92b95cd360cecb4f&owa_period=last_seven_days&owa_do=base.reportDashboard" name="_wp_http_referer">

If so, yes, I'm seeing those.

**Comment by dac2020** [comment]
I also found this error

Maxmind DB file could is not present at: /var/www/html/wp-content/plugins/owa/owa-data/maxmind/

I used the Administrator function to install the module.

**Comment by padams** [comment]
Yes you need to download and install the maxmind DB file. See the wiki.

**Comment by dac2020** [comment]
Ah, I'll take a look. I thought I read that activating the module takes care of that.

**Comment by dac2020** [comment]
Alright, I downloaded it, then enabled the feature then enabled the module. I didn't see any errors.
If this helps at all, to know what's working or not, one log snip shows;

"GET /wp-content/plugins/owa/log.php?owa_timestamp=1458272020&owa_event_type=dom.click&owa_dom_element_name=%28not+set%29&owa_dom_element_value=%28not+set%29&owa_dom_element_id=%28not+set%29&owa_dom_element_class=%28not+set%29&owa_dom_element_tag=A&owa_page_url=http%3A%2F%2Fwww.mydomain.com%2Farticle1122%2F&owa_page_width=1080&owa_page_height=739&owa_dom_element_text=Check+Residential+Outages&owa_target_url=http%3A%2F%2Fwww.cogeco.ca%2Fweb%2Fon%2Fen%2Fresidential%2Fsupport%2Foutages&owa_dom_element_x=292&owa_dom_element_y=1388&owa_click_x=360&owa_click_y=1401&owa_is_new_visitor=true&owa_visitor_id=1458272008911550892&owa_fsts=1458272008&owa_dsfs=0&owa_last_req=&owa_session_id=1458272008892180243&owa_is_new_session=true&owa_nps=1&owa_dsps=0&owa_medium=referral&owa_source=google.com&owa_search_terms=%28none%29&owa_session_referer=https%3A%2F%2Fwww.google.com%2F&owa_HTTP_REFERER=https%3A%2F%2Fwww.google.com%2F&owa_page_title=article+1122-+Links+%26+Contacts+-+mydomain+Networks&owa_site_id=xxx HTTP/1.1" 200 42 "http://www.mydomain.com/article1122/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4"

**Comment by dac2020** [comment]
So, last night I looked before I left and saw
47 visits
46 unique visitors
60 page views

Yet, this morning, it's
46 visits
46 unique visitors
59 page views

Weird.

**Comment by sudojudo** [comment]
Did you ever figure it out, dac2020?  This issue is driving me mad.

**Comment by dac2020** [comment]
Sorry, I finally just got rid of it since I could not find enough help to use it properly. 
The final straw was when it broke after the wordpress 4.5.1 update.
