### ISSUE TITLE
domstream wordpress

### ISSUE THREAD

**Issue by osteopathievilleraymontreal** [padams/Open-Web-Analytics#155]
Hi,
I take a chance to ask how to remoove old domstream because my server is out of space. 

I am not a professional on computer, and in english also.

By the way your app is incredible, so much things you can do with (i ll probably never use)

thanks and BRAVO again

**Comment by padams** [comment]
Just truncate the owa_domstreams table in your database.

**Comment by osteopathievilleraymontreal** [comment]
Yes, I saw your old comments https://github.com/padams/Open-Web-Analytics/issues/23

can you make a command from the WP dashboard ?

thank you again for the plug in and for your quick answer
