### ISSUE TITLE
OWA not compatible with Mediawiki 1.26.2

### ISSUE THREAD

**Issue by alexander-jiang** [padams/Open-Web-Analytics#156]
I followed the installation instructions listed here: http://wiki.openwebanalytics.com/index.php?title=Installation#MediaWiki_Installation

And I'm unable to complete step 5 because I'm unable to load the list of Special Pages (a 500 error). I checked the Apache error logs on my server, and I got the error:
`Call to undefined method SpecialPage::SpecialPage() in /var/lib/mediawiki/extensions/OpenWebAnalytics/mw_plugin.php on line 499`

I think it comes from an issue introduced by MW 1.17, as noted on this bug report: https://www.mail-archive.com/wikibugs-l@lists.wikimedia.org/msg53602.html

And I tried to replace line 499 with the suggested `parent::__construct()` constructor syntax (as documented in PHP http://php.net/manual/en/language.oop5.decon.php). In other words, I tried replacing:
`parent::SpecialPage('Owa', 'owa_view');` with `parent::__construct('Owa', 'owa_view');`

And that seemed to solve the first error, but now I got another error: `PHP Fatal error:  Call to a member function addMessages() on a non-object in /var/lib/mediawiki/extensions/OpenWebAnalytics/mw_plugin.php on line 577`

And this mediawiki variable was removed in MW 1.18.0 (https://www.mediawiki.org/wiki/Manual:$wgMessageCache). 

Given that the OWA integration mediawiki extension has only been tested up to MW 1.16, I won't really continue playing this whack-a-mole game, but I've left this so that, if anyone else wants to go down this rabbit hole, you at least have a place to start.

Also: I'm running this Mediawiki 1.26.2 installation on a LAMP server (with Ubuntu version 14.04.3 and PHP version 5.5.9).

**Comment by eddalexandre** [comment]
I got the same problem here on as Linux Cent OS server. It just won't load the Special Pages on my wiki. :/

**Comment by padams** [comment]
Can someone with a recent mediawiki install and dev environment patch this please?

**Comment by kellewic** [comment]
Add the following in place of __construct():
```
function __construct() {
     parent::__construct('Owa', 'owa_view');
}
```
Add the following in place of loadMessages():
```
public static function onMessagesPreLoad( $title, &$message ) {
    if ($title == "Owa"){ $message = "Open Web Analytics"; }
 }
```
Add the following to LocalSettings.php:
```
$wgHooks['MessagesPreLoad'][] = 'SpecialOwa::onMessagesPreLoad';
require_once "$IP/extensions/owa/mw_plugin.php";
````

**Comment by padams** [comment]
can you submit a pull request?

**Comment by padams** [comment]
adding reference to #460
