### ISSUE TITLE
Open Web Analytics tracking doesn't work

### ISSUE THREAD

**Issue by xbayler** [padams/Open-Web-Analytics#158]
Hi there!

When I installed OWA 1.6 I put a sample web that i did just to check that this works fine.
Then I put the JavaScript Tracker Code inside the page named info.php and I won’t be able to see any analytic statistics from owa after I refreshed my web several times, what i did wrong?

This is the page "info.php":

```
<html>
    <head>
        <!-- Start Open Web Analytics Tracker -->
        <script type="text/javascript">
        //<![CDATA[
        var owa_baseUrl = 'http://localhost/owa/';
        var owa_cmds = owa_cmds || [];
        owa_cmds.push(['setSiteId', 'c76352tr4512345f6789a0b626ef048d']);
        owa_cmds.push(['trackPageView']);
        owa_cmds.push(['trackClicks']);
        owa_cmds.push(['trackDomStream']);

        (function() {
            var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
            owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
            _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
            var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
        }());
        //]]>
        </script>
        <!-- End Open Web Analytics Code -->
    </head>
    <body>
        WORKS!!!
    </body>
</html>
```

**Comment by padams** [comment]
You need to run OWA under a fully qualified domain name, not localhost.

**Comment by xbayler** [comment]
I put my domain name but i get the same error, I can enter to OWA with it but i dont see any analytics statistics when i put the JS on other web in the same lan.

I can enter to OWA on all PC when i put the domain name.

**Comment by padams** [comment]
You can't just change the URL in the tracking code you actually need to serve the web page from a FQDN.

**Comment by xbayler** [comment]
I just delete the OWA and i reinstall them all.

**Comment by xbayler** [comment]
I reinstall the OWA and i put on my apache and DNS that this machine get the name like owa.maist.org

**Comment by xbayler** [comment]
SOLUTION!
I just check all [requeriments](http://wiki.openwebanalytics.com/index.php?title=Technical_Requirements) and i see that i need "Strict SQL Mode" disabled.

I don't put sql-mode="" before because my "my.cnf" file dont has this line but when i put it and i restart mysql all works fine!!

**Comment by sudojudo** [comment]
Thank you for following up, xbayler.
