### ISSUE TITLE
[solved] Show public client IP address

### ISSUE THREAD

**Issue by JjfBcn** [padams/Open-Web-Analytics#159]
Hi, we've OWA behind a loadbalancer and OWA is showing always the IP of the loadbalancer instead of the real client public IP, how could we solve this?

Thanks.

**Comment by Decesus** [comment]
This is going to need to be configured on your load balancer.  There's nothing the servers behind the load balancer can do about that.

**Comment by JjfBcn** [comment]
Hi, finally we could see the real public IP of the clients by adding a parameter in the loadbalancer (x-forwarded) and configuring the module RPAF in OWA Apache WS.

This is the link of the  RPAF module, [https://github.com/gnif/mod_rpaf], just in case it could be useful for someone... I tried with the included module mod_remoteip with no luck, with this parameter it worked fine.

**Comment by cbake6807** [comment]
mod_rpaf isn't really the best solution, because it requires a lot of overhead work to install.. The application could easily check the HTTP headers for the standard header indicating a forwarding proxy is in use. 

# ./modules/base/classes/trackingEventHelper.php

    static function ipAddressDefault() {
        return owa_coreAPI::getServerParam($this->getIp());
    }

  # addition
    function getIp() {
        if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
            return 'HTTP_X_FORWARDED_FOR';
        } else {
            return 'REMOTE_ADDR';
        }
    }

**Comment by cbake6807** [comment]
This solution solved my issue:

PR Submitted - https://github.com/padams/Open-Web-Analytics/pull/196

**Comment by padams** [comment]
equivalent fix is in master now.
