### ISSUE TITLE
Heat map tool and mouse movements

### ISSUE THREAD

**Issue by pedro35012** [padams/Open-Web-Analytics#16]
Hello,
does Open Web Analytics support Heat map tool and mouse movements?I know there is Comparison on the OWA homepage, where I can find it supports both function, but there are stats for version v1.5.0. Does new version really support Heat map tool and mouse movements?Is it free or is it necessary to pay to use this features?

**Comment by mstrokin** [comment]
If you select a page (for example, in "Top pages") then you will have the links for heatmap overlay (and domstream&dom clicks as well)
