### ISSUE TITLE
403 Forbidden ??

### ISSUE THREAD

**Issue by adrianschembri** [padams/Open-Web-Analytics#160]
Hi Guys,

I have an issue making OWA work. I am continually getting 403 (Forbidden) on log.php.
I have followed all the steps for all the right permissions to directories, however I might be missing some important step.

I am using the Async javascript method and OWA is installed in my public_html/owa while my project is also installed on the same server on public_html/project

Permissions:
public_html/owa (inlcluding all sub directories and files) = 755
public_html/owa/owa-data = 777
public_html/owa/log.php = 750
public_html/owa/cli.php = 700

Strangely enough Domstreams are working and even PHP tracking methos is also working fine, however I would like to use the JS method..... any body can help please?

Thanks Guys...will provide any additional info you require ....

**Comment by padams** [comment]
sounds like a webserver config issue.

look to see what url the OWA JS tracker is generating using a browser inspector or Firebug.

Domstreams make a POST request, while pageview and action tracking issue GET requests.

**Comment by adrianschembri** [comment]
This is the tracking being generated of which is returning the 403 error.
P.S. I have left all options in the tracker script to default.

http://owa.excitableweb.com/log.php?owa_timestamp=1459887128&owa_event_type=dom.click&owa_dom_element_name=%28not+set%29&owa_dom_element_value=%28not+set%29&owa_dom_element_id=%28not+set%29&owa_dom_element_class=%28not+set%29&owa_dom_element_tag=FOOTER&owa_page_url=http%3A%2F%2Fstage.bestlistcasinos.com%2Fcoming-soon&owa_page_width=1920&owa_page_height=631&owa_html_element_text=&owa_dom_element_x=0&owa_dom_element_y=849&owa_click_x=216&owa_click_y=880&owa_visitor_id=1459877740888474671&owa_fsts=1459877740&owa_dsfs=0&owa_last_req=1459887058&owa_session_id=1459887058698510425&owa_nps=2&owa_dsps=0&owa_medium=direct&owa_source=%28none%29&owa_search_terms=%28none%29&owa_session_referer=%28none%29&owa_HTTP_REFERER=&owa_page_title=BestListCasino+%7C+Listing+the+best+casinos+online&owa_site_id=07d016636dd0f8d7e29e6e645c9323da&

**Comment by padams** [comment]
Is that space in the log.php really there?

**Comment by adrianschembri** [comment]
actually yes its there!! .... look at the screen shoot attached.... how can I fix that?
![untitled-1](https://cloud.githubusercontent.com/assets/18293116/14306785/aa807174-fbca-11e5-9dc9-8e6f33071ffc.jpg)

**Comment by padams** [comment]
I was referring to the space between the "o" and the "g" in log.php in your first post which appears to be a typo when you pasted the URL. I'm not sure whats going on in that screenshot as I've never seen a malformed request like that before. Is there a live page where you have the JS tracking tag deployed?

**Comment by adrianschembri** [comment]
aahh... no that is not really there.... what I am getting is exactly shown in that console screen shot.
Sure thing ...here you go ... http://stage.bestlistcasinos.com/coming-soon

**Comment by adrianschembri** [comment]
in my localhost is now working perfectly fine! i added {literal} tags around the script (cause i am using smarty templates) but nothing happens when deployed on stage ...this is getting stranger by the minute!

**Comment by padams** [comment]
There is nothing wrong with the JS tracker here. Despite your screen shots the requests being generated properly. the issue is that our web server is rejecting the request due to it's length. Some web hosts have very short limits on GET request length. You'll need to increase the limit. The reason Domstreams work is that hey use POST requests and web hosts usually allow for large POST requests.

**Comment by adrianschembri** [comment]
mmmm..... interesting, I'll check server configs then and will get back with any findings! ...thanks for now padams

**Comment by adrianschembri** [comment]
padams.... do you know from where I can modify such settings?

**Comment by padams** [comment]
I believe it's a setting in the apache config.

**Comment by adrianschembri** [comment]
I actually made some re-search about this and it's seems that he error return should be 414 if that would be the case.... 
http://stackoverflow.com/questions/266322/is-there-a-limit-to-the-length-of-a-get-request

**Comment by padams** [comment]
Should be but not always. The reason I think it's a length issue is that if you simply shorten the request length by removing a few params, then the status code changes to 200...

**Comment by adrianschembri** [comment]
how can I do that and still track same results?

**Comment by padams** [comment]
you can't. i simply truncated the request by hand to see what was happening. You need to reconfigure your web server to handle longer requests. 

BTW, that request is only 830 character long well below the 2000 char limit for most browsers.

**Comment by adrianschembri** [comment]
Yes that is the strange thing about this because its much shorter then the allowed limit..... can't seem to find any settings for this in the php.ini file

**Comment by adrianschembri** [comment]
i found this....
[suhosin]
suhosin.get.max_value_length = 2048

I'll give it a try.
