### ISSUE TITLE
Open Web Analytics usage for mobile application tracking.

### ISSUE THREAD

**Issue by fragmadata** [padams/Open-Web-Analytics#161]
Hi All,

Has anyone used open web analytics in mobile application tracking? 
We are looking to use OWA in a mobile application, by utilizing the log.php endpoint. Is there any documentation where I can read about the event recording end points. 
Please let me know any pointers and issues if faced in mobile tracking with OWA.

**Comment by siva538** [comment]
@padams / team, can you please help with this question? Whether ionic framework based tracking is possible with OWA? 

Or are there any plugins available for such ?

**Comment by padams** [comment]
OWA can be integrated into any framework. You just need someone knowledgeable about the framework to know where the integration points are.

I’ve personally never worked with it.
