### ISSUE TITLE
GeoIP Location not working.

### ISSUE THREAD

**Issue by Decesus** [padams/Open-Web-Analytics#162]
Hello!  First let me say thank you for an awesome and free web tracking platform!

I don't know if the change to hostip (Removes hostip as the default geolocation provider) in 1.5.9 was supposed to remove this functionality, but ever since upgrading to 1.6.0 my error logs are filled with these errors:

```
08:27:07 04/06/16 27699 [] The value "" is not a valid IP address. // #0 /var/www/webdir/modules/maxmind_geoip/classes/maxmind.php(103): MaxMind\Db\Reader->get('')
#1 [internal function]: owa_maxmind->getLocation(Array)
#2 /var/www/webdir/modules/base/classes/eventDispatch.php(249): call_user_func_array(Array, Array)
#3 /var/www/webdir/modules/base/classes/geolocation.php(64): owa_eventDispatch->filter('geolocation', Array)
#4 /var/www/webdir/owa_coreAPI.php(1323): owa_geolocation->getGeolocationFromIp(false)
#5 /var/www/webdir/modules/base/classes/trackingEventHelpers.php(610): owa_coreAPI::getGeolocationFromIpAddress(false)
#6 [internal function]: owa_trackingEventHelpers::resolveCountry(false, Object(owa_event))
#7 /var/www/webdir/modules/base/classes/eventDispatch.php(249): call_user_func_array('owa_trackingEve...', Array)
#8 /var/www/webdir/modules/base/classes/trackingEventHelpers.php(121): owa_eventDispatch->filter('country', false, Object(owa_event))
#9 /var/www/webdir/modules/base/processEvent.php(93): owa_trackingEventHelpers->setTrackerProperties(Object(owa_event), Array)
#10 /var/www/webdir/owa_controller.php(216): owa_processEventController->pre()
#11 /var/www/webdir/owa_coreAPI.php(788): owa_controller->doAction()
#12 /var/www/webdir/owa_coreAPI.php(1211): owa_coreAPI::performAction('base.processEve...', NULL)
#13 /var/www/webdir/owa_coreAPI.php(897): owa_coreAPI::handleRequest(Array, 'base.processEve...')
#14 /var/www/webdir/modules/base/classes/client.php(348): owa_coreAPI::logEvent('unknown_event_t...', Object(owa_event))
#15 /var/www/webdir/log.php(88): owa_client->logEventFromUrl()
#16 {main}
```

Thank you for your time!

**Comment by padams** [comment]
Definitely not intentional. is there an IP address in the tracking event? You should see it in the logs along with the other params of the event as well as lines that show it being filtered like so:

Filtering ip_address
20:29:10 04/06/16 16434 [debug] Filter: owa_trackingEventHelpers::ipAddressDefault. Value passed: 
20:29:10 04/06/16 16434 [debug] Filter: owa_trackingEventHelpers::ipAddressDefault. Value returned: 24.6.53.xx

**Comment by Decesus** [comment]
I enabled debug logging and saw the lines you mentioned and they're populated with a proper IP address (I changed it for privacy purposes).  Interestingly enough, a little further down I saw the IP lookup come back with the right data and further down the final array of data with the right info in it too!
```
07:36:31 04/07/16 9778 [debug] Filter: owa_trackingEventHelpers::ipAddressDefault. Value passed: 
07:36:31 04/07/16 9778 [debug] Filter: owa_trackingEventHelpers::ipAddressDefault. Value returned: 138.0.0.0
.........
07:36:31 04/07/16 9778 [debug] Filter: owa_maxmind::getLocation. Value passed: Array
(
    [ip_address] => 138.0.0.0
    [city] => 
    [country] => 
    [state] => 
    [country_code] => 
    [latitude] => 
    [longitude] => 
)

07:36:31 04/07/16 9778 [debug] Filter: owa_maxmind::getLocation. Value returned: Array
(
    [ip_address] => 138.0.0.0
    [city] => san francisco
    [country] => united states
    [state] => california
    [country_code] => US
    [latitude] => 37.7898
    [longitude] => -122.3942
    [continent] => na
    [continent_code] => north america
    [state_code] => ca
    [postal_code] => 94105
)


.....................

07:36:31 04/07/16 9778 [debug] Dispatching base.page_request event with properties: Array
(
    [guid] => 1460039791914545977
    [timestamp] => 1460039791
    [event_type] => base.page_request
    [visitor_id] => 1459944786246405507
    [fsts] => 1459944786
    [dsfs] => 1
    .............
    [country] => united states
    [city] => san francisco
    [state] => california
    [latitude] => 37.7898
    [longitude] => -122.3942


```

I turned off the log debugging and those errors stopped coming through.  I checked the DB table "owa_session" and the right fields are populated with the state and city but in the Dashboard view of the site, the GeoIP field is blank and under the GeoIP section there's only an entry for {not set}.

I looked at the "location_dim" table in MySQL and there's a single entry for {not set}, and then nothing else.  Could that be causing this issue?

**Comment by padams** [comment]
I appears that the event handler for location only creates persists a location to the DB the first time it sees it. So… what likely is happening here is that OWA logged the location before you enabled the Maxmind extension. 

We could change the logic here to do an update when the values change but that would create a “slowly changing dimension” which is means that reports and group bys would be changing over time. Probably want to add a global switch to turn that on/off as that could cause issues for some that rely on historical facts to remain frozen in time.

In the meantime you could probably just truncate the owa_dim table and OWA will then populate it correctly the next time is sees the location now that Maxmind is enabled.

**Comment by Decesus** [comment]
Awesome, that worked although I did have to clear the cache from the settings menu as well before it started working again.  Thank you again!

**Comment by siva538** [comment]
I am checking the demo site provided demo.openwebanalytics.com/owa.. and I still see that the geo-location is set to "not set" and country/city is not displayed. 

Isn't this fixed or is there a plan to fix this?
