### ISSUE TITLE
Wikipedia page error

### ISSUE THREAD

**Issue by avenantsoftware** [padams/Open-Web-Analytics#163]
Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

Warning: preg_match_all(): Compilation failed: group name must start with a non-digit at offset 4 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 700

Warning: Invalid argument supplied for foreach() in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 701

Warning: preg_replace(): Compilation failed: group name must start with a non-digit at offset 4 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 705

Warning: preg_match_all(): Compilation failed: group name must start with a non-digit at offset 4 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 700

Warning: Invalid argument supplied for foreach() in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 701

Warning: preg_replace(): Compilation failed: group name must start with a non-digit at offset 4 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 705

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

Warning: preg_match(): Compilation failed: group name must start with a non-digit at offset 8 in /home/padams/wiki.openwebanalytics.com/includes/MagicWord.php on line 722

**Comment by kmiloaguilar** [comment]
I was coming here to create this issue.

**Comment by padams** [comment]
wiki has been moved to github. thanks.
