### ISSUE TITLE
PHP7 MySQL access changes..

### ISSUE THREAD

**Issue by maniappan** [padams/Open-Web-Analytics#164]
I had modified the MySQL access calls for PHP7, attached is the file(had to rename as txt extension to upload here), you can consider for adding it into the repository. If it is already done, please ignore.
[owa_db_mysql.php.txt](https://github.com/padams/Open-Web-Analytics/files/222328/owa_db_mysql.php.txt)

**Comment by padams** [comment]
I refactored and added to master. thanks.
