### ISSUE TITLE
mySQL error

### ISSUE THREAD

**Issue by ca-cdn** [padams/Open-Web-Analytics#165]
I've never seen this before but then since mySQL is being deprecated I've always used MySQLi
Also for reference, I have another database on the same server which is fine.
Error seen is;
Headers and client library minor version mismatch. Headers:100010 Library:100106 - /home/path/to owa/plugins/db/owa_db_mysql.php

It seems this is a server configuration related issue rather than the OWA script itself but wanted to pass it along as suppressing the error with
`$this->connection = @mysql_connect(..`
doesn't seem to have any affect as the DB connection still fails.

Migrating to mySQLi would be the better long term option?

**Comment by padams** [comment]
What version of PHP is this happening under?

**Comment by ca-cdn** [comment]
After some further investigation, it seems my hosting provider was using PHP 5.3 and a quick upgrade to PHP 5.6 resolved the issue.
Obviously it still reports a notice (when error reporting is enabled) about MySQL being deprecated blah blah but at least it is just a notice so can be suppressed with @ while I finish up some other testing and development.
Thanks for the quick response though!!
