### ISSUE TITLE
log.php auto download?

### ISSUE THREAD

**Issue by pixeltopf** [padams/Open-Web-Analytics#166]
I just installed owa 1.6.0 yesterday to track my joomla site. Everything worked fine, but today some safari users tell me that they get an autodownload for log.php from the owa directory.

any1 experienced this strange thing and can tell me what I can do to prevent this?

**Comment by padams** [comment]
turn off domstream tracking in your tag.

**Comment by pixeltopf** [comment]
looks like that did it. I deleted "owa_cmds.push(['trackDomStream']);" from the javascript tag.

May I ask what this command does and why there is a autodownload for this file? Strangly enough it only happened when users a clickling on a link on facebook?!

**Comment by padams** [comment]
that’s a bug. domstream is a stream of DOM events that is used to show you to the mouse movements of users on your web page. Those streams are sent to OWA via POST request and somehow safari is getting confused. not sure where.
