### ISSUE TITLE
Can't open analytics link for the home page

### ISSUE THREAD

**Issue by holly-curata** [padams/Open-Web-Analytics#170]
Hi there,
I'm trying to access the Heatmap overlay and Domstreams functionality but can't find a way to get to the analytics for the home page (only the home page) because there's nothing to click on, like there is for the other pages. See attached.
![screen shot 2016-04-26 at 11 40 58 am](https://cloud.githubusercontent.com/assets/4299274/14804156/1d3b358a-0ba4-11e6-9c6c-1ffbdb936dab.png)

When accessing the Top Pages tab, the home page detailed breakdown analytics is inaccessible. I can access the other pages by clicking on the link but there's nothing to click for the home page.

Is there another way to get to the analytics for Home Page?

**Comment by padams** [comment]
This is fixed in master.
