### ISSUE TITLE
OWA Tracking doesn't work

### ISSUE THREAD

**Issue by eava** [padams/Open-Web-Analytics#173]
Hi,
We followed all the steps, installed OWA and generated the website code that we inserted in the html source file. I visited the page many times to test OWA but tracking is still 0. what do you think is the problem?

**Comment by colleenh218** [comment]
I'm having that problem, too. I'm wondering if anyone actually monitors these pages...??

**Comment by sirimala** [comment]
Hi, Same problem here. Any help appreciated.

**Comment by bschof** [comment]
Hi, same problem here too

**Comment by sirimala** [comment]
Hi, I have commented sql_mode="blahblah" to sql_mode="" in php.ini file. It worked for me. Hope this will help your problem.

**Comment by bschof** [comment]
Sorry can't understand that can you tell me what you did?

**Comment by sirimala** [comment]
There can be many problems for not storing data into database. One problem is strict mode restriction on database which is by default enabled. I'm using mysql database. below is the solution which worked for me.
1) To turn off strict mode in MySQL, edit the my.ini or my.cnf file and look for the sql-mode setting:
2) Change sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" (may not be exact line)
3) sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

**Comment by bschof** [comment]
I cannot find the php.ini file as I am on a server and not running as localhost. Any idea where it might be?

**Comment by sirimala** [comment]
my bad, it's not php.ini it is my.ini or my.cnf


Thanks and Regards,
Sreenath
