### ISSUE TITLE
Broken links in documents

### ISSUE THREAD

**Issue by dcb1101** [padams/Open-Web-Analytics#179]
I have created a custom reports page and need to access the OWA data. 

I was looking at the info on https://github.com/padams/Open-Web-Analytics/wiki/Data-Access-API
But there are many broken links. I need info on the specific Metrics & Dimensions. 

Also, any info on querying the database to get visit statistics would be very helpful. 

Thank you

**Comment by smendez-hi** [comment]
Any updates on this? I cannot find any documentation related to the REST API (broken link)

**Comment by AustinCooper79** [comment]
Is there any documentation on REST api or REST requests?

**Comment by padams** [comment]
Dupe with #268
