### ISSUE TITLE
Wiki / Documentation

### ISSUE THREAD

**Issue by Ivanovic123** [padams/Open-Web-Analytics#180]
Hello together, 

unfortunately, there are some broken links within the OWA Documentation. 
Could you please fix that? I need the Documentation of OWA for my Bachelor Thesis. :-) 

Broken Links: 
https://github.com/padams/Open-Web-Analytics/wiki/Database-Schema

https://github.com/padams/Open-Web-Analytics/wiki/Tracking-Event-Pipeline

**Comment by padams** [comment]
Schema is back up there.
