### ISSUE TITLE
Problem adding new website to track

### ISSUE THREAD

**Issue by ktlim86** [padams/Open-Web-Analytics#181]
Hi,

I have a problem adding a website.
Whenever I add the website, the page will show this 
```
Notice: Undefined index: in PATH_TO_OWA\owa\includes\Log-1.12.7\Log.php on line 589
Notice: Undefined index: in PATH_TO_OWA\owa\includes\Log-1.12.7\Log.php on line 589
```

I have checked that line on that file represent this line of code.

```
function priorityToString($priority)
    {
        $levels = array(
            PEAR_LOG_EMERG   => 'emergency',
            PEAR_LOG_ALERT   => 'alert',
            PEAR_LOG_CRIT    => 'critical',
            PEAR_LOG_ERR     => 'error',
            PEAR_LOG_WARNING => 'warning',
            PEAR_LOG_NOTICE  => 'notice',
            PEAR_LOG_INFO    => 'info',
            PEAR_LOG_DEBUG   => 'debug'
        );

        return $levels[$priority]; // here is the problem
    }
```

I am using localhost as the URL link.
Please advise. Thanks. :)

**Comment by padams** [comment]
You cannot use localhost. You need to use a fully qualified domain name. Please read the install page on the wiki and set your public URL properly.

**Comment by ktlim86** [comment]
Hi,

I managed to get it to work. Thanks. :)

**Comment by smitemesmith** [comment]
I'm having the same issue, Any idea how you fixed it?

**Comment by ogaip** [comment]
someone solved this problem?

my error log on nginx is:

2017/03/06 13:02:28 [error] 2496#2496: *66 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index:  in /path/to/owa/includes/Log-1.12.7/Log.php on line 589
PHP message: PHP Notice:  Undefined index:  in path/to/owa/includes/Log-1.12.7/Log.php on line 589" while reading response header from upstream, client: 10.10.100.1, server: owa.app, request: "POST /install.php?owa_action=base.installCheckEnv HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "owa.app", referrer: "http://owa.app/install.php?owa_action=base.installCheckEnv"

i'm running on ubuntu server 16.04 LTS
php 7.0

thanks
