### ISSUE TITLE
Can Open Web Analytic support DOM tracking user activity navigating across multiple pages?

### ISSUE THREAD

**Issue by ktlim86** [padams/Open-Web-Analytics#183]
Hi,

I have played around with OWA for sometimes. I like the DOM tracker feature where I can see the users activity on my web pages. I have a question to ask.

1) I would like to ask whether OWA support tracking the user activity navigating across multiple pages? E.g the user comes to the Page A and then he clicks on the Page B. Both pages are being tracked by the OWA and when I go to the DOM tracker and click Play, the OWA is able to playback the page the user has navigated from Page A to Page B.
Currently, the DOM tracker can track page as one URL and does not track how the user navigate from this page to that page. 

Thanks. :)

**Comment by padams** [comment]
No, Domstreams are only one page.
