### ISSUE TITLE
Is Open-Web-Analytics still being actively maintained?

### ISSUE THREAD

**Issue by Hopelessone** [padams/Open-Web-Analytics#184]
Hi,

I saw some github activity on March 28th 2016 that released version 1.6.0 and nothing much before that since 2 years, in fact the home page still shows a 2014 OWA 1.5.7 as the latest version. I like Open-Web-Analytics layout better than piwik.

My question is: Is this going to be actively maintained?

And how will it perform in high-traffic websites (1,000,000+ pageviews)?

and why not monetize it like this guy does? http://socialsharekit.com/#license

Thanks,

**Comment by ThePrudentNinja** [comment]
I'm curious about this myself. I'm beginning to think that development is either dead or REALLY slow. Would be nice to hear an official answer from a dev.

**Comment by padams** [comment]
Not dead, there are just not a lot of developers.
