### ISSUE TITLE
Integrate OWA with Azizi Search Engine

### ISSUE THREAD

**Issue by smanimania** [padams/Open-Web-Analytics#193]
Good morning, I am developing with Azizi Search Engine, a great php script to create a meta search engine using google/bing API.
it's possible integrate OWA with this search engine? With an API system or with code.
Thank you in advance,
Best Regards,
Roberto

**Comment by jaafarazizi** [comment]
yes it's possible to integrate OWA with [Azizi Search engine](https://azizisearch.com/) code. but you need to understand ASE how it's works & as ASE is based on Laravel 5. you need to know how laravel 5 new packages created. & make OWA as new package.
