### ISSUE TITLE
php based analytics only work when the page is called with a parameter

### ISSUE THREAD

**Issue by kwmkwm** [padams/Open-Web-Analytics#194]
Hello,

I've installed OWA, added the php code to my pages, and i almost have it working.  If I visit "page.php?anything" or "otherpage.php?something" they will both be logged and show up in the analytics.  However, if I do not include a parameter the pages will not be listed correctly.  All non-parameter pages seem to get lumped together in the Top Pages listing.  Does anyone have any suggestions?  My code is:

require_once('owa/owa_env.php');
require_once(OWA_DIR.'owa_php.php');
$owa = new owa_php();
$owa->setSiteId('XXXXXX');
$owa->setPageTitle('index page');
$owa->trackPageView();

**Comment by padams** [comment]
Likely fixed in master.
