### ISSUE TITLE
cannot access owa

### ISSUE THREAD

**Issue by lokyuxuan** [padams/Open-Web-Analytics#195]
i just follow the steps to install the OWA , after set the accounts , the link doesn't turn the dashbord 
it alway in the same page: the login page : : 

http://127.0.0.1:8091/OpenWebAnalytics/index.php?owa_do=base.loginForm&owa_go=http%3A%2F%2F127.0.0.1%3A8091%2FOpenWebAnalytics%2Findex.php&

**Comment by padams** [comment]
You need to run OWA under a qualified domain name not an IP address.
