### ISSUE TITLE
Question: Is it possible to track multiple site ids with a single tracking code? 

### ISSUE THREAD

**Issue by Nano2016** [padams/Open-Web-Analytics#197]
[This is a question, rather than an issue but all searches i've done lead to here, so I'm sorry if this isn't the right place for things like this]

The idea was do create an overview site in OWA to track all events from multiple other sites - e.g. to monitor all visitors of all sites with one click.
I used the code from "Using Multiple Trackers on the Same Web Page" mentiond in the section "Tracker" of the wiki.

Here is the code that i used:

``` javascript
owa_cmds.push(['setSiteId', '23b1c5bfc1ff8f096c03278ff53a7515']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);
owa_cmds.push(['OWATracker2.setSiteId', 'a71ff0b585aa37cff06071c63ea2c0c4']);
owa_cmds.push(['OWATracker2.trackPageView']);
owa_cmds.push(['OWATracker2.trackClicks']);
owa_cmds.push(['OWATracker2.trackDomStream']);
```

Both site ids are never tracked the same time.
Can this code be modified so that it works properly?

**Comment by padams** [comment]
Are you seeing two GET requests made by the browser? are there any javascript errors. Please post those as we can't analyze if this is a bug without more detailed information.
