### ISSUE TITLE
Cannot see visitors IP / some (not set) in interface for users

### ISSUE THREAD

**Issue by diecastgit** [padams/Open-Web-Analytics#198]
I cannot see any information about visitors IP addresses in the interface, and there are some (not set)'s in the interface that I am not sure what they should be, but feel like they maybe should be IP addresses(?)
![not-set-02](https://cloud.githubusercontent.com/assets/17716890/19096510/6c7383b2-8af9-11e6-9b2a-330e09f329bb.png)
![not-set-01](https://cloud.githubusercontent.com/assets/17716890/19096511/6c78dec0-8af9-11e6-994f-4679a0a3072d.png)

**Comment by padams** [comment]
OWA doesn't show the IP address unless you add it as a secondary dimension in reporting. Those (not set) values are got city and county location which require the use of the maxmind geoip module. See the wiki for how to activate that.
