### ISSUE TITLE
Get resultsRows  always empty

### ISSUE THREAD

**Issue by Erisbv** [padams/Open-Web-Analytics#199]
I'm using for the first time, but after installation I try to use the REST through CURL, but only returns empty even though visits data.
# 

http://bravu.com.br/_OpenWebAnalytics/api.php?owa_apiKey=MY_API_KEY&owa_siteId=f592708d04da3e38f2469e6a36af0cca&owa_startDate=20160905&owa_endDate=20161005&owa_metrics=visitDuration,bounces,repeatVisitors,newVisitors,visits,pageViews&owa_dimensions=date,browserType&owa_constraints=browserType%3d%3dFirefox%203.5&owa_limit=10&owa_do=getResultSet&owa_format=json
# 

```
    $query = $urlAnalytics
        . "&owa_siteId={$this->config['owa_id']}"
        . "&owa_startDate={$owa_startDate}"
        . "&owa_endDate={$owa_endDate}"
        . "&owa_metrics={$owa_metrics}"
        . "&owa_dimensions={$owa_dimensions}"
        . "&owa_constraints=browserType%3d%3dFirefox%203.5"
        . "&owa_limit=10"
        . "&owa_do=getResultSet"
        . "&owa_format=json";
    $curl = curl_init();                                // Create Curl Object
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);      // Allow self-signed certs
    curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);      // Allow certs that do not match the hostname
    curl_setopt($curl, CURLOPT_HEADER, 0);              // Do not include header in output
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);      // Return contents of transfer on curl_exec
    curl_setopt($curl, CURLOPT_URL, $query);            // execute the query
    $result = json_decode(curl_exec($curl));
```

**Comment by AustinCooper79** [comment]
I am having a similar issue.

Could you confirm if you resolved this and also where I locate my OWA apiKEY?

**Comment by padams** [comment]
API key is under user profile.
