### ISSUE TITLE
OWA "unique visitors" is wrong when using PHP tracker

### ISSUE THREAD

**Issue by josephernest** [padams/Open-Web-Analytics#201]
According to some test, OWA "unique visitors" is wrong when using PHP tracker.

This is how to reproduce the bug:
1. fresh new install of OWA
2. new website, let's say www.mywebsite.com
3. add PHP tracker to the website www.mywebsite.com
4. open www.mywebsite.com in browser, the "unique visitors" count goes to "1"
5. refresh www.mywebsite.com in same browser, the "unique visitors" count goes to "2"
6. **repeat step 5 : the "unique visitors" count will grow, even if it's the same visitor (same IP, same browser user agent, etc.)**

**Comment by padams** [comment]
You would have ot post some tracker code and browser request info for anyone to help debug this.  Feel free to re-open if you can do that. thanks.
