### ISSUE TITLE
Problems with PHP 7.0

### ISSUE THREAD

**Issue by 5381** [padams/Open-Web-Analytics#202]
Hi,

i am having some problems with open web analytics running on php 7.0. For example the page counters in the report overview do not appear. I managed to fix it with a php downgrade to 5.6.
![screen](https://cloud.githubusercontent.com/assets/22635765/19686501/b97abe1e-9ac1-11e6-9fe1-110e3c5d081d.PNG)

**Comment by padams** [comment]
likely a mysqli issue. should be fixed in master.
