### ISSUE TITLE
Gigantic database after two weeks of OpenWebAnalytics

### ISSUE THREAD

**Issue by josephernest** [padams/Open-Web-Analytics#204]
I'm using OWA (Open Web Analytics) since 2 weeks, for a few websites, with a total of < 10k page views and < 5k visits. This is the size, in MB, of a few tables in the `owa` database:

    | owa                | owa_session                                  |       2.80 |
    | owa                | owa_request                                  |       4.44 |
    | owa                | owa_click                                    |       5.30 |
    | owa                | owa_domstream                                |     238.28 |
    +--------------------+----------------------------------------------+------------+

**Is it normal to have ~ 250 MB of Open Web Analytics data for only 2 weeks, for a total of < 10k page views?**

**Does this mean it will be 6.5 GB per year with the same visit rate?** Or even ~ 65 GB of analytics data for 100k page veiws?

Is there something wrong, or is it the right amount of magnitude?

**Comment by padams** [comment]
Turn off downstream tracking. When you do not need it. It's recoding every mouse movement on every page for every visitor.

**Comment by josephernest** [comment]
Ok thanks! I switched 
> Log Domstreams. This setting controls whether OWA should should log Domstreams.
to Off.

If I turn this off, can I safely wipe out this data with this SQL command:

    delete from owa_domstream;

?

Suggested additions:

1. Can we make the description more explicit? Something like:

> Log Domstreams. This setting controls whether OWA should should log Domstreams, i.e. log every mouse movement on every page for every visitor. Warning: this can make the OWA database ten times bigger than without this feature.

2. I think this could be "off" by default, what do you think? If not, many users could have GB databases in a very short time

**Comment by padams** [comment]
yes it’s safe to truncate the domstream table.

I agree with the default setting change. feel free to submit a patch for that.

**Comment by josephernest** [comment]
Thanks @padams I won't submit a patch for that because my current OWA knowledge is too small to be able to do the things correctly, but feel free to implement it if you think it's worth.

**Comment by josephernest** [comment]
After a few weeks now, even if 

* I disabled Domstream loggin in the admin page

* I removed the table owa_domstream

now I can see that the table owa_domstream is back with a gigantic size (700 MB).

I had to delete it again manually.

It seems that setting "Log Domstream" to "Off" in Admin page hasn't been taken in consideration. (I did save the Settings after setting "Log Domstream" to "Off").

**Comment by padams** [comment]
Remove the trackDonsteam line from your tracker JavaScript.

--
Peter Adams

**Comment by josephernest** [comment]
Thank you very much.

Then you maybe should add this information in the configuration page:

Instead of:
> Log Domstreams
> This setting controls whether OWA should should log Domstreams.
> [OFF]

you could write something like:

> Log Domstreams
> This setting controls whether OWA should should log Domstreams. This allows to replay sites visits with the visitor's eyes. Please note that this option can make the database ten times larger than without. 
> [OFF]
> If your turn this option off, please update your javascript tracking codes by removing `owa_cmds.push(['trackDomStream']);`.

or if not here, you could put such informations in the doc somewhere.

**Comment by padams** [comment]
The fix for the broken config control is now in master so that you no longer need to edit the tracking code. Next step is to move domstreams to their own module that needs to be explicitly activated.
