### ISSUE TITLE
tracking code issue

### ISSUE THREAD

**Issue by ianhaney** [padams/Open-Web-Analytics#206]
Hi

I have installed open web analytics on a website and went to generate a tracking code but I just get a white page instead

The URL is http://www.clickhomes365.co.uk/stats/index.php?owa_action=base.sitesInvocation&amp;owa_siteId=7c6cdb3ad707dd602089676666257bf1

Can anyone help me please as to what the error could be?

Thank you

Ian

**Comment by ianhaney** [comment]
I managed to get it installed and got to the login screen but when I login, it goes to a blank white page, my php version is 5.6

**Comment by ianhaney** [comment]
has anyone got a updated version of open web analytics in mysqli or pdo please

**Comment by padams** [comment]
Master has changes to support mysqli.
