### ISSUE TITLE
Default sites roster display

### ISSUE THREAD

**Issue by josephernest** [padams/Open-Web-Analytics#207]
Is the main "Sites roster" always displayed with visits and page views **per week**, i.e. last 7 days?
Can this easily changed in the admin panel?

If 7 days is a fixed constant value, we could make it more explicit for the new user with an additional sentence ".... are shown per week".

![](http://gget.it/427d6kmc/4.jpg)

**Comment by padams** [comment]
Closing duplicate issue.
