### ISSUE TITLE
Open web analytics

### ISSUE THREAD

**Issue by girisayan** [padams/Open-Web-Analytics#208]
Am using open web  anaalatics tools to track my web site usage. My requirement is to identify the
Number of unique users accessed my web site. Am using the Java script tracking code. Can you please help me how to identify the unique users, as  this functionality already exist in OWA or do we need to create the plugin for that.  Example : A visits the site and then B visits the site then A visits the site C visits the site
 I am expecting the out put as A visits the site twise B once and C once.

**Comment by padams** [comment]
unique visitors is a standard metric.

**Comment by girisayan** [comment]
My application will be logged by different users . I need the report at user level such as 
1. How many transaction
2. How many pages he visited
3. Etc..
How to advice in OWA? please help me.

**Comment by girisayan** [comment]
My application will be logged by different users . I need the report at user level such as

1.How many transaction
2.How many pages he visited
3. Etc..
How to achieve in OWA? please help me.

**Comment by padams** [comment]
You can certainly do this but it sounds like you need to code a custom report or use the API to get the data out in a way your application needs it.
