### ISSUE TITLE
"Last seven days" dropdown menu non visible

### ISSUE THREAD

**Issue by josephernest** [padams/Open-Web-Analytics#209]
In my current install of OWA, the field allowing to change the graph to 7 days or 1 month etc. isn't displayed. **How to change the graph to 1 month then?** (it is stuck to default=7 days)

It is like this:

![](http://gget.it/g46n8an0/1.jpg)

This is how it should be:

![](http://www.openwebanalytics.com/wp-content/uploads/2009/06/owa_dash.jpg)

**Comment by padams** [comment]
Make sure your server allows for serving files with the .tpl extension.

**Comment by josephernest** [comment]
Thank you very much @padams 

It would be interesting to put this in the documentation (maybe it already is? but I didn't find it), because it's not obvious.

The best would be to add a `.htaccess` in the root:

    AddHandler application/x-httpd-php .tpl

so that it will work out-of-the-box for anyone without having to care about PHP configuration. 

___

Something else: is it possible to **make "This month" by default** for every view (Sites roster + individual sites view) instead of "Last seven days" ?

**Comment by padams** [comment]
.tpl files really need to be replaced with .php. They are a hold over from the v1.0 design and are slowly being phased out.

**Comment by josephernest** [comment]
Ok. Until they are phased out, I suggest this one-line pull request:
https://github.com/padams/Open-Web-Analytics/pull/211

**Comment by padams** [comment]
The default time period is a global setting. You can change it in your config file by adding a setSetting call like this: $this->setSetting( 'base', 'default_reporting_period', 'last_thirty_days');
