### ISSUE TITLE
How to import data tracking from OWA?

### ISSUE THREAD

**Issue by musliman** [padams/Open-Web-Analytics#212]
I've just tried demo of OWA, but i can't find export/import data from OWA Dashboard. How can i do it?

**Comment by padams** [comment]
You can export data via the API. No import facility exists yet.

**Comment by musliman** [comment]
Thanks for respon, but where can i get more information and tutorial about that API ?

**Comment by musliman** [comment]
Please give me more advise for this problem. Iwant to import data from OWA but i don't know way to use the API.
