### ISSUE TITLE
Another super big table

### ISSUE THREAD

**Issue by josephernest** [padams/Open-Web-Analytics#215]
In my database, I see:

```
| owaa               | owa_queue_item                               |     747.92                                                                                         |
+--------------------+----------------------------------------------+-----------   
```
What is this table that produces 747 MB of data in just a few weeks? This surely isn't normal, how can we disable this?
(as a comparison, other analytics tools that I tried used 1% of this per year). 

*PS: I had a similar problem recently, and that time it was because of log domstream, that I disabled now, following your advice @padams.*

**Comment by padams** [comment]
Queue items are added when OWA can't find a valid session to match page views to. The idea is that the queue can be processed later in case the data is coming from another server which is delayed in relaying its logs.

Why that is happening to you isn't clear without seeing your logs. Turn on error logging and see what OWA is saying is the reason for logging a queue items. Could be a robot...
