### ISSUE TITLE
Weblink to P3P Compact Privacy Policy is no longer available

### ISSUE THREAD

**Issue by wintstar** [padams/Open-Web-Analytics#217]
In the Administrations Panel => General Configuration Options

> Click here for more information on compact privacy policies and choosing the right one for your web site.

here = http://www.p3pwriter.com/LRN_111.asp

This website is no longer available.

I found them = https://www.w3.org/P3P/

Would it be useful to add this as a txt file as a license, available via web link? 
NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM:
NOI Web Site does not collected identified data.

ADM Information may be used for the technical support of the Web site and its computer system. Users cannot opt-in or opt-out of this usage

DEV Information may be used to enhance, evaluate, or otherwise review the site, service, product, or market. Users cannot opt-in or opt-out of this usage

PSAi Information may be used to create or build a record of a particular individual or computer that is tied to a pseudonymous identifier, without tying identified data (such as name, address, phone number, or email address) to the record. This profile will be used to determine the habits, interests, or other characteristics of individuals for purpose of research, analysis and reporting, but it will not be used to attempt to identify specific individuals. Opt-in means prior consent must be provided by users.

COM Information about the computer system that the individual is using to access the network -- such as the IP number, domain name, browser type or operating system.

NAV Data passively generated by browsing the Web site -- such as which pages are visited, and how long users stay on each page.

OUR Ourselves and/or entities acting as our agents or entities for whom we are acting as an agent.

OTRo Legal entities following different practices. Users may opt-out of the data being used for this purpose.

STP Information is retained to meet the stated purpose. This requires information to be discarded at the earliest time possible. Sites MUST have a retention policy that establishes a destruction time table. The retention policy MUST be included in or linked from the site's human-readable privacy policy.

IND Information is retained for an indeterminate period of time. The absence of a retention policy would be reflected under this option. Where the recipient is a public fora, this is the appropriate retention policy.

DEM Data about an individual's characteristics -- such as gender, age, and income

**Comment by padams** [comment]
I'd rather not maintain a local file with the definitions as these may change. URL has been updated. thanks.
