### ISSUE TITLE
No confirmation alert on Delete 

### ISSUE THREAD

**Issue by guyellish** [padams/Open-Web-Analytics#219]
I am using OWA on my own server, tracking all my sites, and very satisified.
Yet, when installing in a hurry, two sites to track, I clicked Delete for one site and it just went away. A confirmation dialogue would have saved some work.

**Comment by bokmcdok** [comment]
I just lost all my analytics data by accidentally clicking delete. To me this is a critical issue - you should always have confirmation dialogues on actions that can destroy work.

**Comment by padams** [comment]
Yes but....That doesn't delete any analytics data. Just add the site again and the data will show.

**Comment by bokmcdok** [comment]
Ah okay, thanks. Not so serious then :)

I've yet to get around to adding it again :/
