### ISSUE TITLE
Page Type And host name

### ISSUE THREAD

**Issue by girisayan** [padams/Open-Web-Analytics#220]
Hi Padams,

We are implementing the OWA in our project. we need to send the page type and host name to the owa database. kindly let me know the  ASYNC java script command .

Regards,
Girisayan.

**Comment by girisayan** [comment]
I am setting the pagetype using below syntax.                      owa_cmds_push(['setPageType','pagetypename']);    I can able to find the pagetype value in the console .But unable to find the value in owa. Please help the same. Thanks in advance.

**Comment by padams** [comment]
Assuming the value is being stored in the database you can add it as a secondary dimension in any report using the dimension picker drop down.
