### ISSUE TITLE
Visitor Announcements

### ISSUE THREAD

**Issue by skyriv** [padams/Open-Web-Analytics#221]
Howdy, I just installed OWA and everything is working correctly except for the Visitor Announcements. I have the email address correct, but OWA isn't sending any email notifications. Is there something special I should be doing to get this to work?

Thanks
Den

**Comment by skyriv** [comment]
I received a error log email from OWA's Error Logger today, I thought it might help you to weed out the problem:

Jan 11 08:54:15 164688 [] No value passed. // #0 /home/----/public_html/stat/owa_entity.php(340): owa_entity->getByColumn('id', NULL)
#1 /home/----/public_html/stat/modules/base/handlers/locationHandlers.php(80): owa_entity->getByPk('id', NULL)
#2 [internal function]: owa_locationHandlers->notify(Object(owa_event))
#3 /home/----/public_html/stat/modules/base/classes/eventDispatch.php(166): call_user_func_array(Array, Array)
#4 /home/----/public_html/stat/modules/base/classes/eventDispatch.php(298): owa_eventDispatch->notify(Object(owa_event))
#5 /home/----/public_html/stat/modules/base/handlers/domstreamHandlers.php(67): owa_eventDispatch->asyncNotify(Object(owa_event))
#6 [internal function]: owa_domstreamHandlers->notify(Object(owa_event))
#7 /home/----/public_html/stat/modules/base/classes/eventDispatch.php(166): call_user_func_array(Array, Array)
#8 /home----/public_html/stat/modules/base/processEvent.php(109): owa_eventDispatch->notify(Object(owa_event))
#9 /home/----/public_html/stat/modules/base/processEvent.php(98): owa_processEventController->addToEventQueue()
#10 /home/----/public_html/stat/owa_controller.php(233): owa_processEventController->post()
#11 /home/----/public_html/stat/owa_controller.php(218): owa_controller->finishActionCall(NULL)
#12 /home/----/public_html/stat/owa_coreAPI.php(788): owa_controller->doAction()
#13 /home/----/public_html/stat/owa_coreAPI.php(1211): owa_coreAPI::performAction('base.processEve...', Array)
#14 /home/----/public_html/stat/owa_coreAPI.php(897): owa_coreAPI::handleRequest(Array, 'base.processEve...')
#15 /home/----/public_html/stat/modules/base/classes/client.php(348): owa_coreAPI::logEvent('dom.stream', Object(owa_event))
#16 /home/----/public_html/stat/log.php(88): owa_client->logEventFromUrl()
#17 {main}

Thanks
Den

**Comment by padams** [comment]
Should be fixed in master now.
