### ISSUE TITLE
Title not sending for first time alone

### ISSUE THREAD

**Issue by Mohanvenkatesan** [padams/Open-Web-Analytics#222]
Hi,

We have integrated our website with OWA and sending the events through Java script. When we load the page for first time, it is not sending the title. But from second time, it is sending. The page has <title> tag. Pls help me to solve this issue…

First time:

http://10.74.58.15/OWA/log.php?owa_timestamp=1484660520&owa_event_type=base.page_request&owa_user_name=Smith588618%2CJoe588618+M&owa_cv1=isInIframe%3Dtrue&owa_cv3=EID%3D0&owa_cv4=uuiFlag%3Dfalse&owa_page_type=vbuildPage&owa_visitor_id=1484647492890319085&owa_fsts=1484647492&owa_dsfs=0&owa_last_req=1484660489&owa_session_id=1484647494680369763&owa_nps=1&owa_dsps=0&owa_medium=direct&owa_source=%28none%29&owa_search_terms=%28none%29&owa_session_referer=%28none%29&owa_page_url=http%3A%2F%2Ftusfl000vm11569.vdsi.ent.verizon.com%3A7001%2Fresources%2Fspring%2FenggRequest%2FfrcItemSearch.do%3FIndex%3D%26amp%3BitemNumber%3DBE1C%26amp%3BstateWide%3DN%26amp%3Btype%3D%26amp%3Bkow%3D+%26amp%3BajaxAction%3DfrcAcct%26amp%3BvsapProjNum%3D0689691%26amp%3BwpId%3D797919%26amp%3BsiteCode%3D307869%26amp%3BewoNum%3D1A1Y8NR&owa_HTTP_REFERER=&**owa_page_title=&**owa_site_id=872e1586c0876558a077168a6eb64f0d&

Second Time:

http://10.74.58.15/OWA/log.php?owa_timestamp=1484660520&owa_event_type=base.page_request&owa_user_name=Smith588618%2CJoe588618+M&owa_cv1=isInIframe%3Dtrue&owa_cv3=EID%3D0&owa_cv4=uuiFlag%3Dfalse&owa_page_type=vbuildPage&owa_visitor_id=1484647492890319085&owa_fsts=1484647492&owa_dsfs=0&owa_last_req=1484660489&owa_session_id=1484647494680369763&owa_nps=1&owa_dsps=0&owa_medium=direct&owa_source=%28none%29&owa_search_terms=%28none%29&owa_session_referer=%28none%29&owa_page_url=http%3A%2F%2Ftusfl000vm11569.vdsi.ent.verizon.com%3A7001%2Fresources%2Fspring%2FenggRequest%2FfrcItemSearch.do%3FIndex%3D%26amp%3BitemNumber%3DBE1C%26amp%3BstateWide%3DN%26amp%3Btype%3D%26amp%3Bkow%3D+%26amp%3BajaxAction%3DfrcAcct%26amp%3BvsapProjNum%3D0689691%26amp%3BwpId%3D797919%26amp%3BsiteCode%3D307869%26amp%3BewoNum%3D1A1Y8NR&owa_HTTP_REFERER=&**owa_page_title=FRC Search**&owa_site_id=872e1586c0876558a077168a6eb64f0d&

**Comment by padams** [comment]
Impossible to debug without seeing the tracker code you are using.
