### ISSUE TITLE
Any other db plugins, such as mysqli, pdo?

### ISSUE THREAD

**Issue by dac2020** [padams/Open-Web-Analytics#224]
I'm wanting to install this on centos7 using phpw70w. 
The most current version still seems to only use the deprecated mysql or I am missing something.
I've been search the Internet for hours and cannot find a solution for using mysqli for example.

I do have php70w-mysql installed but this is still not working. I am missing something simple I'm sure.
Maybe an extension in php.ini or something?

**Comment by padams** [comment]
Master uses mysqli.

**Comment by dac2020** [comment]
Oh good, I'm not going crazy :). 

Thanks kindly.

**Comment by dac2020** [comment]
Again, I must be missing something simple. I downloaded the trunk version using svn. 
I configured the owa-config.php with mysqli but still get the same error.

[Sun Jan 22 13:10:05.215141 2017] [:error] [pid 1515] [client x.x.x.x:57299] PHP Warning:  require_once(/var/www/vhosts/owa/html/plugins/db/owa_db_mysqli.php): failed to open stream: No such file or directory in /var/www/vhosts/owa/html/owa_coreAPI.php on line 66
[Sun Jan 22 13:10:05.215199 2017] [:error] [pid 1515] [client x.x.x.x:57299] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/owa/html/plugins/db/owa_db_mysqli.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/vhosts/owa/html/owa_coreAPI.php on line 66

Am I supposed to use mysqli or mysql or something else?

**Comment by dac2020** [comment]
If I use mysql, then I get the following.

[Sun Jan 22 13:12:32.188283 2017] [:error] [pid 1644] [client x.x.x.x:57527] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/vhosts/owa/html/plugins/db/owa_db_mysql.php:107\nStack trace:\n#0 /var/www/vhosts/owa/html/plugins/db/owa_db_mysql.php(256): owa_db_mysql->connect()\n#1 /var/www/vhosts/owa/html/owa_db.php(600): owa_db_mysql->prepare('1')\n#2 /var/www/vhosts/owa/html/owa_db.php(548): owa_db->_makeConstraintClause('WHERE', Array)\n#3 /var/www/vhosts/owa/html/owa_db.php(463): owa_db->_makeWhereClause()\n#4 /var/www/vhosts/owa/html/owa_db.php(475): owa_db->generateSelectQuerySql()\n#5 /var/www/vhosts/owa/html/owa_db.php(354): owa_db->_selectQuery()\n#6 /var/www/vhosts/owa/html/owa_entity.php(375): owa_db->getOneRow()\n#7 /var/www/vhosts/owa/html/owa_entity.php(340): owa_entity->getByColumn('id', '1')\n#8 /var/www/vhosts/owa/html/modules/base/classes/settings.php(271): owa_entity->getByPk('id', '1')\n#9 /var/www/vhosts/owa/html/owa_caller.php(100): owa_settings->load('1')\n#10 /var/www/vhosts/owa/html/modules/base/classes/client.php(52): owa_caller->__construct(Array)\n#11 in /var/www/vhosts/owa/html/plugins/db/owa_db_mysql.php on line 107

**Comment by dac2020** [comment]
Ok, really struggling to find more information here. I downloaded the master (nabbed the trunk last time in error) and set things up but it only shows the mysql option again. I tried that but get an error so I changed it to mysqli but still get an error.

[Sun Jan 22 14:20:15.713441 2017] [:error] [pid 8283] [client x.x.x.x:50215] PHP Warning:  require_once(/var/www/vhosts/owa/html/plugins/db/owa_db_mysqli.php): failed to open stream: No such file or directory in /var/www/vhosts/owa/html/owa_coreAPI.php on line 66
[Sun Jan 22 14:20:15.713484 2017] [:error] [pid 8283] [client x.x.x.x:50215] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/owa/html/plugins/db/owa_db_mysqli.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/vhosts/owa/html/owa_coreAPI.php on line 66

In the plugins, there is no mysqli plugin either. Am I supposed to get that somewhere else?
Am I missing a php module or option?

How can I get past this and install?

**Comment by dac2020** [comment]
Simple fix for anyone else going through this.
use the master and keep 'mysql' as the db type.
