### ISSUE TITLE
master with wordpress - tables creation fails

### ISSUE THREAD

**Issue by dac2020** [padams/Open-Web-Analytics#225]
PHP Notice:  Only variables should be assigned by reference in /var/www/html/wp-content/plugins/owa/modules/base/classes/error.php on line 322
Jan 22 14:06:58 11663 [notice] Applying Update 3 (owa_base_003_update)
Jan 22 14:06:58 11663 [notice] Pre Update Proceadure Suceeded
Jan 22 14:06:58 11663 [notice] Change to Table request failed
Jan 22 14:06:58 11663 [notice] Update Proceadure Failed
Jan 22 14:06:58 11663 [notice] Update Failed
Jan 22 14:06:58 11663 [notice] Updates failed. Check OWA's error log file for more details and try again.

I can see that the tables were not created but am not able to find enough information to continue. 
When I activated the plugin, this filled in the owa-config.php file with the correct db details but it didn't have table creation. I then created a new db user and set it with all of the correct permissions then added this user to the owa-config.php yet still cannot create the tables.

The log file simply shows the failures then says try dropping all the tables... which don't exist yet.
I've tried this with the plugin enabled and disabled.

No errors in apache, only in owa logs.

**Comment by dac2020** [comment]
So, I've now installed a stand alone owa which is working fine. I have a tracking code which I would like to install this on the wordpress site but cannot find any information on how to do this. 

When installing owa as a plugin, it's obvious but when wanting to use owa as a stand alone, where/how does one install the site id/tracking code into wp?

**Comment by padams** [comment]
Not sure if this is the issue but you need to take MySQL out of strict mode. We're the tables created under standalone install?

**Comment by padams** [comment]
The WP plugin should create the site tracker and Id for you.

**Comment by dac2020** [comment]
Yes, the tables do get created when putting together a standalone install. 
This is where I'm at now since I could not get past this problem. I've set up a standalone and a copy of that in the wp plugins. The copy of course contains the standalone db settings. 
The site ID is the same in the plugin and the standalone.

**Comment by padams** [comment]
can you drop the OWA tables and try installing again via the WordPress plugin from master? also what version of PHP and OS are you running under?

**Comment by dac2020** [comment]
Os is Centos7 and php70w.
We are also talking in #226 but slightly different topic.
Sure, I can try that but I've done that in all kinds of different ways using master.

So, the steps I took based on your input above. 

I deleted all of the tables in the standalone db since there is no other.
I deactivated the plugin and removed the owa plugin files.
I copied the working standalone version into the wp plugins.
I kept the standalone db settings in the wp instance.
I activated the plugin and this time it did create the tables.
(Previously, I checked to make sure that the db user had table creation allowed, etc)

I changed the Admin settings as desired as just like a previous test, it didn't seem to save the settings.
I go back to the Administration tab and all my settings seem to be gone. However, then I clicked on Main Configuration and this time the settings are as I set them.

Can't think of anything I overlooked so I'll wait and see if any stats show up now.

**Comment by padams** [comment]
Ah. The first time you installed did you only copy OWA's WP plugin file into WordPress's /wp-content/plugins folder or you copy entire OWA set of files?

**Comment by dac2020** [comment]
I copied the entire structure into wp-content/plugins/owa.
I just got back to this and there are still no stats yet.

Am I the only person having this problem? Quite often, when people try things and they cannot get it to work, most don't even ask for help, they just walk away. I'd like to solve this so it can help anyone else going through this.

**Comment by padams** [comment]
Next obvious question is the plugin inserting the OWA JavaScript tag into the website pages?

If so, use a browser debugger like firebug and see if the script is making any http calls to track the page view. If so, note where those requests are going to what the http response code is.

**Comment by dac2020** [comment]
Meaning putting the tab in the footer? <?php wp_footer(); ?>, yes, this is done.

In ie, it always asks if I want to show unsafe content. 
In ff, it shows oddly as well using https which the site is.

One thing I had forgotten to do was to change the OWA_PUBLIC_URL on the wp instance but doing that only made it display even worse now. Is https a problem?

I have opcache installed on that site and hoping this is not some conflict.
I've installed firebug but I'm not exactly sure what I'm looking for.

![2017-01-24_141208](https://cloud.githubusercontent.com/assets/9727841/22266973/44a32aa2-e23f-11e6-9587-e0749a9cfd4d.png)

**Comment by dac2020** [comment]
Hmm, using https in the config file consistently breaks the view.

**Comment by padams** [comment]
Firebug has a Net tab where you can watch every http call made by the web browser. One of them should be to OWAs log.php on your server. You want to see what the http status code is for that request and examine the URL to make sure it's going to the right place. If it's not no stats will be logged...

**Comment by dac2020** [comment]
From within the oea dashboard, I click on any of the stats pages and can see 200OK but nothing regarding log.php anywhere that I've found so far.

Ok, I do see the following which gets a 200 OK
https://www.domain.com/wp-admin/index.php?page=owa&owa_do=base.sites (domain.com for privacy)

All of the owa related connections seem to be 200.

**Comment by padams** [comment]
No I mean on the public faces WordPress pages that visitors see.

**Comment by dac2020** [comment]
Got it. 
Well, I tried that also and see only GET www.domain.com and the rest are all 'POST admin-ajax.php. Not one connection shows owa.

**Comment by padams** [comment]
From the home page of your site? That doesn't sound right. 

Send me the URL privately and I'll take a look.

**Comment by dac2020** [comment]
I'm looking but don't see any pm methods on github.

**Comment by dac2020** [comment]
PM functions were removed some time ago. Do you have a public support email or something? I could email you and reference this issue.

**Comment by dac2020** [comment]
Hi, how would you like me to contact you?

**Comment by dac2020** [comment]
I don't want to quit since you're helping me but I need these stats working soon. I'm not sure what to do next here.

**Comment by dac2020** [comment]
Did you decide to give up on this? I figured this might help when/if someone else comes across a similar problem too.

**Comment by padams** [comment]
my email address is all over the code. if you want to email me privately I’ll try to help you.

**Comment by dac2020** [comment]
I saw that but wasn't sure if you would appreciate emails there. 
Done, just sent.
