### ISSUE TITLE
Feed Tracking

### ISSUE THREAD

**Issue by maitrenageur** [padams/Open-Web-Analytics#228]
Sorry I'm new to OWA.
To track feed is available, but what is to maintain to track different feeds?
Feeds will be created via PHP in different folders like /feed/atom/ or /feed/podcast/ .

**Comment by padams** [comment]
You'd have to roll your own instrumentation of this in PHP using the PHP tracker. OWA does profile a feed table to store requests in. See the WordPRess login for more details on what it's doing there.
