### ISSUE TITLE
Geo Location is not working

### ISSUE THREAD

**Issue by maitrenageur** [padams/Open-Web-Analytics#230]
The Geo Location is not working, no countries are in the list.
What is to do?

**Comment by Toretu** [comment]
Also can not see any geolocation

**Comment by jcfromkc** [comment]
Did you ever find a solution for this?

**Comment by j2l** [comment]
same
+1

**Comment by padams** [comment]
Did you follow the instructions for activating the maxMInd geo module? See the page on the wiki.

**Comment by j2l** [comment]
Oh, didn't know that.
Thanks Padam!

For future visitors:
https://github.com/padams/Open-Web-Analytics/wiki/Maxmind-GeoIP-Module
