### ISSUE TITLE
Tracking search engine search terms

### ISSUE THREAD

**Issue by dac2020** [padams/Open-Web-Analytics#236]
I've been searching for hours and cannot find much information on how to go about configuring OWA to start tracking google search terms for example, among others. First, I'd like to start tracking google searches, however, I've stopped paying for ads from them so does it mean I cannot use this function in OWA then?

I see mentions of tracking but nothing which clearly explains how I can go about this.

https://github.com/padams/Open-Web-Analytics/wiki/Tracker

Can someone help please.

**Comment by padams** [comment]
The OWA JavaScript tracker will automatically record search terms however Google sadly does not pass search terms anymore when the search is done under HTTPS (which is the majority) these days.....

**Comment by dac2020** [comment]
Oh no! They realize they can be circumvented I suppose. 
Any other ways of learning what the search terms are with Google and/or any other search engines that do work?

**Comment by Lonak** [comment]
Try logging into your Google [Search Console](https://www.google.com/webmasters/tools/) to access search terms. It's not handy, but it's the direction Google has taken.

**Comment by dac2020** [comment]
Yes, it's how I do it now. Would have been great to see it in the reports.

Thanks for the tip.
