### ISSUE TITLE
Organic traffic marked as Referral traffic

### ISSUE THREAD

**Issue by natzar** [padams/Open-Web-Analytics#237]
I'm getting google, yahoo and other search engine traffic as Referral traffic, not as organic.

I checked /modules/base/classes/client.php where there is the function isRefererSearchEngine. As there are no more search terms, I modified line 810 
from => //if ( strpos($host, $domain) && $term ) { 
to => if ( strpos($host, $domain)) {

Also I tried to update database manually, setting medium='organic-search' in all owa_requests and owa_sessions rows, that had referer_id = owa.referer(site like '%google%'), but I keep getting same results for traffic sources trough the API.

Any clue on how to fix it?

**Comment by padams** [comment]
client.php is the php tracker. owa.tracker.js is the javascript tracker. Methods are almost identical. I've changed both in master now. thanks.

Also worth noting is that if you make a change to the javascript tracker you then need repackage it using:

`php cli.php cmd="build" package="owa.tracker"`

**Comment by natzar** [comment]
Just with that small change, search engines will be recognized as organic-search now and then?

Can I ask you, why if I update all medium fields in database, the traffic sources values are still the same?
I can't find where you send the Json reply with that values, not even from which table are the values read from.  #padamsIsDoingAmazingWorkWithOWA

**Comment by padams** [comment]
That fix will change it for new events.

For old events you need to update the medium column in all the tables where it exists namely owa_request and owa_session.

**Comment by natzar** [comment]
I updated everything, but no change. I hope it's some cache. Thank you very much.

**Comment by padams** [comment]
Clear your cache using the cli.

**Comment by natzar** [comment]
After the change, it passed some days, but it seems OWA is still classifying search engines as referrals. I just set a cron that keeps updating _request and _session tables everyday to make it work. Just FYI.
