### ISSUE TITLE
Dom Click always defined as Not Set

### ISSUE THREAD

**Issue by kcobb** [padams/Open-Web-Analytics#238]
OWA does not appear to functioning correctly. If an element ID, Name or Class is defined. OWA always reports as Not Set. Has anyone else ran into this issue? I cannot get OWA to record elements correctly.

owa_dom_element_name=%28not+set%29&
owa_dom_element_value=%28not+set%29&
owa_dom_element_id=%28not+set%29&
owa_dom_element_class=%28not+set%29&

**Comment by padams** [comment]
looks like some bad defensive coding. fixed now in master.
