### ISSUE TITLE
I am getting this warning during the installation phase. What is the problem?

### ISSUE THREAD

**Issue by terziasil** [padams/Open-Web-Analytics#239]
I am getting this warning during the installation phase. What is the problem?

Warning: mail() has been disabled for security reasons in /home/u7007570/public_html/asil/includes/Log-1.12.7/Log/mail.php on line 206

**Comment by padams** [comment]
That’s not an OWA error. Check your php or hosting environment.

**Comment by terziasil** [comment]
Thank you padams
