### ISSUE TITLE
How to set page Title/Type ?

### ISSUE THREAD

**Issue by dnrsto** [padams/Open-Web-Analytics#241]
Hello,
How can i set-up the page Title and the page Type ?
All the entries are "(not set)".

Thank you.
Best Regards.

**Comment by jcfromkc** [comment]
Did you find a solutions for this?

**Comment by AKRFranko** [comment]
When you load the tracker in your page, you should wait for then have access to OWATracker instance in javascript. Then you can do

`if(window.OWATracker){
          window.OWATracker.setPageType('your-page-type');
          window.OWATracker.setPageTitle( 'your-page-title; );
          window.OWATracker.trackPageView(); // count this as a page view since title/type have changed.
 }`

**Comment by abdulbasetbasher** [comment]
if you are using Async Tracker

you should add 

`owa_cmds.push(['setPageTitle', document.title]);`
before 
`owa_cmds.push(['trackPageView']); 
`
