### ISSUE TITLE
Tracking phpbb forums

### ISSUE THREAD

**Issue by dac2020** [padams/Open-Web-Analytics#243]
Since I've been searching on how to accomplish this for quite a while without finding enough information, I thought I would create an issue which might help others.

I want to use OWA to track a phpbb (3.2) forum for statistics.
I posted in the phpbb forums but no one seems to know. 
There was mention however of installing the tracking code in the templates overall_footer.php so I put this at the bottom of that page.

require_once('/var/www/virtualhosts/owa/html/owa_php.php');

        $owa = new owa_php();
        // Set the site id you want to track
        $owa->setSiteId('xxxx');
        // Uncomment the next line to set your page title
        //$owa->setPageTitle('somepagetitle');
        // Set other page properties
        //$owa->setProperty('foo', 'bar');
        $owa->trackPageView();
</body>

Looking online, I simply cannot seem to find anything showing what I need to enter into the commented areas however. 

        //$owa->setPageTitle('somepagetitle');
        // Set other page properties
        //$owa->setProperty('foo', 'bar');
        $owa->trackPageView();

What do those areas require in order to start gathering stats? So far, nothing is showing.
The links for help where the tracking code is shown don't work, nothing there, 'not found'.

**Comment by dac2020** [comment]
Guess I'm not the only one who cannot figure this out.

**Comment by dac2020** [comment]
I imagine there are thousands of phpbb forum users. Can this not be done?

**Comment by padams** [comment]
OWA can be added to any website. just add the javascript tracker to one of bbpress’s page templates.
If you want to track more bbpress specific events and meta-data you’ll need to write a bbpress plugin for that.

**Comment by dac2020** [comment]
Yes but I'm using phpbb and show exactly how I've added it to the site in the above comments. 
I also asked what needs to be entered in some of the fields above since I cannot find anything relating to these anywhere.

**Comment by padams** [comment]
that are optional methods you can uncomment to add meta data (such as page title) to the tracking event. You would have to figure out how to get that info from bbPress and then pass it as a variable to that method.

**Comment by dac2020** [comment]
So, even commented, this should be working then? I simply cannot find enough information to make this work. Not sure why.

**Comment by padams** [comment]
No. Commented code does not run. Uncomment the code and populate the argument with the contents of a variable.

**Comment by dac2020** [comment]
I misunderstood. I'll look at this and see if I can figure it out then.
