### ISSUE TITLE
undefinedbase errors

### ISSUE THREAD

**Issue by wedsall** [padams/Open-Web-Analytics#246]
Hello,

 I'm observing strange owa problems such as the reporting range not showing up. While debugging I noticed these errors:
GET http://server/owa/undefinedbase/js/includes/jquery/jQote2/jquery.jqote2.min.js 
GET http://server/owa/undefinedbase/templates/filter_period.tpl 404 (Not Found)
GET http://server/modules/base/i/loader.gif 404 (Not Found)

My public URL is defined as: define('OWA_PUBLIC_URL', 'http://server/owa/');

It seems as if the installation is unsure where its base directory is. In the last example it isn't even looking within the OWA_PUBLIC_URL. Please advise. :) 

William

**Comment by padams** [comment]
Strange. Never seen that before. Is the public URL being set on the OWA object in the DOM?
