### ISSUE TITLE
location_id is not being set with session

### ISSUE THREAD

**Issue by zecman** [padams/Open-Web-Analytics#248]
Hi,
I am using OWA 1.6.0 and have some questions:
1. 
Whenever a visitor connects the GeoIP works (a new location is being saved) but the session does not have the location_id filled out. There is always a 0 in the table's row of the session.
2.
When is the user_name being set in the different tables? I have a user area and know some of my users. I also use OWA to track actions of my apps. Is it possible to take the user_name from the visitor table and put it into the sessions?
3.
In the screenshots of the OWA website I see the locations in an Google map overlay. How can I see this?

Thank you for this great piece of software!

Regards,
Christian

**Comment by padams** [comment]
1 and 2 sound like bugs. Both should be set on page views and sessions there are columns in the tables for both.

3 was removed a long time ago so that screenshot needs to be removed from the site or someone needs to write an module that implements it.

**Comment by zecman** [comment]
Hi
Thanks for the reply. Do you have a hint for me... In which php file to look / make the changes?
Does it make sense to fix the 1.6.0 code or is the master about to be releases the next days? ;-)

Cheers,
Christian

**Comment by padams** [comment]
just submit a pull request on the code in master.

**Comment by zecman** [comment]
I think first I should update to the recent master branch and try to get things running with the recent files, shouldn't I?

Regarding location_id: I am working with actions, maybe that is the problem.

**Comment by padams** [comment]
Yes please update first.

**Comment by padams** [comment]
I see the location_id on sessions. so i don't think this is a generalized issue. re-open if you still have the issue
