### ISSUE TITLE
Does OWA work with Mod Security Enabled?

### ISSUE THREAD

**Issue by hawk0077** [padams/Open-Web-Analytics#249]
Im currently using/setting up piwik but it doesnt play with mod security and disabling mod security isnt an option for me. 

I have piwik (and will maybe have OWA) on a separate server and domain to my sites

Any advice appreciated, thanks

**Comment by padams** [comment]
How do you know that it’s mod_security that is causing your issue?

OWA has a few legacy PHP things that _might_ be tripping it up. 

The first is that it includes local files with the .tpl extension. 

Also, I’ve seen some cases where security rules block anything called log.* which is the main tracking entry point.

**Comment by hawk0077** [comment]
Hi, thanks for the response.
I havent installed OWA as yet but will most likely try it soon (a day or so) as I dont like to rely on google for everything.

I know that mod security is tripping piwik up because in the apache error.log theres an instance of url=/piwik.php and an ID of 981127 (example) and a reference to sql injection rule.

Im no developer but I thought that it was the POST function at cause which I thought from the piwik site.

When I disable the piwik plugin in either wordpress or joomla the error goes away in the log. But  on a coupleof sites google analytics doesnt cause any issues and so I thought OWA would work without issues as well as from anone developer point of view they look similar... or did until google went crazy with their new scripting and user interface designs. 

If I can find a way to integrate joomla and wp via plugins or other simeple method I will install OWA soon as mentioned.

**Comment by hawk0077** [comment]
piwik also say that it isnt compatable with mod security.

https://piwik.org/faq/troubleshooting/faq_100/

Thanks again for the response, anything to add would be appreciated as I get through the next couple of days work and gathering info on OWA. Cheers
