### ISSUE TITLE
non-numeric value encountered / Undefined index - can't set up OWA

### ISSUE THREAD

**Issue by cubetronic** [padams/Open-Web-Analytics#251]
New to OWA, not sure what's going wrong here... Maybe a permissions problem? But my Apache user "www-data" has full permissions in the website directories.

going to localhost/owa/install.php sends me to:
`http://localhost/owa/install.php?owa_action=base.installCheckEnv`

which gives the following:
```
Warning: A non-numeric value encountered in /home/a/Downloads/site/owa/includes/Log-1.12.7/Log.php on line 635

Warning: A non-numeric value encountered in /home/a/Downloads/site/owa/includes/Log-1.12.7/Log.php on line 635

Warning: A non-numeric value encountered in /home/a/Downloads/site/owa/includes/Log-1.12.7/Log.php on line 635

Warning: A non-numeric value encountered in /home/a/Downloads/site/owa/includes/Log-1.12.7/Log.php on line 635

Notice: Undefined index: in /home/a/Downloads/site/owa/includes/Log-1.12.7/Log.php on line 589

Warning: A non-numeric value encountered in /home/a/Downloads/site/owa/includes/Log-1.12.7/Log.php on line 635

Warning: A non-numeric value encountered in /home/a/Downloads/site/owa/includes/Log-1.12.7/Log.php on line 635

Notice: Undefined index: in /home/a/Downloads/site/owa/includes/Log-1.12.7/Log.php on line 589
```

So, according to the note on the install.php, I edited owa-config-dist.php with the proper info and renamed it owa-config.php, but then it asked me for a username and password. When+Where was I supposed to set that up?! Or an email address?! and now going back to install.php, I just get those errors again.

I looked at lines 635 and 589, and it seems to have something to do with UMASK, so.. I went ahead and did a recursive chmod 755 to the owa folder, just to see if that would help, but no luck...

**Comment by Kamaladhasan** [comment]
HI I'm new to OWA, I'm using php7.1 version... When I try to install OWA the first step install.php I gave db name db user and password and then try to continue.. But it shows the following error..

Warning: A non-numeric value encountered in D:\xampp\htdocs\owa\includes\Log-1.12.7\Log.php on line 635

Warning: A non-numeric value encountered in D:\xampp\htdocs\owa\includes\Log-1.12.7\Log.php on line 635

Warning: A non-numeric value encountered in D:\xampp\htdocs\owa\includes\Log-1.12.7\Log.php on line 635

Warning: A non-numeric value encountered in D:\xampp\htdocs\owa\includes\Log-1.12.7\Log.php on line 635

Notice: Undefined index: in D:\xampp\htdocs\owa\includes\Log-1.12.7\Log.php on line 589

Warning: mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set() in D:\xampp\htdocs\owa\includes\Log-1.12.7\Log\mail.php on line 206

**Comment by aozimkov** [comment]
I have the same issue( 
My site pwered by php 7.1 and after owa plugin has been activated in wordpress panel I have an error
`Warning: A non-numeric value encountered in www/wp-content/plugins/owa/includes/Log-1.12.7/Log.php on line 635`

**Comment by aozimkov** [comment]
I am not a master in php but I try to look on a code
I looked for line 635 it is return in MASK function: 
```
    public static function MASK($priority)
    {
        return (1 << $priority);
    }

``` 
with var_dump($priority) before return looks like this: 

```
int(7) int(6) int(0) int(2) int(1) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(5) int(5) int(5) int(5) int(5) int(3) int(3) int(3) int(3) int(3) int(5) int(5) int(5) int(5) int(5) string(0) ""
Warning: A non-numeric value encountered in /var/www/u0176813/data/www/rccoffeeperm.ru/wp-content/plugins/owa/includes/Log-1.12.7/Log.php on line 638
string(0) ""
Warning: A non-numeric value encountered in /var/www/u0176813/data/www/rccoffeeperm.ru/wp-content/plugins/owa/includes/Log-1.12.7/Log.php on line 638
string(0) ""
Warning: A non-numeric value encountered in /var/www/u0176813/data/www/rccoffeeperm.ru/wp-content/plugins/owa/includes/Log-1.12.7/Log.php on line 638
string(0) ""
Warning: A non-numeric value encountered in /var/www/u0176813/data/www/rccoffeeperm.ru/wp-content/plugins/owa/includes/Log-1.12.7/Log.php on line 638
string(0) ""
Warning: A non-numeric value encountered in /var/www/u0176813/data/www/rccoffeeperm.ru/wp-content/plugins/owa/includes/Log-1.12.7/Log.php on line 638
string(0) ""
Warning: A non-numeric value encountered in /var/www/u0176813/data/www/rccoffeeperm.ru/wp-content/plugins/owa/includes/Log-1.12.7/Log.php on line 638
int(7) int(7) int(7) int(7) int(7) int(7) int(7) int(7) 
```

But 
```
    /**
     * Calculate the log mask for the given priority.
     * This method may be called statically.
     * @param integer   $priority   The priority whose mask will be calculated.
     * @return integer  The calculated log mask.
     * @access  public
     * @since   Log 1.7.0
     */
```
Why I looked for a string in var_dump? may be issue some where here? )
Have you any idea? :)

**Comment by aozimkov** [comment]
The issue observed just on php7

**Comment by padams** [comment]
Are you running g the latest code in master?

**Comment by aozimkov** [comment]
I trying running owa as Wordpress plugin

But when I changed PHP version to 5.6 the problem was solved for me. I think that issue with php 7

**Comment by padams** [comment]
This is fixed in master.
