### ISSUE TITLE
No tracking from websites with HTTPS DOMAIN

### ISSUE THREAD

**Issue by ramsesIII** [padams/Open-Web-Analytics#253]
No tracking from websites with https
Does not track webpages from https.
All the websites I converted from HTTP to HTTPS have stopped tracking.
The tracking code has not been touched or changed.
They just stopped working.
I did a test:
Reported website from HTTPS to HTTP and for magic to work
I have reported this website with HTTPS and stopped working

Does anyone have a solution?
Possible Bug?
My mistake?
Please help me
Thank you all

**Comment by padams** [comment]
Did you change the public URL in the config and regenerate the tracking tag?

**Comment by ramsesIII** [comment]
Absolutely not.

Example ... if domain first was:
http://www.foo.com
now is:
https://www.foo.com

I did two tests

1 Test) HTTP to HTTPS without touching tracking code

2 Test) Created new profile on OWA directly with HTTPS choice

Both do not work the tracking
I tried with version 1.6.0 and 1.5.7

**Comment by padams** [comment]
Does the JavaScript tracker even make the GET request to the server?

If so turn on debug logging and see how far OWA gets in processing it. There should be an error in that log.

--
Peter Adams

**Comment by ramsesIII** [comment]
Maybe I understand the problem.
I did a new install of OWA 1.6 on HTTPS address is for magic works address with HTTPS tracking work

The problem (but I will confirm in the coming days) is:
Tracking from a site with HTTPS can not occur on a OWA site with HTTP, otherwise break SSL certified security chain

So for security to install OWA with HTTPS address is sure to capture tracking from HTTP and HTTPS addresses

Making other tests is coming up days ahead.

**Comment by ramsesIII** [comment]
Finally a verdict;)
The problem is easy, if you want to trace Websites with HTTPS, OWA must have an HTTPS address otherwise it's "broken the security chain" of the web site to trace.

I confirm that OWA under HTTPS address can trace HTTP and HTTPS websites without any problems.

If you have a website in HTTP and after you convert it to HTTPS you have to create a new profile.
Unfortunately, OWA does not allow you to edit the web site profile from administration
(At least do not do it from the database.)

Great OWA, really well done ... outstanding API calls extremely versatile.

**Comment by angerangel** [comment]
Just an helpful note: as you described if you install OWA on a http server, you can't track https servers; but if you adopt a SSL certificate on your OWA sever, you have to change the configuration file owa-config.php file this way, go to the 61 line:
from 
`define('OWA_PUBLIC_URL', 'http://www.mywebsite.com/Open-Web-Analytics/');  `
to
`define('OWA_PUBLIC_URL', 'https://www.mywebsite.com/Open-Web-Analytics/');   `

then logout and login again.
