### ISSUE TITLE
Class 'owa_db_' not found

### ISSUE THREAD

**Issue by korang** [padams/Open-Web-Analytics#255]
Trying to install owa as plugin to my wordpress site.  Getting the error 
Fatal error: Class 'owa_db_' not found in /var/www/html/newconceptmassageandspa.com/wp-content/plugins/owa/owa_coreAPI.php on line 102

NOTE: my wordpress database is not called wordpress but a unique name for the site.

**Comment by padams** [comment]
The OWA-config file is not being created so it’s unable to determine what DB type to use. Very likely a permissions issue.
