### ISSUE TITLE
Getting some simple data using PHP

### ISSUE THREAD

**Issue by ozcamman** [padams/Open-Web-Analytics#257]
I have successfully installed OWA and now would like to load some simple stats into a website..
Data like number of visits  this week/month/etc
Am a newbie here so am floundering for ideas..
Any help?
Thanks

**Comment by HussainMD** [comment]
OWA does it all for you. 

Go to Administration Menu (on the top) -> Tracked Sites (on the left panel) -> Add New and specify DOMAIN NAME and SITE NAME - save it. And you are ready to go.

![owa_add_new](https://user-images.githubusercontent.com/33723460/32957539-dead7e8c-cbb3-11e7-884a-c14c7cf955dd.JPG)
