### ISSUE TITLE
Overrun with Crawlers and Bot Spam

### ISSUE THREAD

**Issue by jcfromkc** [padams/Open-Web-Analytics#263]
I implemented the OWA tracking code on a site this morning. Within the 6 past hours its clocked about 500 "Unique Visitors". Each page visit is less then a second so I know these are all crawlers. Are there any plugins or third party utilities that work with OWA to help prevent crawler and bot spam from destroying the analytics data? I wasn't seeing any of this using Click Stats. 

Amazing program by the way! 

Thx, JC

**Comment by JingleSPOT** [comment]
Aloha

Did you solve this? I'm looking for answers too.

**Comment by jcfromkc** [comment]
Nope. I stopped using this and went back to Clicky Stats.
________________________________
