### ISSUE TITLE
not tracking

### ISSUE THREAD

**Issue by yoel123** [padams/Open-Web-Analytics#266]
at all.

but it dose adds the info to the sql tables i can see the data rows of clicks and downstream.

but it shows 0.00 on everything in the owa control panel please help

**Comment by HussainMD** [comment]
I've same issue. I can see stats on the db but on the screen it's not showing any charts...
![owa_mainscreen1](https://user-images.githubusercontent.com/33723460/32957182-dcf93bd6-cbb2-11e7-9294-44ed17f12a0c.JPG)

**Comment by padams** [comment]
Assuming this is resolved in master. Reopen with specific debug from OWA error log files if need be.
