### ISSUE TITLE
Cryptographic, Password Disclosure and XSS vulnerabilities

### ISSUE THREAD

**Issue by fgeek** [padams/Open-Web-Analytics#267]
Original advisory is here: http://hyp3rlinx.altervista.org/advisories/AS-OPENWEBANALYTICS0721.txt

Please fix these vulnerabilities and create a new release with the fixes, thank you. I haven't personally reproduced the issues, but I can do so if needed. There doesn't seem to be CVEs assigned for this advisory. I can request the CVEs from MITRE today.

**Comment by fgeek** [comment]
Btw. your web site still has http://trac.openwebanalytics.com link. You might want to change it to point directly to GitHub issue tracker, thanks.

**Comment by padams** [comment]
I believe some of this is fixed in master. If you are in a position to test the advisory that would be helpful.

**Comment by fgeek** [comment]
Happy to help. I'll send a new message after I have tested this with the newest version.

**Comment by padams** [comment]
These should all be fixed by now. Re-open if not.

**Comment by attritionorg** [comment]
@padams Could you link to the fixing commits and/or mention the first fixing version? Thanks!

**Comment by padams** [comment]
I just looked these again and they are all fixed as far as I can tell. I think most have been fixed since 1.5.9.

**Comment by attritionorg** [comment]
Thank you!
