### ISSUE TITLE
Reset Database for Site

### ISSUE THREAD

**Issue by sutibo42** [padams/Open-Web-Analytics#27]
Hello.  I'm working on setting up OWA for a few different websites.  I would like to "clear" all analytics for a particular site as I go through the development process.  I've tried to delete the site via the UI, but when I bring it back the old analytics are still there.

Can anyone guide me through all of the tables that need to be purged and in what order in the SQL database to accomplish this?  Or is there a UI feature I have missed?

Thanks
Brina

**Comment by padams** [comment]
If you want to clear all data from all sites you can just drop the OWA tables and re-install. Purging data for one site is kinda difficult but basically you want to do a SQL delete on any row with the site_id that equals the site you want to purge.
