### ISSUE TITLE
Geo Location not working

### ISSUE THREAD

**Issue by NollyB** [padams/Open-Web-Analytics#271]
Just installed OWA and it is working in that I can see visits to pages where I have installed the 'code'.
I cannot see any Geo Location data; probably because I do not understand how to set that up.
Help would be appreciated.
Norman

**Comment by abousselmi** [comment]
Have you tried (from the owa portal) to activate the Maxmind GeoIP module ?
You can find it under settings -> Modules
Cheers

**Comment by NollyB** [comment]
I have seen a User's Domain and IP address but I am unable to see the User'd Country or City.
Cheers

**Comment by padams** [comment]
See the wiki for how to setup geolocation.
