### ISSUE TITLE
Can't complete install -- Array to string conversion

### ISSUE THREAD

**Issue by olegsemgem** [padams/Open-Web-Analytics#272]
I'm trying to complete the steps on install.php. At the end of the wizard, when I push the button to setup my tracker, I'm taken back to install.php and have to start from the beginning.

The error log contains errors like the following:

```
10:27:23 08/21/17 [debug] Query: SELECT * FROM owa_site WHERE domain = 'https://myservice.example.org'    LIMIT 1 
10:27:23 08/21/17 [debug] <errorentry>
	<datetime>2017-08-21 10:27:23 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Array to string conversion</errormsg>
	<scriptname>{my-owa-path}\plugins\db\owa_db_mysql.php</scriptname>
	<scriptlinenum>220</scriptlinenum>
</errorentry>
```

I'm running on IIS with PHP 7.1.7, and AWS RDS MySql.

Any help would be appreciated!

**Comment by abousselmi** [comment]
Which type of encoding you are using in your database?

**Comment by olegsemgem** [comment]
When I issue:

```
SHOW VARIABLES LIKE '%colla%';
SHOW VARIABLES LIKE '%char%';
```

I get:

```
collation_connection    utf8_general_ci
collation_database    latin1_swedish_ci
collation_server    latin1_swedish_ci

character_set_client    utf8
character_set_connection    utf8
character_set_database    latin1
character_set_filesystem    binary
character_set_results    utf8
character_set_server    latin1
character_set_system    utf8
character_sets_dir   ...
```

I've also tried with:

```
collation_connection    utf8_general_ci
collation_database    utf8_general_ci
collation_server    utf8_general_ci

character_set_client    utf8
character_set_connection    utf8
character_set_database    utf8
character_set_filesystem    binary
character_set_results    utf8
character_set_server    utf8
character_set_system    utf8
character_sets_dir   ...
```

The issue persists either way, though!

**Comment by abousselmi** [comment]
I compared to my running mysql instance, it seems that encoding is ok. Which version mysql and php you are running? Mine are: mysql 5.7.19 and php 7.0.22

**Comment by olegsemgem** [comment]
I've switched off RDS for now, and am using a docker mysql container with the following version:

mysql -V
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper

PHP is  7.17

Still having the same problem, even with the new MySql. I'll try a different version of PHP next.

**Comment by padams** [comment]
Try the new code in master. I've added a query that will disable the strict sql mode that is now on by default in mysql 5.7.

**Comment by padams** [comment]
assuming this fix worked. if not reopen.
