### ISSUE TITLE
How to contact project team?

### ISSUE THREAD

**Issue by kwidoo** [padams/Open-Web-Analytics#275]
I represent new company CREDEROOM, that will be developing it's own IT infrastructure soon. One of the most important parts of it will be webanalytic. 

We would like to discuss with team the ways of co-operation and financial support.

My contacts is op@crederoom.com (or private kwidoo@gmail.com).

Oleg

**Comment by padams** [comment]
You can send me an email: Peter at openwebanalytics dot com
