### ISSUE TITLE
master not working with php v 7.1.8

### ISSUE THREAD

**Issue by raykai** [padams/Open-Web-Analytics#277]
I'm getting a loop after installing: Success! That's It. Installation is Complete.

if you click on Login and generate a site tracker! it loops back to creating the admin password/email / 1st site to track page. don't seem to have a PHP error being shown.

**Comment by Stephan35** [comment]
Also loop for me !

php 7.1

**Comment by locvfx** [comment]
Can't install. Blank page at 'install.php?owa_action=base.installCheckEnv"
PHP 7.1

**Comment by locvfx** [comment]
After applied a quick fix: https://github.com/padams/Open-Web-Analytics/issues/242
Now I get stuck in the installation loop :(

**Comment by padams** [comment]
try the new code in master.

**Comment by locvfx** [comment]
sorry, I tried just now, still stuck in the installation loop! :(

**Comment by padams** [comment]
Turn on development logging in your config file and see what errors are in the owa error log file.

**Comment by padams** [comment]
Lots of PHP comparability changes have landed in master now. Reopen with specific debug errors.
