### ISSUE TITLE
I have a problem with showing page path and page title.

### ISSUE THREAD

**Issue by savkevip** [padams/Open-Web-Analytics#278]
Does anyone use this tools in SinglePageApps? 

The app is written in AngularJS.

For path tool always show '/' and when clicking on that I get correct URL(www.myapp.com/employees) but when I run Heatmap always show me index page(www.myapp.com/) or '/' (otherwise page) with correct 'colored clicks'...

![screenshot from 2017-09-12 17-32-49](https://user-images.githubusercontent.com/16799924/30334618-6e3eab3c-97e0-11e7-9a68-91c1965f5f4f.png)

**Comment by HussainMD** [comment]
@savkevip How you are tracking the site? using JavaScript or PHP tracking code?

**Comment by padams** [comment]
OWA can use used in a single page app. Just keep issuing commands via the owa_cmd queue. See the wiki for more details on how the issue tracker commands.
