### ISSUE TITLE
No data base tables are created

### ISSUE THREAD

**Issue by eboisen** [padams/Open-Web-Analytics#282]
I am attempting to install Open Web Analytics.  MySQL is installed, owadb database created, awadbuser created, user permissions set, and owa directory populated from install.  Install fails after I enter username and password in http://xxxxxxxxx/owa/install.php?owa_do=base.loginForm&owa_go=http%3A%2F%2Fwww.erikboisen.net%2Fowa%2Finstall.php%3Fowa_action%3Dbase.installCheckEnv&

I get a "this page isn't working"  Should the previous step have populated the database?  I set up Wordpress with PostgreSQL without much issue.  I thought this would be easy.  Any suggestions?

**Comment by padams** [comment]
postgreql is not supported.
