### ISSUE TITLE
Not able to set an EmailAddress

### ISSUE THREAD

**Issue by JildertDW** [padams/Open-Web-Analytics#283]
Hi,

We are considering using the OWA platform for our master thesis. However, therefore it is necessary that we can customize the user_email column in the owa_visitor table. We already succeeded in adding the user_name. 

We tried this, but the identifier "setEmailAddress" is not known. 

```
var owa_baseUrl = 'http://****.be/owa/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', '*****']);
owa_cmds.push(['setUserName', 'admin']);
owa_cmds.push(['setEmailAddress', 'admin@***.be']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);
```

Can anyone tell us how it should be set correctly?

Thanks in advance!

**Comment by padams** [comment]
Try owa_cmds.push(['setGlobalEventProperty', 'email_address', 'some@email.com']);

**Comment by mfishman** [comment]
@padams would you mind posting the complete JS Tracker Code that sends the username and email address. I have tried every variation explained here on the forums. I am on 1.6.0 and currently have this code and it's still not working:

var owa_baseUrl = 'https://syspass.klarinetsolutions.com/owa/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', '######']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);
//owa_cmds.push(['setUserName', 'admin']);
//owa_cmds.push(['setEmailAddress', 'M@k.com']);
owa_cmds.push(['setGlobalEventProperty', 'email_address','m@k.com']);
owa_cmds.push(['setGlobalEventProperty', 'user_name','admin']);

Thanks in advance.

**Comment by JildertDW** [comment]
Same, doesn't work for me either...

**Comment by padams** [comment]
ok, looks like OWA was looking for the wrong key name. I've fixed that in master.

**Comment by JildertDW** [comment]
Thanks! This issue can be closed now!
