### ISSUE TITLE
Can't see the stats

### ISSUE THREAD

**Issue by HussainMD** [padams/Open-Web-Analytics#284]
Hi I've got OWA installed no errors in the logs. I can see tables created on local mysql db. But after logging on to the OWA portal I dont see any stats of the locally hosted site.

Any thoughts what am I missing here?

Thakn you.
Hussain
![owa_login](https://user-images.githubusercontent.com/33723460/32893877-f72cd0d4-cad2-11e7-9e55-a3a8fc4faec5.JPG)

**Comment by HussainMD** [comment]
Looking at various tables on local db - except owa_site all have no data. I can owa_site has following domain and name: http://ukeqtydpc020:8080/

Regards,
Hussain

**Comment by HussainMD** [comment]
![owa_mainscreen1](https://user-images.githubusercontent.com/33723460/32902961-b1fdf7e0-caeb-11e7-8ebb-daf4a983e8b9.JPG)

**Comment by HussainMD** [comment]
??

**Comment by JildertDW** [comment]
We are experiencing the same. We're thinking that it might be because our website is a single page website.

**Comment by HussainMD** [comment]
Hey JildertDW, My site is hosted internally (intranet) but has multiple pages. OWA does gather stats in the database but not sure why its not showing them on the OWA site. Dont see any errors in the logs to investigate whats wrong..

**Comment by HussainMD** [comment]
how do i enable logging? as currently dont see anything int he OWA logs.

**Comment by HussainMD** [comment]
After enable logging. I see below error message in the logs:

[27-Nov-2017 11:51:15 Europe/Lisbon] PHP Fatal error:  Call to undefined function money_format() in C:\Webserver\Open-Web-Analytics\owa_lib.php on line 1119

**Comment by JildertDW** [comment]
What did you do to enable logging? We're having the same issue. Peter is helping me out in issue #286

**Comment by HussainMD** [comment]
uncomment below:

/** 
 * LOG PHP ERRORS
 *
 * Log all php errors to OWA's error log file. Only do this to debug.
 */

//define('OWA_LOG_PHP_ERRORS', true);

in owa-config.php under my OWA installation folder.

**Comment by HussainMD** [comment]
After updating to MASTER I am getting below error loading OWA -


Notice: Use of undefined constant OWA_DIR - assumed 'OWA_DIR' in C:\Webserver\Open-Web-Analytics\index.php on line 20

Warning: require_once(OWA_DIR/owa_php.php): failed to open stream: No such file or directory in C:\Webserver\Open-Web-Analytics\index.php on line 20

Fatal error: require_once(): Failed opening required 'OWA_DIR/owa_php.php' (include_path='.;\xampp2\php\PEAR') in C:\Webserver\Open-Web-Analytics\index.php on line 20

**Comment by padams** [comment]
did you blow away your config file?

**Comment by HussainMD** [comment]
yes looks like it :( now doing it from scratch. downloaded and installing 1.6.0 giving me this error - 
Fatal error: Class 'owa_db_' not found in C:\Webserver\OWA\owa_coreAPI.php on line 102

**Comment by padams** [comment]
Tour config file is not setup correctly. You need to specify the db type in the config file.

--
Peter Adams

**Comment by HussainMD** [comment]
Thanks @JildertDW and @padams on this issue. Its good now after downloading from master branch.
