### ISSUE TITLE
how to disable below error message?

### ISSUE THREAD

**Issue by HussainMD** [padams/Open-Web-Analytics#285]
Hi,

Can someone tell me how to disable below error message I get when I logged onto OWA?

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in C:\Webserver\Open-Web-Analytics\plugins\db\owa_db_mysql.php on line 112

Thank you.
Hussain

**Comment by padams** [comment]
Use the code in master.

**Comment by HussainMD** [comment]
not sure what you mean @padams

**Comment by padams** [comment]
I mean that this bug has recently been fixed in the master branch. Download the code from the master brand instead of the 1.5.x release tarball.

**Comment by HussainMD** [comment]
This is good now. Closing the issue. Thanks for the help @padams
