### ISSUE TITLE
GPL license and dynamic loaded content

### ISSUE THREAD

**Issue by JildertDW** [padams/Open-Web-Analytics#286]
Hi Peter,

We plan on using the Open Web Analytics framework for our master thesis. However, the company who are working with has some questions regarding the GPL license. Is it correct that we only need to make the source code of the changes to the OWA publicly available? Or do we need to open source the code in which we are using the OWA tracker publicly available as well - meaning we need to open source the entire product of our company? 

Secondly, the company is using a single web application in which dynamic content is loaded with javascript. The clicks on the dynamically loaded element don't seem to be tracked. We are guessing that this is currently not supported. If not, can you give us a direction in which we need to start looking in the code to implement this? If it is supported, any idea why the clicks aren't tracked in our application? 

Thanks in advance,

Jildert

**Comment by JildertDW** [comment]
The clicks are tracked perfectly in the database as well as visitor id's etc. Currently we found how to to gain information about dynamically loaded content. 

Still not showing up in the dashboard though.

**Comment by padams** [comment]
Turn on development logging in the config file and see what errors are reported in the log file when you load the dashboard. 

Also watch the http requests and responses made by the browser when you load the dashboard to see if there are any errors there as well.

**Comment by JildertDW** [comment]
I got these logs in de owa_data>logs folder. 
[errors_ae5f6c8be5b423af22f774fb7aa598a6.txt](https://github.com/padams/Open-Web-Analytics/files/1505224/errors_ae5f6c8be5b423af22f774fb7aa598a6.txt)

As for network errors after login, I don't see any popping up. I attached an image of the request that happen during loading up the dashboard. Hope this can help you to help us figure out the issue. 
<img width="1869" alt="screen shot 2017-11-27 at 10 19 44" src="https://user-images.githubusercontent.com/7084733/33259300-bc0a19d4-d35c-11e7-83b5-5759dc6d437a.png">

**Comment by padams** [comment]
Can you turn on debug logging in the config file? then login and re-post the error log.

**Comment by JildertDW** [comment]
Turned "define('OWA_LOG_PHP_ERRORS', true);" on in de owa-config.php, cleared out the log file and got this. From what I make from it, it may be an issue in the API? 

[errors_ae5f6c8be5b423af22f774fb7aa598a6.txt](https://github.com/padams/Open-Web-Analytics/files/1505335/errors_ae5f6c8be5b423af22f774fb7aa598a6.txt)

Not sure if it is the correct config file, as it says localhost for database and I'm running it on my server taptics.be.
[owa-config.txt](https://github.com/padams/Open-Web-Analytics/files/1505344/owa-config.txt)

**Comment by padams** [comment]
You need to also uncomment the error_log_handler line as well.

**Comment by JildertDW** [comment]
Oke, this should be all the logs. [error.txt](https://github.com/padams/Open-Web-Analytics/files/1510171/error.txt)

**Comment by padams** [comment]
ok. Try updating the new code in master and see how that works for you.

**Comment by JildertDW** [comment]
It seems to be working now !
