### ISSUE TITLE
Geo_Location as "not set"

### ISSUE THREAD

**Issue by HussainMD** [padams/Open-Web-Analytics#290]
Hi Guys,

Anyone seeing issue with GeoLocation as "Not Set" in OWA dashboard?

Please see attached. Any idea what needs to be done to track this?

Thank you. 
![image](https://user-images.githubusercontent.com/33723460/33605271-e144c8a2-d9b0-11e7-85b9-bd4625a72098.png)

**Comment by padams** [comment]
See the maxmind geoip module page in the wiki...

**Comment by HussainMD** [comment]
got it @padams thanks
