### ISSUE TITLE
12 Hour Format for Visit Time Display

### ISSUE THREAD

**Issue by ryanml** [padams/Open-Web-Analytics#293]
I couldn't see anything in the configuration for making timestamps display in 12 hour format as opposed to 24. 

Personally I prefer 24, but a non technical user of the platform had asked me about this. 

If this configuration isn't available, I'd love to take on the feature. It should be pretty straightforward. 

From an implementation standpoint, it probably would be best if this was a display only feature at the template level, to avoid breaking any dependencies that count on those stamps being in 24 hour format.

**Comment by ryanml** [comment]
For example, when set to display in 12 hour format, this would read:

Wed Dec 20 6:23:06 PM MST

<img width="208" alt="screen shot 2017-12-20 at 7 01 44 pm" src="https://user-images.githubusercontent.com/8732757/34237159-5b90ec54-e5b8-11e7-85d4-99511ae97718.png">

**Comment by ryanml** [comment]
@padams what are your thoughts on this? Do you think such a control in the configuration would be beneficial?

**Comment by padams** [comment]
All times are stored in the db as a Unix timestamp (seconds since 1970) so it’s likely being formatted by the view or template that renders that visit feed. 

Personally I don’t see a need to add an option for 12 hour formatting but I’d merge a patch if others do.

**Comment by padams** [comment]
Closing due to lack of patch. Reopen if you have a pull request to share for this.
