### ISSUE TITLE
Recorded URL truncated 

### ISSUE THREAD

**Issue by HussainMD** [padams/Open-Web-Analytics#296]
Hi, 

I have hosted OWA to internally hosted site. URL for pages are for example like  **http://site:8080/abc/mypage.php** while recorded URLs on **TOP CONTENT** truncates this and shows on the OWA dashboard as **http://site/abc/mypage.php**

Any idea why this is happening? and how to fix this?

Thank you.

**Comment by zecman** [comment]
If I understood right, OWA just leaves out the port. 

> http://site:8080/abc/mypage.php
> http://site/abc/mypage.php

What exactly is the problem?

**Comment by HussainMD** [comment]
Hi @zecman,

I would like to have a link with port as it is rather than truncated.

So expect recorded URL to be http://site:8080/abc/mypage.php

Thank you.

**Comment by padams** [comment]
OWA normalizes the url by removing g port numbers. Just use another siteid if you want to track something separately.

**Comment by npena** [comment]
Hi guys, I'm using OWA 1.6.9 and my site has port number in the url, and the links to view the heatmap, downstreams point are shown without the port number, and the web server has another app in 80 port, so I'm not able to see them. Is there some option to do not truncate the URL? Thanks.
