### ISSUE TITLE
only one Tracking Action Group displayed

### ISSUE THREAD

**Issue by Noeppes** [padams/Open-Web-Analytics#300]
Hello,
i have defined three Action Groups  with the code like "$owa->trackAction('Aktentrenner', 'Pappen', '---', 10);".
But only one (the first one) was displayed an count.

Noeppes

Oh... I used the newest Version!

**Comment by zecman** [comment]
Moin Noeppes,

maybe some kind of proxy may have served from cache?

Do you really want to increase Pappen by 10 with every request?

Grüße,
Z×C

**Comment by Noeppes** [comment]
Hi,
"Do you really want to increase Pappen by 10 with every request?" it's only a test!
All accessible caches, etc. have been emptied by me. Even today, days after definition of the Action Group, no entries are counted.

**Comment by zecman** [comment]
Could you please provide the part of your php file that initiates the action.

**Comment by Noeppes** [comment]
Error...
it's such a thing if you use a template engine ...
Error was with me ... but why always an action group was counted I do not know.
Now I've used the tracking code in the right place (where the template engine can not get there) and everything works fine.

Greetings 
Noeppes
