### ISSUE TITLE
Blank page on installation 

### ISSUE THREAD

**Issue by rritz66** [padams/Open-Web-Analytics#307]
I tried to install owa, never got past installation screen. After filling in database info, I get blank screen always. 

Filled in database info in cofig file and enabled debugging and logging. 
Now when I open owa index.php I get tons of lines like this: 

Warning: fopen(/var/www/vhosts/mydomain.com/httpdocs/owa/owa-data/logs/errors_230b919a1242baa02c88052094a5d4af.txt): failed to open stream: Permission denied in /var/www/vhosts/mydomain.com/httpdocs/owa/modules/base/classes/logFile.php on line 44 

I am on shared hosting that meets all the rquirements

**Comment by padams** [comment]
Try changing permissions so OWA can write to the owa-data directory.

**Comment by fvlasie** [comment]
I have the same problem on Fedora 27

**Comment by fvlasie** [comment]
Permissions set to 777 on own-data.

**Comment by fvlasie** [comment]
It seems to be selinux is up to its old tricks. Running the following on the install directory fixed it:

chcon -R unconfined_u:object_r:httpd_sys_rw_content_t:s0
