### ISSUE TITLE
owa_user creation fails

### ISSUE THREAD

**Issue by jotakar** [padams/Open-Web-Analytics#309]
The sql for creating owa_user
CREATE TABLE IF NOT EXISTS owa_user (id SERIAL AUTO_INCREMENT,.... 
gives error because AUTO_INCREMENT is included in SERIAL
I think lines 42 and 43 in user.php are redundant
$this->properties['id']->setDataType(OWA_DTD_SERIAL);
$this->properties['id']->setAutoIncrement();

If I delete the second line OWA is installed without any issue

Thanks

**Comment by padams** [comment]
Which version of MySQL are you running?

**Comment by jotakar** [comment]
I'm using MariaDB 10.2 on windows 10
Thanks

**Comment by simonefalcini** [comment]
Please fix in master, I had this issue too and fixed by commenting row 43.

**Comment by mallorn** [comment]
I ran into the same thing with MariaDB 10.3.10 today.  After fixing it I started to open a new issue and this came up as a possible alternative.

Basically, it borks when SERIAL and AUTO_INCREMENT are used together.

**Comment by seonwoolee** [comment]
I concur, I had to comment out row 43.

**Comment by squatto** [comment]
This will be fixed by #377 (open as of this comment)

**Comment by zeki893** [comment]
When will this get pushed to master?

**Comment by padams** [comment]
fixed in #377
