### ISSUE TITLE
Visits, unique visitors and page views all the same

### ISSUE THREAD

**Issue by nile16** [padams/Open-Web-Analytics#310]
I run a fresh install of version 1.6.1. It seems to work in general but the number for visits, unique visitors and page views are all the same. All three numbers count up when I reload the webpage I track. It is like all three counters show page views. When I click on visit details no data like IP address shows, it only reads '(not set)'. I use the PHP code. 

Thanks for this otherwise good software.

**Comment by padams** [comment]
are the owa cookies getting set in the browser?

**Comment by padams** [comment]
please post your php tracker code.

**Comment by nile16** [comment]
No cookie is stored according to FireFox.

<?php
require_once('/var/www/html/owa/owa_php.php');

$owa = new owa_php();
// Set the site id you want to track
$owa->setSiteId('fffffffffffffffffffffffffffffffffff');
// Uncomment the next line to set your page title
//$owa->setPageTitle('somepagetitle');
// Set other page properties
//$owa->setProperty('foo', 'bar');
$owa->trackPageView();
?>

SiteId is redacted.

Thanks.

**Comment by githubtd01** [comment]
I have the same problem.

```
<?php
require_once('/owa_php.php');
		
$owa = new owa_php();
// Set the site id you want to track
$owa->setSiteId('xxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
// Uncomment the next line to set your page title
$owa->setPageTitle($_SERVER['PHP_SELF']);
// Set other page properties
//$owa->setProperty('foo', 'bar');
$owa->trackPageView();
?>
```
Only sites where the URL includes something like "?names=" will be displayed.
I'm running PHP 7.1.

Did anybody find a solution???

Thank you very much,
best regards,
Tobias

**Comment by bennet-esyoil** [comment]
A little bit late to the party, but i'll join. Same issue here, probably don't need to post the Code.
I'm also on PHP7.3 but using the JS Tracker, tho there are no errors in the Apache Error logs.

**Comment by padams** [comment]
Give the code in master a try and see if that resolved your issue. Re-open if it doesn’t.
