### ISSUE TITLE
IP address displaying "Not set"

### ISSUE THREAD

**Issue by OpenWaveDigital** [padams/Open-Web-Analytics#312]
![screenshot](https://user-images.githubusercontent.com/31146868/36404514-198a5c06-15b9-11e8-9152-57d7b40ba05c.png)

I've enabled debugging but do not see IP addresses in the 'owa-data/logs/errors...' files. I also looked into the handles directory and made sure IP anonymization  was turned off. At a loss for why IP's are not being displayed. I tested tracking on 3 different domains. 

OWA instance is Ubuntu 16.04, apache2, mysql 5.7, php 7.0, if that matters.

**Comment by padams** [comment]
try adding the ip_address as a secondary dimension on any report data grid. Does it show up there?

**Comment by The-Juggernaut** [comment]
Hello!
I'm having the same problem. Adding ip_address does show the correct ip address

**Comment by wimbley** [comment]
What is the fix for this?

**Comment by jameshwc** [comment]
Hey, I have same problem currently.
The IP address is displaying "not set" there, however, when I added the ip_address as a secondary dimension, as mentioned below, I got the correct value. Any way to fix that bug? I know PHP and MySQL, however, I don't know which column I should insert the data.
![圖片](https://user-images.githubusercontent.com/45334777/59332250-5e312c80-8d28-11e9-9e8c-a5bfa156aaa9.png)

![圖片](https://user-images.githubusercontent.com/45334777/59332190-4063c780-8d28-11e9-812b-1982af192fd0.png)

**Comment by nedoskiv** [comment]
just installed it and have similar problem, on many pages it display not set, is this project become dead?

**Comment by BloodyIron** [comment]
I too am not getting IP Addresses, my website is behind a reverse proxy, however it is doing x-header forwarding so the website that is being tracked is getting the correct source IPs of traffic.

**Comment by faustoandrade78** [comment]
Hello, same problem here ..

**Comment by padams** [comment]
The IP address is never displayed in those summary box, only as a secondary dimension on reporting.

This is a different bug causing those (not set) values that is now fixed in master.
