### ISSUE TITLE
All referrals, locations, etc are "(not_set)"

### ISSUE THREAD

**Issue by SlidingHorn** [padams/Open-Web-Analytics#313]
I'm not getting any geolocation or referral link information at all.  Everything shows as (not_set).

Am I missing something here?  Everything from the support wiki seems to imply this information should be retrieved "out of the box"

**Comment by OpenWaveDigital** [comment]
Same issue. I was even able to get the geolocation module working, but the other items are (not_set).

**Comment by padams** [comment]
You need ot activate the maxmind module to get geoid info. See the maxmind page on the wiki on how to set that up.

**Comment by SlidingHorn** [comment]
Will do...What about the referral link info?

**Comment by padams** [comment]
Give the new code in master a try and see if you start seeing referer urls show up.

**Comment by SlidingHorn** [comment]
Just overwrite everything?

**Comment by SlidingHorn** [comment]
Sorry to be a bother - Just wondering if I'm supposed to extract the archive over my current installation or if I just need to replace specific files, etc.  

If I'm to extract the whole thing, are there any files I'll need to worry about fixing in terms of what's already configured?

**Comment by clickwork-git** [comment]
Also the GitHub version does not work.

**Comment by ketodiet** [comment]
Is the referrals issue fixed? If so is there a way to patch an OWA install to make referrals work? Thank you

**Comment by BloodyIron** [comment]
I took would like to know if "Search Terms" works with OWA, that's a rather critical feature that doesn't seem to work on the demo site.

**Comment by padams** [comment]
Sadly google stopped passing search terms in the url when using https at google.com
