### ISSUE TITLE
 Uncaught Exception in owa_entity.php Line 351

### ISSUE THREAD

**Issue by buggbear** [padams/Open-Web-Analytics#314]
Sometimes when I click on "heat map" I get this exeption:

PHP Fatal error:  Uncaught Exception: No value passed. in /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/owa_entity.php:351\nStack trace:\n#0 /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/owa_entity.php(334): owa_entity->getByColumn('id', NULL)\n#1 /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/modules/base/overlayLauncher.php(44): owa_entity->load(NULL)\n#2 /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/owa_controller.php(218): owa_overlayLauncherController->action()\n#3 /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/owa_coreAPI.php(791): owa_controller->doAction()\n#4 /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/owa_coreAPI.php(1214): owa_coreAPI::performAction('base.overlayLau...', Array)\n#5 /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/owa_caller.php(222): owa_coreAPI::handleRequest(NULL, 'base.overlayLau...')\n#6 /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/owa_caller.php(164): owa_caller->handleRequest()\n#7 /usr/share/O in /usr/share/Open-Web-Analytics-beta/Open-Web-Analytics/trunk/owa_entity.php on line 351

Url was:

/owa/index.php?owa_do=base.overlayLauncher&owa_overlay_params=eyJzaXRlSWQiOiI5NjNjY2NlZDAxMmRiN2NlYWZkYzQ4ZThlNmQ5MjFhZCIsInBlcmlvZCI6Imxhc3Rfc2V2ZW5fZGF5cyIsImFjdGlvbiI6ImxvYWRIZWF0bWFwIiwiYXBpX3VybCI6Imh0dHBzOlwvXC9hZG0uY3A3MDBibXcuY29tXC9vd2FcL2FwaS5waHAiLCJkb2N1bWVudF9pZCI6bnVsbH0=

Can someone maybe help me with this?

I'm using the Rev. 1750 TRUNK.

**Comment by padams** [comment]
Assuming this was resolved. If not please open with more debug detail.
