### ISSUE TITLE
Nenhum Report

### ISSUE THREAD

**Issue by PauloBoaventura** [padams/Open-Web-Analytics#315]
Hello, I installed OWA and after 3 days in our ... In the data ...
I'm using Joomla.

Should I have any permissions on the .htaccess or something similar?

Can I use Magento?

How to proceed?

Thank you for the development and I really want to print whatever you need ...

Att,
Paulo

BR
olá instalei o OWA e apos 3 dias nenhuma mudança nos dados...
Estou usando no Joomla.

Deve ter alguma permissão no .htaccess ou algo similar?

Posso usar em Magento?

Como proceder?

Agradeço pelo desenvolvimento e quero muito utilizar para reportar qualquer melhoria necessaria...

Att,
Paulo

**Comment by PauloBoaventura** [comment]
[https://github.com/padams/Open-Web-Analytics/issues/316](url)

**Comment by PauloBoaventura** [comment]
Still having problems ...
Can someone help me?

**Comment by buggbear** [comment]
Paulo, 

You don't need any .htaccess files for OWA. 

Just follow the instructions in the wiki

https://github.com/padams/Open-Web-Analytics/wiki/Installation

List your added sites on OWA, go to "Get Tracking Code", copy and paste the source code of the javascript code at the end of your index.php.

I am also using joomla and installing OWA was really easy.

**Comment by PauloBoaventura** [comment]
@buggbear 

So I wanted to answer you there = https://github.com/padams/Open-Web-Analytics/issues/316#issuecomment-369867685

But I did not ...

What I'm noticing is ~ and what the javascript in php ... and the script is interrupted when it runs ...

It is possible??

**Comment by buggbear** [comment]
Try removing all the .htaccess in the OWA directory first. You can increase security when you see it all is working. There must be world access to 'modules/base/js/' (maybe more? I don't know) else visitor's browser will not be able to call the OWA functions. 

>I put the bank of cities that did not have 

Sorry, I don't understand, what do you mean?

**Comment by padams** [comment]
Closing assuming this question was resolved.
