### ISSUE TITLE
Is this still being maintained 

### ISSUE THREAD

**Issue by rootinshell** [padams/Open-Web-Analytics#317]
Is this still being maintained? Error after installing.
Others above have pointed out. There are error messages coming up upon installation. Please if someone is maintaining it address this.

MediaWiki 1.22.5 PHP	5.3.10-1ubuntu3.11 (apache2handler) MySQL	5.5.37-0ubuntu0.12.04.1 Lua	5.1.5

Latest OWA instalaltion Error:

Warning:mysql_select_db() expects parameter 2 to be resource, boolean given in /home.../a/extensions/owa/plugins/db/owa_db_mysql.php on line 115

Warning: mysql_set_charset() expects parameter 2 to be resource, boolean given in /home.../a/extensions/owa/plugins/db/owa_db_mysql.php on line 118

Warning: mysql_real_escape_string() expects parameter 2 to be resource, boolean given in /home.../a/extensions/owa/plugins/db/owa_db_mysql.php on line 259

Warning: mysql_connect() [function.mysql-connect]: Can't connect to MySQL server on 'mysql...org' (111) in /home.../a/extensions/owa/plugins/db/owa_db_mysql.php on line 112

Warning: mysql_select_db() expects parameter 2 to be resource, boolean given in /home.../a/extensions/owa/plugins/db/owa_db_mysql.php on line 115

Warning: mysql_set_charset() expects parameter 2 to be resource, boolean given in /home.../a/extensions/owa/plugins/db/owa_db_mysql.php on line 118

Warning: mysql_errno() expects parameter 1 to be resource, boolean given in /home.../a/extensions/owa/plugins/db/owa_db_mysql.php on line 174

**Comment by padams** [comment]
The mediawiki plugin need some serious love. if you can debug and submit a pull request, we can merge your changes.

**Comment by Michelenzoo** [comment]
Use `127.0.0.1` instead of `localhost` when filling in db server

**Comment by padams** [comment]
Dupe with #460
