### ISSUE TITLE
Cannot see statistics

### ISSUE THREAD

**Issue by Syscon11** [padams/Open-Web-Analytics#32]
Hi,
I entered the tracking code on the site, but i cannot see the statitics, why?
Thanks.

![stat](https://cloud.githubusercontent.com/assets/9698167/5013243/80d279d8-6a8c-11e4-9e0b-b6bdc8517e77.jpg)

**Comment by aakarsha** [comment]
Any updates?

**Comment by padams** [comment]
Use a javascript debugger like firebug to see what is happening to the HTTP request to log.php. is it throwing an error?

**Comment by master-opr** [comment]
I have installed wordpress, and then owa in a separate folder (owa). when i added the tracing code (PHP code) in to index.php i got this error on bottom of my site :

Warning: Cannot modify header information - headers already sent by (output started at . . . . . .l\wwwroot\wp-includes\theme.php:1139) in .
.\wwwroot\owa\owa_coreAPI.php on line 1079

the owa admin dashboard works well but still there is not any report for showing.
php 5.3
my sql 5.1

**Comment by padams** [comment]
You do not need to add any code to WordPress pages. Install the OWA directory in the WordPress plugins folder and then activate it via the plugin admin screen in WordPress.

**Comment by master-opr** [comment]
Thanks for your reply.

1.by installing as wordpress plugging,where can i see its admin dashboard?
i activate it but didn't find any configuration or link to open dashboard.


2. beside,i want to know how could i activate tracing in any kind of websites,except wordpress. i want to be installed as a independent subfolder.

**Comment by master-opr** [comment]
is there any solution?

**Comment by padams** [comment]
Closing as likely resolved.
