### ISSUE TITLE
Mediawiki compatibility

### ISSUE THREAD

**Issue by RobJF** [padams/Open-Web-Analytics#320]
OWS has not been compatible with Mediawiki for a long time, so that promotion of such compatibility is seriously misleading.

Simply search issues for Mediawiki for evidence.

I strongly suggest that if compatibility with the current release of MW cannot be attained in the near future, these misleading claims should be dropped.

(I understand that this is a community effort and would love to contribute but my php skills are not adequate, nor do I currently have the time to improve them.)

**Comment by padams** [comment]
Will work on it. thanks.
