### ISSUE TITLE
Unable to set Page Title, Page Type, Entry Page etc in php tracking

### ISSUE THREAD

**Issue by userpqr** [padams/Open-Web-Analytics#321]
The question looks astonishingly simple. But, I searched a lot and could get no answer. 
I have added the php tracking code in footer. Views are getting tracked, but page titles, entry page, exit page etc are showing as not set. I tried setting 

owa->setPageTitle($_SERVER['PATH_INFO'];

But, got no result.

I got the php tracking code from the website->get tracking code. It looks like it does not work. Can someone give me a sample php code for owa for tracking page titles etc as mentioned above ?

**Comment by padams** [comment]
Please give the code in master a try. There are some fixes there that are relevant to this issue.

**Comment by userpqr** [comment]
Thanks for the response. I am now using the code that is mentioned here : https://github.com/padams/Open-Web-Analytics/wiki/PHP-Invocation What I understood is, if the URL contains some parameter like ?a=0 then the Page path, title etc gets set. Otherwise, it shows page path not set.

Am I missing something here in the code or in the settings ? Is there any way I can set the page path etc when the URL does not have any parameter ?

**Comment by userpqr** [comment]
Can you please give me the URL of the code in master that you referred here ?

**Comment by WmShrPy** [comment]
Same remark as **userpqr**, on a fresh installation of 2018-03-18 master version.
On PHP tracking, value passed at _setPageTitle()_ isn't interpreted when a page is called without parameter ; "not set" informations are stored/viewed.
( The only tracking mode tested was with _trackPageView()_ )

**Comment by padams** [comment]
Just added the fix to master.

**Comment by githubtd01** [comment]
did a complete new installation with the new master and I'm still having the same problem.

**Comment by padams** [comment]
Did you use a clean db?

**Comment by githubtd01** [comment]
I did deleted the complete database and created a new one.

**Comment by padams** [comment]
Make sure you clear your owa_s cookie when you retest otherwise you will be stuck in the same session.

If you turn on development logging in the config file. OWA will tell you exactly what it’s doing to every property passed by the tracker. That should give you a clue as I can’t reproduce your issue.

**Comment by padams** [comment]
fix has landed.
