### ISSUE TITLE
WTF?

### ISSUE THREAD

**Issue by fjeddy** [padams/Open-Web-Analytics#322]
Can't define the username for the first user, `admin`, and I can't delete the user when I finally managed to make a new one.

Can't set a complicated, comprehensive password containing all sorts of characters without getting errors saying I need minimum 6 characters.

I can't set SMTP details within OWA and it expects it to be setup, configured and ready to go server-side, yet, you include a SMTP class and library within the OWA code. Why?

When you click "Create a new password" as an admin on another user, not only is it just a plain "Password recovery" tool that's literally useless in that scenario, but on top of that, the form is NOT filled with the users email address, you have to enter it manually.

Don't get me wrong, I love the enthusiasm and willingness to create open source software. But why bother in the first place if you're just going to do everything half-assed?

Deleting and forgetting about this waaaay quicker then it took me to set it up.

EDIT: NVM, guess I should pay better attention. Just realised this project hasn't been given any love in 8 years and can be considered dead, most likely not even safe to use anymore.

**Comment by padams** [comment]
The project is still being developed and if you look at the release timeline you would see that.

**Comment by fjeddy** [comment]
Yeah, no, what you call "still being developed" is what the rest of the world call "dead, but kept functional".
