### ISSUE TITLE
owa_session_referer: (none)

### ISSUE THREAD

**Issue by chrismatchett** [padams/Open-Web-Analytics#324]
Hi,

I setup a test referral link but I'm not seeing results as expected in chrome devtools using the javascript tracker? How do I get referral links?

owa_medium: direct
owa_source: (none)
owa_search_terms: (none)
owa_session_referer: (none)
owa_HTTP_REFERER: 

Ta,

Chris

**Comment by padams** [comment]
Referer comes for the referrer header of the http request. It’s not something you typically explicitly set on the tracker. If that header is present then OWA should pick it up.

To test setup a link to your OWA record web page on another domain, clear your OWA cookies and then click over.

**Comment by chrismatchett** [comment]
Thanks, it was my bad.

I was unaware that https doesn't pass a referrer header to http. Took a while to work that out.

Great system, thanks.

Chris
