### ISSUE TITLE
Unable to get the specific Authenticated user wise clicks tracking report

### ISSUE THREAD

**Issue by rakeshdongarwar1** [padams/Open-Web-Analytics#325]
Hello Support Team,
Thanks for the code.
Actually my requirement is to track the clicks of authenticated user, but currently it gives me the report for overall. Can you please suggest how could I generate the user wise report.

Thanks ins advance.

**Comment by padams** [comment]
As long as you populate the user_name and user_email dimensions in your tracking request they are available as secondary dimensions in reporting.
