### ISSUE TITLE
broken documentation links

### ISSUE THREAD

**Issue by themancalledjakob** [padams/Open-Web-Analytics#327]
In some links in the documentation you get a page "not found"
e.g. if you go here: http://demo.openwebanalytics.com/jstracker.php

then click on the link in "Consult the OWA wiki for more information and documentation on OWA's Javascript tracker." at the top of the page.
You are linked to "https://github.com/padams/Open-Web-Analytics/wikiindex.php?title=Tracker" 
This page does not exist, I first thought there is just a slash missing between wiki & index.php¸but that gets you just to the index of the wiki, and not to the JavaScript tracker.
I guess it should be "https://github.com/padams/Open-Web-Analytics/wiki/Tracker"

This happens relatively often unfortunately, and makes browsing the documentation quite tiring.

**Comment by padams** [comment]
fixed.
