### ISSUE TITLE
domstream issues

### ISSUE THREAD

**Issue by themancalledjakob** [padams/Open-Web-Analytics#328]
(1) it would be great if it would be mentioned in the documentation that you have activate the "domstream" module in the administration.
It took me a while to figure that out... ;-) 

(2) The clicks in the domstream are inaccurately placed.
I realized that mouse coordinates are off, when the domstream is viewed in different dimensions than when it was recorded.
for example:
I visit the site with a browser set to half width of the screen.
I view the recorded domstream with a browser set to full width of the screen.
-> all mouse movements are skewed 50% in x position.

(3) dom in domstream does not respond to the playback
The mousemovement is executed (with inaccuracies, see 2), and I can see clicks marked with a red dot.
Though, the dom does not react on the clicks or mouseovers.

(3) dom in domstream does respond to admin mouse
When I play back a domstream, while it does not react to the recorded mouse actions, it does react to the mouse actions of the one viewing the domstream. This seems counter productive, since I only want to see how visitors use the site and not accidentially trigger something that distorts watching the experience.

I experienced all of the issues in a similar manner both with Chrome and/or Firefox as visitor and/or admin.

My system:
OS 4.14.30-1-MANJARO (linux)
Chrome Version 65.0.3325.146 (Official Build) (64-bit)
Firefox 59.0.1 (64-bit)

I couldn't find a version number of OWA in the adminstration panel, but the last commit in git log is:
commit 00c3a91b7bbf7a0d3f089f9090852b72da1f6f3b
Date:   Tue Mar 20 03:35:23 2018 -0700

I used both synchronous and asynchronous javascript tracker.
No wordpress or mediawiki, no php tracker.

**Comment by davetbo** [comment]
I clicked Activate on the Domstream module but nothing seems to have happened.  How can I tell if it's working?  Where can I see the recordings?  I suspect it's not properly enabled.

Thanks :)
Dave

**Comment by davetbo** [comment]
I eventually figured it out. Thanks!

**Comment by BloodyIron** [comment]
> You need to enable it in your JS tracker tag code as well if it’s not already. See the wiki. If you don’t see the browser POSTIng data to OWA whenever you move the mouse then it’s not enabled In your tracker tag code.
> […](#)
> On Dec 10, 2018, at 2:44 PM, davetbo ***@***.***> wrote: I clicked Activate on the Domstream module but nothing seems to have happened. How can I tell if it's working? Where can I see the recordings? I suspect it's not properly enabled. Thanks :) Dave — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

This is the part I missed, as I enabled it but didn't realise it would add another line to the tracker JS code. Thanks! :D
