### ISSUE TITLE
pageTitle and pageType won't set via javascript tracker

### ISSUE THREAD

**Issue by themancalledjakob** [padams/Open-Web-Analytics#329]
I track page views like this:
```
OWATracker.setPageTitle('myPageTitle');
OWATracker.setPageType('myPageType');
OWATracker.trackPageView();
```

In the report I can see that page views are tracked, though the page title is always taken from the <title> tag and not from what I explicitly set manually via the tracker.
These values do show up though at page path, not title.

Also, not all page views show up.
![screenshot from 2018-04-15 18-04-19](https://user-images.githubusercontent.com/1830798/38780483-7d9134a6-40d7-11e8-970e-581d214c0b21.png)

As you can see, the number of total page views is "84", but when I count the individual pageviews together I come to a different value (10 + 7 + 2 = 19).

The page type is weirdly enough always the first one I set and stays the same for all visitors.
When I drop the owa table content in mysql, I can set a new page type, but it'll stay like this until I drop the mysql table again or ceompletely reinstall owa.

I get no errors in the javascript console.

My system:
OS 4.14.30-1-MANJARO (linux)
Chrome Version 65.0.3325.146 (Official Build) (64-bit)
Firefox 59.0.1 (64-bit)

My owa is at the last commit ( 00c3a91b7bbf7a0d3f089f9090852b72da1f6f3b / Tue Mar 20 03:35:23 2018 -0700 / properly setting current url on request. fixing #321 )

I used both synchronous and asynchronous javascript tracker.
No wordpress or mediawiki, no php tracker.

**Comment by padams** [comment]
page title not being overloaded is a bug now fixed in master. 

page type and title are tied to the page url in the owa_document table. Those values will not change over time for a given URL even if you decide to set different values for them in the tracker.
