### ISSUE TITLE
OWA tracks wordpress pages multiple times

### ISSUE THREAD

**Issue by userpqr** [padams/Open-Web-Analytics#330]
I am already using php tracking of OWA in my main server and it works properly there. Recently, I downloaded updated version of OWA in my development server and followed similar steps to activate OWA. But, I can see OWA's php tracking is tracking wordpress pages multiple times sometimes. And, I see some pages with urls /path-to-themes/fonts/**webfonts.***?v=*** are being tracked multiple times with almost each page load. Sometimes it tracks pages properly though. I tried adding the code in header as well as footer, but the problem persists. 
I downloaded recent version of OWA from the website and installed it following the installation instructions. 
Is there any recent changes in OWA that may be triggering the issue ? Please help.

**Comment by padams** [comment]
impossible to tell from this information how you are including the php tracker code in your web app but chances are it's being included twice. Feel free to reopen if you can provide more info.
