### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by kordic27** [padams/Open-Web-Analytics#332]
hi there,
I looked through prior posts, and I didn't see my issue anyplace - so forgive me if it has been answered (and just point me there).... 
I am going through the install process and are getting two very different errors.
If I open the install.php file in Chrome, I receive the following:

PHP Notice:  Use of undefined constant OWA_ERROR_HANDLER - assumed 'OWA_ERROR_HANDLER' in E:\WebSites\owa\modules\base\templates\config_dom.tpl on line 15

If I open it in IE, I get an internal 500 error:   The website cannot display the page

Any thoughts on where I should look first? 

Thanks
JK

**Comment by padams** [comment]
Set OWA to development logger mode in the config file. That will produce an errors log file in owa-data/logs that will show you where OWA is getting stuck.
