### ISSUE TITLE
GDPR / DSGVO

### ISSUE THREAD

**Issue by ballrock2** [padams/Open-Web-Analytics#336]
Hey,

are there any informations about using OWA in Europe with the new GDPR / Privacy-Rules? Is the tool ok with it when IPs are anonymized? Is there an option to set a "no tracking"-cookie or something in this way?

Best regards
Andreas

**Comment by padams** [comment]
There are a few changes in master that bring OWA into closer alignment with GDRP. But, generally speaking, if you are not logging user-names or email, and you anonymize IPs you should be ok. 

Also, OWA respects the donottrack property that can be set by users in their web browser. 

However, if you wanted to allow users to opt-out of OWA tracking on a specific website, yo would need to set your own opt-out cookie and look for it before inserting the OWA commands. If you set an opt-out cookie you can then use OWA's new `['pause-owa']` cmd to prevent tracking (See #338).

A good template for this can be seen in this article: https://webgilde.com/en/analytics-opt-out/

**Comment by criterion9** [comment]
Is there a list of the remaining changes to be made somewhere or master branch is ready to go?

**Comment by padams** [comment]
Master is ready to be used.
