### ISSUE TITLE
PHP error on wrong domain?

### ISSUE THREAD

**Issue by PortMacOnline** [padams/Open-Web-Analytics#339]
Hi guys,
I am new to Github and OWA so please be gentle with a noob!

I installed OWA on a domain called portmac.pw, and I am getting an error message on another one of my domains, portmaconline.com. The error message is:

require_once('/home/portmacpw/public_html/owa/owa_php.php'); $owa = new owa_php(); // Set the site id you want to track $owa->setSiteId('ca487772a9da59859eeb7f830b745305'); // Uncomment the next line to set your page title //$owa->setPageTitle('somepagetitle'); // Set other page properties //$owa->setProperty('foo', 'bar'); $owa->trackPageView(); 

![owa-error](https://user-images.githubusercontent.com/7662890/40953957-91e9f47c-68c5-11e8-8af5-bd2d656ea959.png)

The worrying thing is that the error message is still showing, even though I have uninstalled OWA from the portmac.pw domain. Can anyone point me in the right direction here? I would like to get OWA up and running properly because I am not too keen on giving Google all my data to sell!   :-)

Terry

**Comment by padams** [comment]
Someone pasted the Php tracking code from your own domain into this webpage. You should consult your developer.
