### ISSUE TITLE
change project license

### ISSUE THREAD

**Issue by miclando** [padams/Open-Web-Analytics#340]
hi,

at the moment the project is licensed as GPL.
as a result, open source projects that are licensed as Apache 2 can't consume this infrastructure because it will limit the license under which they are being developed.

is there any plan to change the license to Apache 2 ?

the project i am leading is checking the option of using open wed analitics.
https://github.com/onap/sdc

and at the moment we are blocked by the license issue.
i would apriciate your response.

**Comment by padams** [comment]
No plans in the works to change licenses.

**Comment by siva538** [comment]
Thanks @padams for your feedback on this. 

However have a concern that if we just make the licensing as GPL (V2 or V3) for OWA, this would constraint many commerical applications using this, as this would mean the source code being made available to the public for software products derived from or using OWA, or that incorporate, the OWA code in the system. 

Are there any plans to avoid this viral affect of making the sources available for commercial applications?

**Comment by siva538** [comment]
Hi @padams , one quick thought though. If you can at least make the JS tracking code as "BSD" license or MIT License, it would help us handle the premise installations without any licensing issues. 

Request you to consider this minor piece.

**Comment by padams** [comment]
Why would you need a different license to use this on premise? GPL only applies to OWA code/files not your web app code.

**Comment by siva538** [comment]
Thanks much for your response on this. 

Per the GPL guidelines (please correct me if I am wrong) if we have to embed the tracking code in our application, it would also mean that we have to make our commercial app as well GPL open source right (since we are distributing the tracking code as part of Commercial app) ? 

Hence to avoid that we are requesting to at least consider the tracking code as  being made as BSD or MIT License, so we can skip that clause and not make our code GPL.

**Comment by padams** [comment]
Are you talking about the JavaScript snippet that loads the tracker JS library? That’s not a file in he OWA code distro and doesn’t carry a license notice at all as far as I know...

**Comment by praveen5959** [comment]
What about if we use the minified js file from OWA repo? Then should we open source our code also?
