### ISSUE TITLE
Loading existing data

### ISSUE THREAD

**Issue by atifghaffar** [padams/Open-Web-Analytics#342]
Hi all,

Has someone already loaded data into OWA?
I would like to load from a db, or I can generate apache compatible logs and then load from them.

I have data in db in this format 
+--------------+-----------------+------+-----+---------------------+-----------------------------+
| Field        | Type            | Null | Key | Default             | Extra                       |
+--------------+-----------------+------+-----+---------------------+-----------------------------+
| id           | int(11)         | NO   | PRI | NULL                | auto_increment              |
| domain       | varchar(100)    | NO   | MUL | NULL                |                             |
| query_string | text            | YES  |     | NULL                |                             |
| update_time  | timestamp       | YES  |     | 0000-00-00 00:00:00 | on update CURRENT_TIMESTAMP |
| insert_time  | timestamp       | YES  | MUL | 0000-00-00 00:00:00 |                             |
| useragent    | varchar(100)    | YES  | MUL | NULL                |                             |
| sc           | int(2)          | YES  |     | NULL                |                             |
| sw           | int(11)         | YES  |     | NULL                |                             |
| referer      | varchar(255)    | YES  |     | NULL                |                             |
| page         | varchar(255)    | YES  |     | NULL                |                             |
| remote_addr  | varchar(20)     | YES  |     | NULL                |                             |
| checked      | int(2) unsigned | NO   | MUL | 0                   |                             |
| cookie       | int(1)          | NO   |     | 0                   |                             |
| week         | char(7)         | YES  |     | NULL                |                             |
| browser      | varchar(20)     | YES  |     | NULL                |                             |
| os           | varchar(20)     | YES  |     | NULL                |                             |
| date         | date            | YES  | MUL | NULL                |                             |
| hour         | char(2)         | YES  |     | NULL                |                             |
| year         | char(4)         | YES  |     | NULL                |                             |
| month        | char(2)         | YES  |     | NULL                |                             |
| day          | char(2)         | YES  |     | NULL                |                             |
+--------------+-----------------+------+-----+---------------------+-----------------------------+

Thanks

**Comment by padams** [comment]
This is not supported. OWA must generate it's own GUIDs during tracking events.
