### ISSUE TITLE
Could not instantiate mail function.

### ISSUE THREAD

**Issue by rogereab** [padams/Open-Web-Analytics#346]
I see that this has been asked before with no real answer.

What have I missed?

Set everything up and all works very well apart from the fact that I cannot add a new user fully or change email address as it cannot start the email system up and the following message appears in the top left of the browser window.

"Could not instantiate mail function."

Is there something else to install/set up or tweak, I've looked but cannot find anything.

Is this a hosting issue, I use Siteground in Europe.

Thanks, any help appreciated

Roger B

**Comment by siva538** [comment]
Hi Roger, I couldn't find any direct UI provision where the SMTP can be configured. However there were some underlying php pages the application is using "PHP-MAIL", and it might work when configured with the appropriate SMTP server. You can give it a try.

**Comment by rogereab** [comment]
Thanks for your response. I looked closely and searched the whole system for the wording "Could not instantiate mail function." but couldn't find it within the owa folder. 
I've attached a screenshot that shows that the email has been sent as far as the OWA system is concerned but it may be something on the hosting side that returns the "Could not instantiate mail function." wording!

![screen shot 2018-07-31 at 14 46 54](https://user-images.githubusercontent.com/40893559/43463555-c424b6de-94d0-11e8-8f83-a15486456803.png)

**Comment by rogereab** [comment]
OK, looked closer and found what is needed. Can't seem to get past the $from where it objects to the field. maybe it needs a later version of PHP mailer?

**Comment by rogereab** [comment]
So . . as I'm using this on a sub domain I didn't want to risk other problems as I have many email accounts sitting there.
So I modified the 'class.phpmailer.php' file with some hard coded details (yes I know its a problem when updating) but it now works as it should!
This will do until I can figure out what exactly I should put in the php.ini file to make it work. 
Anybody know as a Google search produces all sorts of wrong answers - and I know because I've tried many of them, some of which crashed the script!
All help appreciated!

**Comment by JeusuDigital** [comment]
I fixed this by updating PHP Mailer to 5.2.27, just upload PHPMailer-5.2.27 folder under /includes and then update the define path in owa_env.php

**Comment by padams** [comment]
When you say hard code where are you doing that?

**Comment by padams** [comment]
PHPMailer has been updating in master so I'm closing this now.
