### ISSUE TITLE
Do not tracking sites.

### ISSUE THREAD

**Issue by josowa** [padams/Open-Web-Analytics#347]
Hello Everyone,
I just installed OWA in a hosted site. the rooster site it's working, I added 3 more websites and it's not showing any information, nothing at all. Is there a way to see a log file to find out what is happening?

Thanks.

**Comment by padams** [comment]
Are you using the code from master or a zip of the the last tag?

Yes there is a log file. Turn on Dev logging in the config file and look in the owa-data/logs die.

**Comment by josowa** [comment]
Installed from Softaculous CP, OWA v1.6.2. 
Attached part of the dev log file.
[OWA- LogFile.txt](https://github.com/padams/Open-Web-Analytics/files/2183148/OWA-.LogFile.txt)

**Comment by josowa** [comment]
Also noticed that only rooster site is logging. other 3 sites data is not shown in dev log file.
I opened rooster site, and log datda is shown let's said 23:16:12, after that opened pages in other 3 sites but timestamp in log file still the same.
