### ISSUE TITLE
Wordpress plugin track code error

### ISSUE THREAD

**Issue by myjomtienhome** [padams/Open-Web-Analytics#351]
After installation of owa plugin 162 no tracking data in dashboard, I guess wrong tracking codes
created:
var owa_baseUrl = '//domainname.com/wp-content/plugins/owa/';
should be:
var owa_baseUrl = 'https://domainname.com/wp-content/plugins/owa/';

...no data is tracked and generated
Where is the code included in the WP web sites?

**Comment by myjomtienhome** [comment]
I removed the WP plugin and made standalone installation, made tracker code in theme footer - works-
The separate plugin is not working either wit acually WP:
=== Open Web Analytics Plugin===
Contributors: chrische
Tags: owa, openwebanalytics, analytics, stats, statistics, open web analytics, statistics
Requires at least: 2.5
Tested up to: 3.1
Stable tag: 1.3

This plugin adds the Open Web Analytics javascript code into the footer of
your website. It has several useful options.

== Description ==****

**Comment by padams** [comment]
I suspect you are not entering the URL properly WordPress.  The WordPress address (URL) setting (set in Settings > General) needs to include a protocol such as http or https.

**Comment by padams** [comment]
The Wordpresses plugin has been updated in master so give that a try if you are still having issues.
