### ISSUE TITLE
OWA Install script : Blank page after writing DB information

### ISSUE THREAD

**Issue by Tomawak** [padams/Open-Web-Analytics#352]
Hello,

I have an issue while trying to install OWA on my server.
Just after I fill the Configuration Settings, I get a blank page. :(
No error, nothing.
The URL I can see in the nav bar is "install.php?owa_action=base.installCheckEnv".
I tried replacing error_reporting(0) by error_reporting(E_ALL) in daemon config, but nothing change.

I downloaded lastest version (1.6.2), installed it in /var/www/owa and used a symlink (my document root point to another directory). I use PHP 7.2 and I really don't get what i'm doing wrong.

Can anyone help me ?

**Comment by siva538** [comment]
I am getting this behavior too. And it seems to be in 1.6.2 itself. OR with the latest version of PHP. 

Even after logging enabled, there are a bunch of errors displayed in the screen, but no clue on how to resolve this - 

Warning: fopen(/var/www/html/owa/owa-data/logs/errors_4cf4ad592bc9981092ed73e0343934c2.txt): failed to open stream: Permission denied in /var/www/html/owa/modules/base/classes/logFile.php on line 44

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 45

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 46

Warning: fopen(/var/www/html/owa/owa-data/logs/errors_4cf4ad592bc9981092ed73e0343934c2.txt): failed to open stream: Permission denied in /var/www/html/owa/modules/base/classes/logFile.php on line 44

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 45

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 46

Warning: fopen(/var/www/html/owa/owa-data/logs/errors_4cf4ad592bc9981092ed73e0343934c2.txt): failed to open stream: Permission denied in /var/www/html/owa/modules/base/classes/logFile.php on line 44

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 45

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 46

Warning: fopen(/var/www/html/owa/owa-data/logs/errors_4cf4ad592bc9981092ed73e0343934c2.txt): failed to open stream: Permission denied in /var/www/html/owa/modules/base/classes/logFile.php on line 44

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 45

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 46

Warning: fopen(/var/www/html/owa/owa-data/logs/errors_4cf4ad592bc9981092ed73e0343934c2.txt): failed to open stream: Permission denied in /var/www/html/owa/modules/base/classes/logFile.php on line 44

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 45

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/owa/modules/base/classes/logFile.php on line 46

**Comment by padams** [comment]
Sounds like permissions on the own-data directory are not set properly. OWA is complaining about not being to create or access the log file...

**Comment by padams** [comment]
I just added a check for this in the installer. If you update from master and try again if should show a proper error.

**Comment by Tomawak** [comment]
Correct, it was permission issue.
Thanks for your work :)
