### ISSUE TITLE
On-Premise Install

### ISSUE THREAD

**Issue by ibril15** [padams/Open-Web-Analytics#353]
Hello,

We are in the process of implementing OWA for our enterprise application.  Most of our customers are SaaS, however a portion are On-Premise where the application code is hosted on the customer's environment (or on AWS, Azure, etc.).  Under GPLv2, it does not appear that we would have to share our application's source code to integrate with OWA in our SaaS hosting model.  But what about for the on-premise customers?

- Would installing our application along with OWA on the customer's servers be considered "distribution" and we would therefore be required to release our source code?
- What if only the JS aspects are installed on the customer's environment, and the back end is still in our data center?  Does that change anything?
- What if the OWA application is installed but disabled (not used), does that still count as distribution?
- Is there possibility for obtaining a separate license for specific companies (like ours) implementing a wide-ranging solution?

Thank you in advance.

-Igor

**Comment by LukeTully** [comment]
@padams

**Comment by padams** [comment]
The GPL does not prevent you from installing the software on your own hardware. It doesn’t know or care where you install. Where people typically get into trouble with the GPL is when they modify the software and then try to redistribute it without those modifications.

If you aren’t modifying OWA or redistributing it then, there is generally no issue.

Also, If you are unclear about the GPL there are plenty of lawyers out there that specialize in it.
