### ISSUE TITLE
GeoIP issues

### ISSUE THREAD

**Issue by wimbley** [padams/Open-Web-Analytics#356]
I have:
owa>owa-data>maxmind>GeoLite2-City.mmdb
owa>owa-data>maxmind>GeoLite2-Country.mmdb
owa>owa-data>maxmind>GeoLite2-ASN.mmdb

and have added to my:
owa>owa-config.php the following code:

define('OWA_MAXMIND_DATA_DIR', '/owa-data/owa-data/maxmind/'); // Maxmind GeoLite City GEOLOCATION path

and I have the Modules>Maxmind GeoIP turned on, as well as:

ADMIN>Geo-location (perform geo-location lookup) turned on.

I still see 'not set' for all country, city, etc. data.

I have used secondary dimension select: IP Address and see the Ip addresses of my visitors.

What am I doing wrong? Thanks in advance for any help!

**Comment by padams** [comment]
Turn on development logging in your config file and look in the OWA error log to see where the maxmind module is failing.

**Comment by wimbley** [comment]
I turned on logging and get the following:

21:30:31 2018-08-24 30602 [debug_log] About to perform action: base.apiRequest 
21:30:31 2018-08-24 30602 [debug_log] Getting state - store: u key:  
21:30:31 2018-08-24 30602 [debug_log] Getting state - store: p key:  
21:30:31 2018-08-24 30602 [debug_log] loading last value in initial state container for store: p 
21:30:31 2018-08-24 30602 [debug_log] populating state for store: p, name: , value: 6e0d4df35ba38327cfb8479143e9ddabc2dac3627d0b78f50e3c1947dfe6b2b9, store type: cookie, is_perm:  
21:30:31 2018-08-24 30602 [debug_log] Getting state - store: u key:  
21:30:31 2018-08-24 30602 [debug_log] Getting state - store: p key:  
21:30:31 2018-08-24 30602 [debug_log] check cache file: /data/57/3/5/80/3820080/user/4244390/htdocs/bestsignmonuments/owa/owa-data/caches/1/owa_user/b947f150c0d1f0c8a85c2466597ff41a.php 
21:30:31 2018-08-24 30602 [debug_log] Cache File not found for Collection: owa_user, id: b947f150c0d1f0c8a85c2466597ff41a, file: /data/57/3/5/80/3820080/user/4244390/htdocs/bestsignmonuments/owa/owa-data/caches/1/owa_user/b947f150c0d1f0c8a85c2466597ff41a.php 
21:30:31 2018-08-24 30602 [debug_log] CACHE MISS - object not found for Collection: owa_user, id: b947f150c0d1f0c8a85c2466597ff41a 
21:30:31 2018-08-24 30602 [debug_log] Col: user_id, value: admin 
21:30:31 2018-08-24 30602 [debug_log] Query: SET SESSION sql_mode='' 
21:30:31 2018-08-24 30602 [debug_log] Query: SELECT * FROM owa_user WHERE user_id = 'admin'    LIMIT 1  
21:30:31 2018-08-24 30602 [debug_log] set key: user_id1 
21:30:31 2018-08-24 30602 [debug_log] set hkey: c30da9265ba0a4704db9229f864c9eb7 
21:30:31 2018-08-24 30602 [debug_log] Added Object to Cache - Collection: owa_user, id: c30da9265ba0a4704db9229f864c9eb7 
21:30:31 2018-08-24 30602 [debug_log] Added Object to Dirty List - Collection: owa_user, id: c30da9265ba0a4704db9229f864c9eb7 
21:30:31 2018-08-24 30602 [debug_log] entity loaded from db 
21:30:31 2018-08-24 30602 [debug_log] check cache file: /data/57/3/5/80/3820080/user/4244390/htdocs/bestsignmonuments/owa/owa-data/caches/1/owa_user/b947f150c0d1f0c8a85c2466597ff41a.php 
21:30:31 2018-08-24 30602 [debug_log] Cache File not found for Collection: owa_user, id: b947f150c0d1f0c8a85c2466597ff41a, file: /data/57/3/5/80/3820080/user/4244390/htdocs/bestsignmonuments/owa/owa-data/caches/1/owa_user/b947f150c0d1f0c8a85c2466597ff41a.php 
21:30:31 2018-08-24 30602 [debug_log] CACHE MISS - object not found for Collection: owa_user, id: b947f150c0d1f0c8a85c2466597ff41a 
21:30:31 2018-08-24 30602 [debug_log] Col: user_id, value: admin 
21:30:31 2018-08-24 30602 [debug_log] Query: SELECT * FROM owa_user WHERE user_id = 'admin'    LIMIT 1  
21:30:31 2018-08-24 30602 [debug_log] set key: user_id1 
21:30:31 2018-08-24 30602 [debug_log] set hkey: c30da9265ba0a4704db9229f864c9eb7 
21:30:31 2018-08-24 30602 [debug_log] Added Object to Cache - Collection: owa_user, id: c30da9265ba0a4704db9229f864c9eb7 
21:30:31 2018-08-24 30602 [debug_log] Added Object to Dirty List - Collection: owa_user, id: c30da9265ba0a4704db9229f864c9eb7 
21:30:31 2018-08-24 30602 [debug_log] entity loaded from db 
21:30:31 2018-08-24 30602 [debug_log] loading assigned sites 
21:30:31 2018-08-24 30602 [debug_log] Query: SELECT * FROM owa_site_user WHERE user_id = '1'     
21:30:31 2018-08-24 30602 [debug_log] Filtering allowed_sites_list 
21:30:31 2018-08-24 30602 [debug_log] Filtering auth_status 
21:30:31 2018-08-24 30602 [debug_log] Checking if user is capable of: view_reports 
21:30:31 2018-08-24 30602 [debug_log] No capability passed or user is an admin and capable of everything. 
21:30:31 2018-08-24 30602 [debug_log] no start/end params passed to owa_metric::setTimePeriod 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for visits 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for pagesPerVisit 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for pageViews 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for visits 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for visitDuration 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for bounceRate 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for bounces 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for visits 
21:30:31 2018-08-24 30602 [debug_log] getting metric entities for uniqueVisitors 
21:30:31 2018-08-24 30602 [debug_log] pre-reduce set of entities to choose from: Array
(
    [uniqueVisitors] => Array
        (
            [0] => base.session
            [1] => base.request
            [2] => base.action_fact
            [3] => base.domstream
            [4] => base.click
            [5] => base.commerce_transaction_fact
            [6] => base.commerce_line_item_fact
        )

    [visits] => Array
        (
            [0] => base.session
            [1] => base.request
        )

    [bounces] => Array
        (
            [0] => base.session
        )

    [visitDuration] => Array
        (
            [0] => base.session
        )

    [pageViews] => Array
        (
            [0] => base.request
            [1] => base.session
        )

)
 
21:30:31 2018-08-24 30602 [debug_log] post-reduce set of entities to choose from: Array
(
    [1] => base.session
)
 
21:30:31 2018-08-24 30602 [debug_log] Entities summary levels: Array
(
    [base.session] => 1
)
 
21:30:31 2018-08-24 30602 [debug_log] Dimensions: Array
(
    [0] => date
)
 
21:30:31 2018-08-24 30602 [debug_log] Checking the following dimensions for relation to base.session: Array
(
    [0] => date
    [2] => siteId
)
 
21:30:31 2018-08-24 30602 [debug_log] Dimension: date is denormalized into base.session 
21:30:31 2018-08-24 30602 [debug_log] Dimension: date is related to base.session. 
21:30:31 2018-08-24 30602 [debug_log] Dimension: siteId is denormalized into base.session 
21:30:31 2018-08-24 30602 [debug_log] Dimension: siteId is related to base.session. 
21:30:31 2018-08-24 30602 [debug_log] optimal base entity is: base.session 
21:30:31 2018-08-24 30602 [debug_log] Using base.session as base entity for making result set. 
21:30:31 2018-08-24 30602 [debug_log] about to apply constraints 
21:30:31 2018-08-24 30602 [debug_log] about to apply selects 
21:30:31 2018-08-24 30602 [debug_log] Added pageViews to ChildMetrics array 
21:30:31 2018-08-24 30602 [debug_log] Added bounces to ChildMetrics array 
21:30:31 2018-08-24 30602 [debug_log] Query: SELECT COUNT(DISTINCT session.id) as visits, round(avg(session.last_req - session.timestamp)) as visitDuration, COUNT(DISTINCT session.visitor_id) as uniqueVisitors, SUM(session.num_pageviews) as pageViews, sum(CASE session.is_bounce WHEN TRUE THEN 1 ELSE 0 END) as bounces FROM owa_session as session WHERE session.yyyymmdd BETWEEN '20180817' AND '20180824' AND session.site_id = 'c6a81fda34196cc71411617c1a0c9688'    LIMIT 1  
21:30:31 2018-08-24 30602 [debug_log] Added pageViews to ChildMetrics array 
21:30:31 2018-08-24 30602 [debug_log] Added bounces to ChildMetrics array 
21:30:31 2018-08-24 30602 [debug_log] Query: SELECT session.yyyymmdd as date, COUNT(DISTINCT session.id) as visits, round(avg(session.last_req - session.timestamp)) as visitDuration, COUNT(DISTINCT session.visitor_id) as uniqueVisitors, SUM(session.num_pageviews) as pageViews, sum(CASE session.is_bounce WHEN TRUE THEN 1 ELSE 0 END) as bounces FROM owa_session as session WHERE session.yyyymmdd BETWEEN '20180817' AND '20180824' AND session.site_id = 'c6a81fda34196cc71411617c1a0c9688' GROUP BY session.yyyymmdd  ORDER BY date ASC  
21:30:32 2018-08-24 30602 [debug_log] Total session time: 1.3175208568573 
21:30:32 2018-08-24 30602 [debug_log] goodbye from OWA 
21:30:32 2018-08-24 30602 [debug_log] starting to persist cache... 
21:30:32 2018-08-24 30602 [debug_log] Dirty Objects: Array
(
    [owa_user] => Array
        (
            [c30da9265ba0a4704db9229f864c9eb7] => c30da9265ba0a4704db9229f864c9eb7
        )

)
 
21:30:32 2018-08-24 30602 [debug_log] starting to persist cache... 
21:30:32 2018-08-24 30602 [debug_log]  writing file for: owa_userc30da9265ba0a4704db9229f864c9eb7 
21:30:32 2018-08-24 30602 [debug_log] Cache File Removed: /data/57/3/5/80/3820080/user/4244390/htdocs/bestsignmonuments/owa/owa-data/caches/1/owa_user/c30da9265ba0a4704db9229f864c9eb7.php 
21:30:32 2018-08-24 30602 [debug_log] changing file permissions on cache file 
21:30:32 2018-08-24 30602 [debug_log] Cache Statistics: 
						  Total Hits: 3 (Warm/Cold: 1/2)
						  Total Miss: 2
						  Total Added to Cache: 2
						  Total Replaced: 0
						  Total Persisted: 2
						  Total Removed: 1

**Comment by wimbley** [comment]
I don't see any errors but it is still not working. Please help!

**Comment by padams** [comment]
That log file is showing debug for an API request issued by the reporting interface. That’s not the right operation to debug.

The geo ip lookups happen when a tracking request is processed (usually at the time the page/event is tracked). So you you need to attempt to track a page then look at the log file.

**Comment by wimbley** [comment]
I’ve turned off my iPhone so I’m off my LAN and using AT&T IP.

I’ve loaded my site with code embedded and looked at:

owa>owa-data>errors_errors_d396c29e499aa0e75a1fef11eb9d2dae.txt

and get the same code:

19:32:49 2018-08-25 19200 [debug_log] starting to persist cache... 
19:32:49 2018-08-25 19200 [debug_log]  writing file for: browscapc6a60a0b9b71be0278b6953c1f241f25 
19:32:49 2018-08-25 19200 [debug_log] Cache File Removed: /data/57/3/5/80/3820080/user/4244390/htdocs/bestsignmonuments/owa/owa-data/caches/1/browscap/c6a60a0b9b71be0278b6953c1f241f25.php 
19:32:49 2018-08-25 19200 [debug_log] changing file permissions on cache file 
19:32:49 2018-08-25 19200 [debug_log] Cache Statistics: 
						  Total Hits: 15 (Warm/Cold: 3/12)
						  Total Miss: 0
						  Total Added to Cache: 1
						  Total Replaced: 0
						  Total Persisted: 1
						  Total Removed: 1 

What am I doing wrong? And THANK YOU!!!!!

---
Wade
404.435.5080




On Aug 25, 2018, at 7:26 PM, padams <notifications@github.com> wrote:

That log file is showing debug for an API request issued by the reporting interface. That’s not the right operation to debug.

The geo ip lookups happen when a tracking request is processed (usually at the time the page/event is tracked). So you you need to attempt to track a page then look at the log file.

**Comment by padams** [comment]
If you are not seeing tracking request debug I the log file then the tracking request is never making it to the server. You’ll need to step backwards and see if the browser is even loading the OWA tracking library (owa.tracker) by using the browser’s network inspector.

If the browser is successfully loading the library you will see a 200 http status code on that request and then the browser will issue a second request to the server for log.php. That second request actually contains the tracking info. You’ll want inspect that request to see the http status code as well as why info is being sent.

**Comment by wimbley** [comment]
There is no owa.tracker in my browser network inspector:



---
Wade
404.435.5080




On Aug 25, 2018, at 7:53 PM, padams <notifications@github.com> wrote:

If you are not seeing tracking request debug I the log file then the tracking request is never making it to the server. You’ll need to step backwards and see if the browser is even loading the OWA tracking library (owa.tracker) by using the browser’s network inspector.

If the browser is successfully loading the library you will see a 200 http status code on that request and then the browser will issue a second request to the server for log.php. That second request actually contains the tracking info. You’ll want inspect that request to see the http status code as well as why info is being sent.

**Comment by wimbley** [comment]
../owa/modules/base/js/owa.tracker.js has permissions 644, as do all files in this directory. Do I need these to be 755?

---
Wade
404.435.5080




On Aug 25, 2018, at 7:53 PM, padams <notifications@github.com> wrote:

If you are not seeing tracking request debug I the log file then the tracking request is never making it to the server. You’ll need to step backwards and see if the browser is even loading the OWA tracking library (owa.tracker) by using the browser’s network inspector.

If the browser is successfully loading the library you will see a 200 http status code on that request and then the browser will issue a second request to the server for log.php. That second request actually contains the tracking info. You’ll want inspect that request to see the http status code as well as why info is being sent.

**Comment by padams** [comment]
If there is no request being made for the owa.tracker.js library then the tracking tag script code is not executing. You should verify that it has been added to the web page you want to track and if so, look for any JavaScript errors in the browser.

**Comment by wimbley** [comment]
I’ve found the error in the script code and have updated all pages. I now see owa.tracker code no error on all pages via browser inspector - thank you!

I still don’t see Visitor Geolocation Country, State/Region.

I’ve surfed the site through multiple browsers outside of my network. OWA Desktop Screenshot Pdf:



---
Wade
404.435.5080




On Aug 25, 2018, at 8:13 PM, padams <notifications@github.com> wrote:

If there is no request being made for the owa.tracker.js library then the tracking tag script code is not executing. You should verify that it has been added to the web page you want to track and if so, look for any JavaScript errors in the browser.

**Comment by padams** [comment]
Great. Now you can look in the logs and see why the maxmind code is or is not doing.

**Comment by wimbley** [comment]
I can not thank you enough for your help! I must admin I feel like a dumb@ss yet again.

I turned on error logging and checked:

>owa>owa-data>logs>eorros_*&%&^$$

and get this:

22:28:34 2018-08-25 21824 [debug_log]  
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveFullHost. Value returned:  
22:28:34 2018-08-25 21824 [debug_log] full_host filtered by owa_trackingEventHelpers::resolveFullHost. 
22:28:34 2018-08-25 21824 [debug_log] Filtering host 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::getHostDomain. Value passed:  
22:28:34 2018-08-25 21824 [debug_log] Registered domain is:  
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::getHostDomain. Value returned:  
22:28:34 2018-08-25 21824 [debug_log] host filtered by owa_trackingEventHelpers::getHostDomain. 
22:28:34 2018-08-25 21824 [debug_log] Filtering browser_type 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveBrowserType. Value passed:  
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveBrowserType. Value returned: Firefox 
22:28:34 2018-08-25 21824 [debug_log] browser_type filtered by owa_trackingEventHelpers::resolveBrowserType. 
22:28:34 2018-08-25 21824 [debug_log] Filtering is_browser 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::isBrowser. Value passed:  
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::isBrowser. Value returned: 1 
22:28:34 2018-08-25 21824 [debug_log] is_browser filtered by owa_trackingEventHelpers::isBrowser. 
22:28:34 2018-08-25 21824 [debug_log] Filtering browser 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveBrowserVersion. Value passed:  
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveBrowserVersion. Value returned: 61.0 
22:28:34 2018-08-25 21824 [debug_log] browser filtered by owa_trackingEventHelpers::resolveBrowserVersion. 
22:28:34 2018-08-25 21824 [debug_log] Filtering is_robot 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::isRobot. Value passed:  
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::isRobot. Value returned:  
22:28:34 2018-08-25 21824 [debug_log] is_robot filtered by owa_trackingEventHelpers::isRobot. 
22:28:34 2018-08-25 21824 [debug_log] Filtering os 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveOs. Value passed:  
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveOs. Value returned: Mac OS X 
22:28:34 2018-08-25 21824 [debug_log] os filtered by owa_trackingEventHelpers::resolveOs. 
22:28:34 2018-08-25 21824 [debug_log] Filtering is_entry_page 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveEntryPage. Value passed:  
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveEntryPage. Value returned:  
22:28:34 2018-08-25 21824 [debug_log] is_entry_page filtered by owa_trackingEventHelpers::resolveEntryPage. 
22:28:34 2018-08-25 21824 [debug_log] Filtering country 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_trackingEventHelpers::resolveCountry. Value passed:  
22:28:34 2018-08-25 21824 [debug_log] Filtering geolocation 
22:28:34 2018-08-25 21824 [debug_log] Filter: owa_maxmind::getLocation. Value passed: Array
(
    [ip_address] => 71.12.151.177, 71.12.151.177
    [city] => 
    [country] => 
    [state] => 
    [country_code] => 
    [latitude] => 
    [longitude] => 
)
 
22:28:34 2018-08-25 21824 [debug_log] Total session time: 0.42844319343567 
22:28:34 2018-08-25 21824 [debug_log] goodbye from OWA 
22:28:34 2018-08-25 21824 [debug_log] starting to persist cache... 
22:28:34 2018-08-25 21824 [debug_log] Dirty Objects: Array
(
    [browscap] => Array
        (
            [2843c9cf95284da85b49668fc0bc6bf4] => 2843c9cf95284da85b49668fc0bc6bf4
        )

)
 
22:28:34 2018-08-25 21824 [debug_log] starting to persist cache... 
22:28:34 2018-08-25 21824 [debug_log]  writing file for: browscap2843c9cf95284da85b49668fc0bc6bf4 
22:28:34 2018-08-25 21824 [debug_log] Cache File Removed: /data/57/3/5/80/3820080/user/4244390/htdocs/bestsignmonuments/owa/owa-data/caches/1/browscap/2843c9cf95284da85b49668fc0bc6bf4.php 
22:28:34 2018-08-25 21824 [debug_log] changing file permissions on cache file 
22:28:34 2018-08-25 21824 [debug_log] Cache Statistics: 
						  Total Hits: 5 (Warm/Cold: 2/3)
						  Total Miss: 0
						  Total Added to Cache: 1
						  Total Replaced: 0
						  Total Persisted: 1
						  Total Removed: 1 


which I see no problems, but I still don’t see any IP info on any screens in OWA:



---
Wade
404.435.5080




On Aug 25, 2018, at 9:56 PM, padams <notifications@github.com> wrote:

Great. Now you can look in the logs and see why the maxmind code is or is not doing.

**Comment by padams** [comment]
Strange. it appears that the maxmind module is being passed two IP addresses (that are the same) separated by a comma. Can you post the part of the log that shows the start of this tracking request and the raw event parameters received by OWA?

**Comment by padams** [comment]
I just added support for this in master. Update from master and see if that fixes your issue.

**Comment by padams** [comment]
Closing.
