### ISSUE TITLE
Mailing List Link returning "Not Found"

### ISSUE THREAD

**Issue by AJCastroChandri** [padams/Open-Web-Analytics#357]
On this link,
http://www.openwebanalytics.com/

The Mailing List links --> http://wiki.openwebanalytics.com/index.php?title=Support#Mailing_Lists
Are returning "Not found".

Is there another way I can subscribe to the list?

Thank you!

**Comment by padams** [comment]
The lists are long gone. I’ll have to remove that link. Thx.

**Comment by padams** [comment]
fixed.
