### ISSUE TITLE
Search Terms (not provided)

### ISSUE THREAD

**Issue by wimbley** [padams/Open-Web-Analytics#359]
Secondary Dimension Report shows single IP address, but search terms (not provided). Please help - and thanks for past help!

**Comment by padams** [comment]
There's nothing to help with as the term was not provided by the search engine. very common these days when users search under HTTPS.

**Comment by wimbley** [comment]
If I go to Google.com and search for "sign monuments" our site shows #2 organic:

Examples of Sign Monuments: The BEST Sign Monuments...

clicking on this shows owa.tracker-combines-min.js but doesn't show results in 'search engines' nor 'search terms'
