### ISSUE TITLE
Fully newbie admin, just changed from piwik to owa

### ISSUE THREAD

**Issue by viktor30** [padams/Open-Web-Analytics#36]
Hi fellows,

I just installed OWA, I'd like to replace piwik with it, but I'm really not familiar with it, all ready checked the OWA's wiki but could not find out plenty of things like: 

How can I see my logged visitor's ip addresses?

Could anyone recommend me some basic infos/tutorials?

**Comment by padams** [comment]
ip addresses can be seen by adding them as a secondary dimension in all reporting.
