### ISSUE TITLE
search terms

### ISSUE THREAD

**Issue by wimbley** [padams/Open-Web-Analytics#360]
If I go to Google.com and search for "sign monuments" our site shows #2 organic:

Examples of Sign Monuments: The BEST Sign Monuments...

clicking on this shows owa.tracker-combines-min.js but doesn't show results in 'search engines' nor 'search terms'

Is there a relay time for this to kick in?

**Comment by padams** [comment]
No. Although Google not obscures all search terms by no longer passing them in the referer when searching google.com under HTTPS.
