### ISSUE TITLE
Search Terms

### ISSUE THREAD

**Issue by wimbley** [padams/Open-Web-Analytics#361]
I have the site bestsignmonuments.com with OWA installed. If I go to Google.com and search for "sign monuments" our site shows #2 organic:

Examples of Sign Monuments: The BEST Sign Monuments...

clicking on this shows (web inspector) owa.tracker-combines-min.js loading without error but doesn't show results in 'search engines' nor 'search terms' in OWA

Is there a relay time for this to kick in?

**Comment by padams** [comment]
No. Although Google now obscured all search terms so OWA and other trackers will not see them.
