### ISSUE TITLE
Password reset, no mail

### ISSUE THREAD

**Issue by bzdega** [padams/Open-Web-Analytics#362]
Hi,

i just installed OWA and created a 2nd user. I tried to login with this user but failed because of wrong password. Then i requested a password reset - it says email was send - but a mail never arrives...

I wonder if there is any mail configuration?

regards
Michael

**Comment by padams** [comment]
You do not need to configure mail within OWA. It uses whatever mail/SMTP you have php setup to use.

**Comment by rogereab** [comment]
I'm also having this problem, could you please explain where this mail/SMTP setup misconfigured please as I'm struggling to find it. I assume its outside of OWA?

**Comment by padams** [comment]
the PHP mail functions relay on a valid configuration of SMTP in php.ini. PHP of course relies on the server being configured with a MTA that is configured to route mail.

**Comment by rogereab** [comment]
Can you give an example of a valid php.ini for a unix server so that I can enter my own details?

**Comment by padams** [comment]
This is not a generalized issue as far as I can tell it's a local server config issue. That said there have been fixes to some of the mailing code recently in master.

**Comment by nataprawira** [comment]
php: mail is blocked by my hosting, so i need to use PHPMailer to email.

**Comment by padams** [comment]
You can configure OWA to use PHPMailer's SMTP capabilities. Here are the config values that need to set in your owa-config.php file:

```
$this->set( 'base', 'mailer-host', 'your host');   
$this->set( 'base', 'mailer-port', 'your port');   
$this->set( 'base', 'mailer-use-smtp', true);   
$this->set( 'base', 'mailer-smtpAuth', true);   
$this->set( 'base', 'mailer-username', 'your user name');   
$this->set( 'base', 'mailer-password', 'your password');   
```

**Comment by c42759** [comment]
@padams I'm receiving `SMTP Error: Data not accepted.`. After a few researches I found out the server only doesn't allows to masking the sernder email. How can I set the sender email?

**Comment by c42759** [comment]
I found it:
```
$this->set( 'base', 'mailer-from', 'your-email@here.ext');   
```
