### ISSUE TITLE
Announce New Visitors Via E-mail

### ISSUE THREAD

**Issue by skuriver** [padams/Open-Web-Analytics#363]
I installed OWA on several servers over the years, but the Announce New Visitors Via E-mail has never worked. This last time I used Softaculous to install, prior times were manual installs, but the results are the same, the Announce New Visitors Via E-mail does not send reports.

Is there some configuration outside of OWA that I need to edit.

Thanks
Den

**Comment by n0taga1n** [comment]
Hi all, is there any definitive solution for this issue. TIA

**Comment by padams** [comment]
This is fixed in master.
