### ISSUE TITLE
OWA is not tracking and definitely not working properly.  PLEASE HELP

### ISSUE THREAD

**Issue by destinationav** [padams/Open-Web-Analytics#365]
It's not working for me either. I followed all instructions step by step but it doesn't log IP, Browser, Visits, Clicks, Time on Page, Not Set, etc.

![capture](https://user-images.githubusercontent.com/43298995/45588269-4cbd1000-b8cf-11e8-9b07-32677e16a50d.PNG)
![capture2](https://user-images.githubusercontent.com/43298995/45588270-4cbd1000-b8cf-11e8-86fb-60192f71291d.PNG)

I have reinstalled it several times to no avail. When I look in AWStats it is registering as normal and I can see all of my visitors and their IP addresses.

What can be the problem? Should I install a previous version?

**Comment by padams** [comment]
Are you using the latest code from master? Also, what version of PHP, MySQL and what OS are you running. Did you turn on debug logging and see if there are any errors being logged in the OWA log file? what about javascript errors in the browser.

It's next to impossible to tell if you have a misconfigured environment or you have run into an actual bug without this info.

Also AWSTATS uses a completely different method for data collection so it will likely never match OWA.

**Comment by destinationav** [comment]
Are you using the latest code from master? Yes
Current PHP version: 5.6.30
Current MySQL: libmysql - 5.1.73
OS: CPanel 70.0.53
I don’t see any errors when I open the console. My domain is destinationav.co if you want to see.

**Comment by destinationav** [comment]
![capture](https://user-images.githubusercontent.com/43298995/45615466-cec14c00-ba29-11e8-94c8-87b5ccc99a7c.PNG)
![capture2](https://user-images.githubusercontent.com/43298995/45615467-cec14c00-ba29-11e8-98e0-86960129b83e.PNG)
![capture3](https://user-images.githubusercontent.com/43298995/45615468-cec14c00-ba29-11e8-8285-de353fff25f3.PNG)

**Comment by padams** [comment]
Likely an old version of OWA in channel. Closing this as there's not enough info to debug,
