### ISSUE TITLE
Ignored setPageType() in JS tracker

### ISSUE THREAD

**Issue by davidebaldini** [padams/Open-Web-Analytics#366]
OWA is configured and works overall, but the JS function `setPageType()` of the following script has no effect. 

The script is inserted in the HTML `head`, and works overall, except for `setPageType()`.

OWA version:  1.6.2.

```javascript
<!-- Start Open Web Analytics Tracker -->
<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'https://example.com/analytics/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', '78901235678901234567899012345678']);  // fictitious
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);

(function() {
	var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;

	_owa.onload = function() {
		window.OWATracker.setPageType('forum');
		window.alert("loaded");
	}

	owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
	_owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
	var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>
</script>
<!-- End Open Web Analytics Code -->
```

**Comment by padams** [comment]
Are you using the latest code from master? 

Also, the page type must be set prior to the track page view cmd. Just push a new cmd to set the page view right before trackpageview.

**Comment by davidebaldini** [comment]
I also tried to push the command like this, but it didn't work either:

```javascript
var owa_baseUrl = 'https://example.com/analytics/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', '78901235678901234567899012345678']);  // fictitious
owa_cmds.push(['setPageType', 'forum']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
```

I'm using OWA 1.6.2 release, not the head.

**Comment by padams** [comment]
That’s correct. Please try with the latest code in master.

**Comment by trivedip** [comment]
I tried it with code from master still I can't track pages.
`var owa_baseUrl = 'sample.com';
    var owa_cmds = owa_cmds || [];
    owa_cmds.push(['setDebug', true]);
    owa_cmds.push(['setSiteId', 'a53dc800fb80875698ee72429b974d5f']);
    owa_cmds.push(['setPageTitle','Home']);
    owa_cmds.push(['setPageType', 'Home']);
    owa_cmds.push(['trackPageView']);
    owa_cmds.push(['trackClicks']);`

`(function () {
        var _owa = document.createElement('script');
        _owa.type = 'text/javascript';
        _owa.async = true;
        owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(
            /http:/, 'https:') : owa_baseUrl);
        _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js'; 
        var _owa_s = document.getElementsByTagName('script')[0];
        _owa_s.parentNode.insertBefore(_owa, _owa_s);
    }());`

All the pages are displayed as (not set)

**Comment by ddelago** [comment]
Hi @trivedip I have the same problem as well. "setPageTitle" does not work for me also.

```
<script type="text/javascript">
    //<![CDATA[
    var owa_baseUrl = 'http://localhost:8080/owa/';
    var owa_cmds = owa_cmds || [];
    owa_cmds.push(['setSiteId', '3f94aad20ece073c9467901f22c60b76']);
    owa_cmds.push(['setPageType', 'article']);
    owa_cmds.push(['setPageTitle', 'Chisel']);
    owa_cmds.push(['setUserName', 'Daniel']);
    owa_cmds.push(['trackPageView']);
    owa_cmds.push(['trackClicks']);
    owa_cmds.push(['trackDomStream']);

    (function() {
        var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
        owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'http:') : owa_baseUrl );
        _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
        var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
    }());
    //]]>
</script>
```

**Comment by ddelago** [comment]
Go into the DB and alter it manually in the owa_document table. I think if you've visited the site before you added the owa command it won't update the site info and remain (not set) or whatever it is.

**Comment by padams** [comment]
This is fixed in master.
