### ISSUE TITLE
What does a valid php.ini look like

### ISSUE THREAD

**Issue by rogereab** [padams/Open-Web-Analytics#367]
Can anyone be so kind as to show me what a valid php.ini setting(s) looks like so that I can enter my own details and get the mail system to work without hard coding these settings into some of the files which so far is the only way I can get the mail system to work?

It would at least mean I can apply updates in the future without having to re-enter it all again!

Thanks in advance

Roger B

**Comment by padams** [comment]
There are some fixes to mail sending in master. Reopen if those do not fix things for you.
