### ISSUE TITLE
Can't Install and No Error Logs Produced

### ISSUE THREAD

**Issue by seonwoolee** [padams/Open-Web-Analytics#370]
I'm trying to install OWA on my server. I can get past the first stage of the install script that asks for the mysql settings. 
When I go to enter the Default Site & User Information and hit continue, I get the error message 
`Database Schema Installation failed. Please check the error log file for more details`

I have set `OWA_ERROR_HANDLER` to development and `OWA_LOG_PHP_ERRORS` to true. However, there are no log files in `owa-data/logs` and there are no errors in `/var/log/nginx/error.log`.

How can I see the error messages to diagnose my issue?

**Comment by seonwoolee** [comment]
I got it to produce logs. Still can't install, but I'll open a separate issue

**Comment by DeeeeLAN** [comment]
how did you get logs to show up? I have the same issue.
