### ISSUE TITLE
Dashboard Display Broken

### ISSUE THREAD

**Issue by seonwoolee** [padams/Open-Web-Analytics#373]
I just installed OWA, but the site doesn't render correctly. I've attached a screenshot ![](https://i.imgur.com/bYhcBqQ.png)

This seems related to #175 but I'm not sure. There's no errors in `/var/log/nginx/error.log` concerning a permission error in accessing css. Furthermore, I can directly access `https://analytics.seonwoolee.com/modules/base/css/owa.css?version=1.6.2` just fine

**Comment by padams** [comment]
Closing as there's not enough info to debug this.
