### ISSUE TITLE
Infinite redirects?

### ISSUE THREAD

**Issue by brienb** [padams/Open-Web-Analytics#374]
Hello,

I installed OWA on a new Debian 9 web server. I have some strict Apache2 web server settings, which I'm not sure may be interfering with the installation, but I see no javascript errors.

The problem is that whenever I add the OWA javascript code to any page, the page keeps trying to redirect repeatedly until the server times out. I have to take the code of the page, then clear my browser's cache. 

This is very strange? 

I have it on another server and it works fine. I have object cache off. All of my settings are fine, as far as I know.

**Comment by padams** [comment]
Not sure. is it running under https? Check your .htaccess rules maybe.
