### ISSUE TITLE
Can anyone explain the event tacing Javascript

### ISSUE THREAD

**Issue by edwardt12** [padams/Open-Web-Analytics#375]
I cant fond any explanations.
I want to track specific events using JavaScript probably.
e.g. when a user clicks my button to see discounts I want to trap an event called discounts.
What JavaScript is needed? Where do I put that JavaScript?
All I can see is a general JavaScript  file like GA that captures every click
I see reference to custom events and even code snippets, but it doesn't tell me how or where this code would be deployed
Thanks in advance.

**Comment by edwardt12** [comment]
What I have found is:
OWATracker.trackAction('Cooking', 'Recipe Print',  'Best Chicken Parmesan Recipe', 10);
This I believe is close to what I need.  The action name is 'Recipe Print'
In my case it could be:
OWATracker.trackAction('deciding', 'Compare discounts',  'etc', 10);

What I dont understand is:
where will this line of Javascript be placed:
How will it know that my user is clicking the "Discounts button"?
Do I need to use a specific dom naming method?
Do need to attach and event to the button I am tracking?
Anyone?

**Comment by ddelago** [comment]
I've added it to my button HTML element using the onclick event listener: 
`onclick="OWATracker.trackAction('deciding', 'Compare discounts', 'etc', 10)"`

So whenever the button is clicked the action is logged.

**Comment by padams** [comment]
See https://github.com/padams/Open-Web-Analytics/wiki/Action-Tracking
