### ISSUE TITLE
Entry Page Path blank for homepage

### ISSUE THREAD

**Issue by davetbo** [padams/Open-Web-Analytics#378]
Hello,

I'm totally new to OWA and I have to say it's very impressive. I'm very optimistic that it will work well for me.  However, I'm having a hard time figuring out some of its quirks.

Specifically, I'm trying to find the heat maps for my homepage.  If I go to top pages, then click the "Page Path" for one of the pages, I can see the Heatmap Overlay link near the bottom.  However, I've noticed that 2 rows of the list of pages have no link under "Page Path" and therefore cannot be visited to check out the Heatmap link.

Any idea why that is?  Here's a screenshot: 
![image](https://user-images.githubusercontent.com/82604/49768072-da6e8880-fc8f-11e8-91e0-0954c3dbeed9.png)

I appreciate anyone's advice.  

Thanks!
Dave

**Comment by padams** [comment]
I believe this is fixed in master.

**Comment by BloodyIron** [comment]
> I believe this is fixed in master.

Fresh install of 1.6.4 and I see this bug too. I don't see any commits for it being fixed, how should we address this on our end? D:

**Comment by padams** [comment]
Did you drop the tables In the DB? Also you need to use the latest code in master not 1.6.4.

**Comment by BloodyIron** [comment]
I installed fresh with 1.6.4 yesterday, the DB was completely empty. I just checked the commits since 1.6.4 and I don't see anything that is related to this issue so... I am confused.

**Comment by padams** [comment]
Pretty sure there is a post 1.6.4 change in master that fixes this. Please try that code with a clean DB.

**Comment by BloodyIron** [comment]
So I have to drop all my content then? :(

**Comment by padams** [comment]
No. You can just delete the row for that page from the owa_document table and then track the page again.
