### ISSUE TITLE
Adding new users

### ISSUE THREAD

**Issue by andhof-mt** [padams/Open-Web-Analytics#38]
Is it possible to add multiple users?

And perhaps have each user only access the stats of a certain website?

**Comment by purecanuck** [comment]
Any updates on this? Is it possible to limit user access to specific websites instead of all of them?

**Comment by padams** [comment]
You can do this via the user profile screen in the admin interface. It allows you to choose the sites that any specific OWA user can access.

**Comment by purecanuck** [comment]
On my User Profile screen, I only see: User Name, API Key, Real Name, and Email Address fields. I'm logged in as admin and looking at index.php?owa_do=base.usersProfile&owa_edit=1&owa_user_id=admin

**Comment by padams** [comment]
That's because you are an admin. Create a new user and the controls will appear.

**Comment by purecanuck** [comment]
I've tried with Viewer and Analyst roles to no avail. 
![alanexample](https://cloud.githubusercontent.com/assets/10412496/6139801/c9d222c4-b144-11e4-870e-57c3f87bfade.png)

**Comment by padams** [comment]
Ah, sorry I meant the site profile not the user profile. Create a new user then go to the site profile you want to grant access to and add the user to the list.

**Comment by purecanuck** [comment]
I do not see anywhere to add/remove/edit the user list for a given website. Related, how do I default to only allowing a user (alan) access to only one website as opposed to defaulting to all of them?

![screen shot 2015-02-10 at 5 06 22 pm](https://cloud.githubusercontent.com/assets/10412496/6139993/37d9011e-b147-11e4-856a-1dd4c48bae0b.png)

**Comment by padams** [comment]
The GUI is a bit tricky here. You have to set the user access site by site. Just multi select the users you want to have access and hit save. Only the "viewers" hi lighted will have access. Admins can access everything.

**Comment by brianshophero** [comment]
When I hit "save user" I get a message that the page can't handle the request and a http error 500 message. Is anyone else having this problem?

**Comment by JoshWho** [comment]
So how can we enable User registration for others to signup on there own?
