### ISSUE TITLE
Visitor Map

### ISSUE THREAD

**Issue by pointaction** [padams/Open-Web-Analytics#382]
Is there plans to get any visitor map like you had in the past with Google API?

It would be nice to have this even it is just as a addon to install.

Thank you

**Comment by Maaiins** [comment]
I created a small module to display the count of visitors on a map, it´s very simple and based on latitude/longitude. So when no latitude or longitude is given there will be no data.

In future I will add maybe features with ecommerce reportings, but for now i've got no need for this.

https://github.com/Maaiins/Open-Web-Analytics-VisitorMap

![image](https://user-images.githubusercontent.com/7676540/75928435-ad972a00-5e6e-11ea-8a50-7bdaff0241ad.png)

**Comment by padams** [comment]
This is great.

**Comment by padams** [comment]
Closing this out.
