### ISSUE TITLE
Add site via API

### ISSUE THREAD

**Issue by pauladams24** [padams/Open-Web-Analytics#383]
I was wondering if there was a way to add a website to OWA though the API, or if not, if there is any easy, automatic way to do this from an external source.

Also, is it possible to create new users via the API (this is less of a priority, but would be useful to know if it is possible).

Thanks in advance for any reply.

Paul Adams

**Comment by padams** [comment]
https://github.com/padams/Open-Web-Analytics/wiki/Command-Line-Interface-%28CLI%29
