### ISSUE TITLE
Maxmind fails "PHP Fatal error:  Cannot declare class MaxMind\Db\Reader, because the name is already in use in /Users/davetbo/Documents/MAMP_Sites/uhills.dev/wp-content/plugins/owa/modules/maxmind_geoip/includes/MaxMind-DB-Reader-php-1.0.3/src/MaxMind/Db/Reader.php on line 14"

### ISSUE THREAD

**Issue by davetbo** [padams/Open-Web-Analytics#385]
Hello,

I am following the instructions on this page:
https://github.com/padams/Open-Web-Analytics/wiki/Maxmind-GeoIP-Module

As soon as I activate the MaxMind module in the OWA Modules config, I get this error:
PHP Fatal error:  Cannot declare class MaxMind\Db\Reader, because the name is already in use in /Users/davetbo/Documents/MAMP_Sites/uhills.dev/wp-content/plugins/owa/modules/maxmind_geoip/includes/MaxMind-DB-Reader-php-1.0.3/src/MaxMind/Db/Reader.php on line 14

It looks like maybe that class is already being loaded by WordFence. If I disable WordFence it stops crashing with this error.  Could you write your code to check if that class exists before instantiating it?

Best,
Dave

**Comment by davetbo** [comment]
I created a patch for you that appears to help avoid this error. Basically it just checks if class_exists for each of the maxmind requires in your maxmind.php file.
[maxmind.php.patch.txt](https://github.com/padams/Open-Web-Analytics/files/2911757/maxmind.php.patch.txt)

**Comment by padams** [comment]
Please submit this as a pull request here on GitHub.

**Comment by padams** [comment]
Closing as a fix is in master.
