### ISSUE TITLE
Undefined variable notice

### ISSUE THREAD

**Issue by mrabinovsky** [padams/Open-Web-Analytics#39]
Hi I just set up OWA according to the wiki instructions, and I wasn't sure where to put the php code it gives you so I simply put it in my head functions. Basically it is on every single page on my website that has a header. I hope this was right because it didn't really specify if it has to be on every page you want to track or just someplace on the site. Anyways now when I go to any page on my site I get this notice:

Notice: Undefined variable: page_parse in D:\xampp\htdocs\owa\modules\base\processEvent.php on line 297

 it was something different before it just magically changed to that, and if I actually type in the base URL I don't have that error (though if I hit the home link which takes you to the exact same page it does).

I hope someone can help me, because I think this tool is really cool. Thanks.

**Comment by padams** [comment]
This is now fixed in master.
