### ISSUE TITLE
New Visitors stays at "0" 

### ISSUE THREAD

**Issue by criterion9** [padams/Open-Web-Analytics#391]
It appears that for all the sites I am tracking the New Visitor count never increments. I can view in the Visitors Age report that there should be many New Visitors by adding the Repeat Visitor as a secondary metric when it will clearly show there are far more New Visitors than Repeat Visitors. It will split out the Repeat Visitor counts from everything else but the New Visitor metric is always 0 for some reason. Has anyone else had this issue and if so how did they resolve it?

![2019-03-16 18_10_50-Open Web Analytics - Visitor Age](https://user-images.githubusercontent.com/23464351/54482248-f6497380-4816-11e9-86d6-d40666d83b7e.png)
![2019-03-16 18_11_18-Open Web Analytics - Visitor Age](https://user-images.githubusercontent.com/23464351/54482250-fb0e2780-4816-11e9-8cda-f3c18bfbd3ff.png)

**Comment by padams** [comment]
I'm assuming this got resolved as I'm not seeing it in my install or reported elsewhere. re-open if need be.

**Comment by padams** [comment]
This is actually an issue caused by bad input validation of boolean values sent by the javascript tracker.

**Comment by padams** [comment]
Fixed by properly typing boolean values that get sent by the javascript tracker as strings.
