### ISSUE TITLE
Installing OWA in a "RACHEL" server (offline contents)

### ISSUE THREAD

**Issue by coleag** [padams/Open-Web-Analytics#392]
Hi guys,

We are deploying "RACHEL" installations in rural communities in Mexico, specifically the Yucatan area.

RACHEL is a portable plug-and-play server which stores educational websites and makes that content available over any local (offline) wireless connection. It essentially is a Ubuntu distribution configured to serve offline digital contents to users:  https://worldpossible.org/rachel

I can see instructions to install OWA on WordPress & MediaWiki, but are there instructions to install OWA in any other server configuration? Any guidance would be great.

Thanks,
Camilo Olea
Co-founder
www.kaanbal.org

**Comment by padams** [comment]
Not sure I follow but please see the installation instructions for a standalone install.
