### ISSUE TITLE
Change admin username of "admin"

### ISSUE THREAD

**Issue by trogladyte** [padams/Open-Web-Analytics#393]
I just installed OWA and it's all running, but the admin UN is "admin" which is pretty weak. I want to change it, but it's not editable in the profile edit.

Can I do this or do I need to do a reinstall?

**Comment by vinnief** [comment]
i couldnt do it on install, and you cannot add other users either. pity. no point in having a username f it is always the same.

**Comment by bennet-esyoil** [comment]
maybe if you change it in the database directly, the corresponding table is "owa_user".

**Comment by joho1968** [comment]
One more input field in the installer shouldn't be all that hard.

**Comment by bennet-esyoil** [comment]
There has not been any update with a new feature in the near past, I would say that development is pretty dead by now, most releases include bug-fixes and/or backwards-compatibility changes. Introducing a new field is probably not realy worth it.

**Comment by joho1968** [comment]
Would it be worth it to start pulling / pushing / merging? It'd be a shame to fork just to add bug fixes.

**Comment by bennet-esyoil** [comment]
You need to fork it anyways for PRs, but go ahead if you want. I'm working on a fix for something myself and I hope it get's accepted.

**Comment by padams** [comment]
Closing as a fix is in master now.
