### ISSUE TITLE
OWA 1.5.2 under MediaWiki 1.18.1 does not log user_name of authenticated users?

### ISSUE THREAD

**Issue by willend** [padams/Open-Web-Analytics#4]
Hi there,

I am using an OWA 1.5.2 installation under MediaWiki 1.18.1 which logs all access fine - but does not store logged-in mediawiki usernames (or emails), the owa database simply has NULL values in all rows of the relevant table...

I have had a look at all settings on the OWA side (did not configure the system myself, the sysadmin did) and all looks OK. One thing makes me wonder though; He has configured MediaWiki to use PostgreSQL and OWA to use MySQL - different databases ofcourse and different database users...  Is there a hidden requirement for a common database level access for the two codes?

Any other hints or ideas wrt. what could be wrong?

Best,
Peter

**Comment by padams** [comment]
That error is now fixed in master. 

Sadly our trac db got corrupted so we lost history and moved here.

I'm not sure why the user name and email is not being recorded. You would have to debug the mediawiki tracking request to see if it's even being passed.
