### ISSUE TITLE
Domain Aliases

### ISSUE THREAD

**Issue by atos-phillips** [padams/Open-Web-Analytics#403]
Hi 

We're doing some testing using v.1.6.2 but can't seem to get a domain alias to work.

We have 2 domains that resolve to the same backend application. One domain is specified as the main site domain, which works great, but the other domain - specified in the domain aliases - doesn't get tracked at all. 

The tracking code shows up in the page source code for the second domain but no tracking info is getting recorded in the owa database/reporting dashboard. We've tried specifying the format as www.domain.com, also tried prefixing with htttp and https protocols, using wildcards...everything we could think of but without success. The setting appears in the owa_site table, so it is getting saved to the database correctly. Have also checked the error log which looks fine.

Are we missing something?

**Comment by padams** [comment]
OWA knows nothing about domain aliases. It's very explicit. One must set up two sites in OWA and then have logic that invokes the tracker with whatever site_id that you want record stats for.
