### ISSUE TITLE
call trackPageView a second time on a page by JS

### ISSUE THREAD

**Issue by maynard321** [padams/Open-Web-Analytics#404]
Is it possible to register a second (or 3rd...) page view programatically by Javascript?

Scenario: the html page is controlled by javascript / ajax and shows various "pages", changing the browser URL without reloading the actual html page. We want to register each new page as a page view, rather than an event.

GA allows this with, eg:
```javascript
    gtag('config', google_analytics_id, {'page_path' : url});
```

I've tried something similar, but it seems not to work:
```javascript
    owa_cmds.push(['setSiteId', my-site-id]);
    owa_cmds.push(['trackPageView']);
```

**Comment by padams** [comment]
See #318

**Comment by padams** [comment]
Yes. If the URL of the page has changed just call trackPageView again.
