### ISSUE TITLE
Can OWA be used to track chrome extensions?

### ISSUE THREAD

**Issue by jasonday** [padams/Open-Web-Analytics#405]
chrome extensions are essentially web pages, so that part should be easy to track, however does the site url/domain when adding a new instance within OWA have bearing? or should the domain be along the lines of: 
`chrome-extension://gdocgfhmbfbbbmhnhmmejncjdcbjkhfc/options.html`

**Comment by padams** [comment]
If you can invoke Javascript you can use OWA to track any kind of event.
