### ISSUE TITLE
Suspected Malware - Newbe Question

### ISSUE THREAD

**Issue by RetroWill** [padams/Open-Web-Analytics#407]
Hi

I installed this for the first time on Friday evening.  I have had a number of messages from CPanel saying that there is malware detected in the 'browscap' folder Generic:PHP/Backdoor.A .  When I browse the folder there are a lot of php files with long obscure names e.g. af26a291b02611b619f29585bbb19ac9.php .  If I open any of the files it looks like there is encrypted code there.

Are these files generated by the tool itself and are false positives or is there an issue?  Any advice appreciated.

Thanks
Will

**Comment by padams** [comment]
Are you talking about the owa-data/caches/1/browscap folder?? If so those are cache files not malware.

All the php files in the cache folders are generated by the software. You can turn off object caching in the config file if something is complaining about those files.

**Comment by RetroWill** [comment]
Interesting that CPanel is flagging them as Malware and quarantining them!  I have had a few more alerts since posting this.  Thanks for putting my mind at rest though.

**Comment by padams** [comment]
Not sure there is any issue here. Re-open if there is.
