### ISSUE TITLE
Can OWA track time between events?

### ISSUE THREAD

**Issue by wbcostigan** [padams/Open-Web-Analytics#413]
For example, can I find average time from when a user clicks a specific page element, until they click a different page element? 

I have a button that will 'show' a hidden panel, and two elements on that panel that close the panel (the 'x' control and a 'Close' button. I want to know how long users are looking at my panel before they close it.

Also on the panel is another button that navigates them to a different section. Can I see how long between opening my panel and clicking the 'navigate-to-xyz' element?

**Comment by padams** [comment]
Yes it's in the click stream report for an individual visit. Click on the visit in the visit list on the main dashboard or a visit report.
