### ISSUE TITLE
Use of undefined constant OWA_ERROR_HANDLER

### ISSUE THREAD

**Issue by joho1968** [padams/Open-Web-Analytics#415]
PHP 7.2 (FPM), Nginx, Ubuntu 18.04.LTS. Stand-alone.

The constant OWA_ERROR_HANDLER *is* defined (as 'production'). The URL is /index.php?owa_do=base.sitesProfile, after filling in all the fields for a new site to monitor and then clicked "Save settings" under "Site settings".

If I instead click "Save Profile" higher up, it seems to work. If I then go back and alter some "Site settings", I can successfully click "Save settings" without any errors.

[21-Aug-2019 19:48:51 Europe/Stockholm] PHP Warning:  Use of undefined constant OWA_ERROR_HANDLER - assumed 'OWA_ERROR_HANDLER' (this will throw an Error in a future version of PHP) in /var/www/OWA/public_html/modules/base/templates/config_dom.tpl on line 15
[21-Aug-2019 19:49:45 Europe/Stockholm] PHP Fatal error:  Uncaught Exception: No value passed. in /var/www/OWA/public_html/owa_entity.php:351
Stack trace:
#0 /var/www/OWA/public_html/plugins/validations/entityExists.php(41): owa_entity->getByColumn('site_id', NULL)
#1 /var/www/OWA/public_html/modules/base/classes/validator.php(104): owa_entityExistsValidation->validate()
#2 /var/www/OWA/public_html/owa_controller.php(204): owa_validator->doValidations()
#3 /var/www/OWA/public_html/owa_coreAPI.php(791): owa_controller->doAction()
#4 /var/www/OWA/public_html/owa_coreAPI.php(1213): owa_coreAPI::performAction('base.sitesEditS...', Array)
#5 /var/www/OWA/public_html/owa_caller.php(222): owa_coreAPI::handleRequest(NULL, 'base.sitesEditS...')
#6 /var/www/OWA/public_html/owa_caller.php(164): owa_caller->handleRequest()
#7 /var/www/OWA/public_html/index.php(46): owa_caller->handleRequestFromUrl()
#8 {main}
  thrown in /var/www/OWA/public_html/owa_entity.php on line 351

**Comment by arnisjuraga** [comment]
#415

**Comment by padams** [comment]
Fixed with #419
