### ISSUE TITLE
Template content being 'escaped' showing HTML entities

### ISSUE THREAD

**Issue by joho1968** [padams/Open-Web-Analytics#418]
Just to force an error, I attempted to create an already existing user. The error message itself is correct, but the output is escaped with what looks like htmlentities (). Doesn't that, sort of, defeat the purpose of having templates that are allowed to contain HTML?

I have attached a screenshot.
![image](https://user-images.githubusercontent.com/3135227/63469410-703af400-c46a-11e9-8e84-7f859ad500fa.png)

**Comment by padams** [comment]
Yep. That's a bug. Happy look at a patch if you have one.

**Comment by joho1968** [comment]
Yeh. I just need to wrap my head around this framework / code and there are only 24h in a day (working on that too).

**Comment by padams** [comment]
closing this out a the fix is in master now.
