### ISSUE TITLE
OWA on a secure site?

### ISSUE THREAD

**Issue by andrew5555** [padams/Open-Web-Analytics#42]
We recently configured our whole site to function as a secure site (using ssl certificate). We have a snippet in our .htaccess file which forces all pages on site to switch to ssl. This has seemed to break OWA. You can see here even on the login page: https://www.lifeleap.org/owa/

Is there a method of allowing OWA to operate on a secure site? Thanks for any suggestions.

**Comment by alexlehm** [comment]
I am running owa on my site with cloudflare ssl, which looks like it is working properly.
The tag accounts for http and https and everything else should work when the server supports ssl

**Comment by andrew5555** [comment]
alexlehm - thanks for the reply. Hmm, maybe it's something else. I'm have no custom coding in script and I have the most recent version, so it's not making sense to me.

**Comment by andrew5555** [comment]
Got it - I had to change "OWA_PUBLIC_URL" in the config file to https. 

Hope this helps someone in the future.
