### ISSUE TITLE
Memory exhausted Error

### ISSUE THREAD

**Issue by embaseadmin** [padams/Open-Web-Analytics#421]
I am getting below error while installing owa. i even tried the memory size up to 512 MB in php.ini file. 
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /opt/lampp/htdocs/owa/plugins/db/owa_db_mysql.php on line 154

**Comment by padams** [comment]
You need to provide a lot more information than that if you want anyone to help point you in the right direction. First of all:

- Are you running OWA as standalone PHP app or as part of another app?
- Are you running the code in master?
- What version of PHP?
- How are you invoking OWA? From PHP code or using the JS tracker?
- Have you turned on development logging and looked at the errors log file?
