### ISSUE TITLE
1.6.2 install issues

### ISSUE THREAD

**Issue by grifgr10** [padams/Open-Web-Analytics#423]
I am attempting to install 1.6.2 on a fresh instance.  I have created the table, user and ensured permissions for that user seem good.  But continue to get access denied for user.  

What permissions are needed by this user for original setup?  I have even tried full DBA permissions.

![image](https://user-images.githubusercontent.com/1914348/65185009-b0bf6a80-da34-11e9-8a5e-e097cf028405.png)

[Wed Sep 18 16:41:05.933334 2019] [php7:warn] [pid 2671] [client 10.100.62.81:56475] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user 'owa'@'10.1.0.6' (using password: YES) in /data/owa/plugins/db/owa_db_mysql.php on line 111, referer: https://domain.com/install.php?owa_action=base.installCheckEnv

[Wed Sep 18 16:41:05.933391 2019] [php7:warn] [pid 2671] [client 10.100.62.81:56475] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, bool given in /data/owa/plugins/db/owa_db_mysql.php on line 117, referer: https://domain.com/install.php?owa_action=base.installCheckEnv

**Comment by criterion9** [comment]
Are you putting the OWA codes and database on the same machine? If so, your from address isn't correct based on the screenshot. If not, I would check to see if you are able to connect from the command line from the web server where you are putting the owa code.

**Comment by georgedorn** [comment]
I'm having the same issue.  Going to /owa/install.php and putting in the user/pass for mysql works for the followup check (that followup check fails with a white screen after running out of memory if mysql auth fails) but then immediately afterwards the install reports that DB Schema Creation has failed.

This is, notably, using PHP 7.3 on Ubuntu 16.04 and MariaDB.  I get a ton of php warnings, too, such as:

```
AH01071: Got error 'PHP message: PHP Warning:  mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, bool given in /var/www/html/owa/plugins/db/owa_db_mysql.php on line 220
PHP message: PHP Warning:  Use of undefined constant OWA_ERROR_HANDLER - assumed 'OWA_ERROR_HANDLER' (this will throw an Error in a future version of PHP) in /var/www/html/owa/modules/base/templates/config_dom.tpl on line 15', referer: https://www.example.com/owa/install.php?owa_site_id=&owa_do=base.installDefaultsEntry&
```

**Comment by getflourish** [comment]
Also had some issues with the installation using a fresh database and PHP 7.3. When I disabled “force SSL” for the database it worked.

**Comment by padams** [comment]
Try the latest code in master. It should fix this. Re-open if it doesn't.
