### ISSUE TITLE
Multiple Web Site Support - track any number of web sites and view statistics in aggregate or by site

### ISSUE THREAD

**Issue by mahadevans87** [padams/Open-Web-Analytics#425]
The features wiki states - 

> Multiple Web Site Support - track any number of web sites and view statistics in aggregate or by site

I am specifically interested in how we can achieve this using the OWA platform. Can someone help me with how to view the statistics of multiple websites together?

**Comment by padams** [comment]
It's a ton of data with a lot of limitations so you would have to write custom report to do this or use the API.
