### ISSUE TITLE
Heatmap overlay not working in OWA

### ISSUE THREAD

**Issue by elena139** [padams/Open-Web-Analytics#426]
Hi,

I read previous comments but heatmap overlay in OWA simply is not working for me. I tried Firefox as a browser still no success. I can't even press the 'play' button. Is there any specific code that needs to be added inside the tracking code maybe? If yes what would this code should be?
I enabled domstream in Settings again not sure if that is working either. Pressed on on live view again same.
Thanks in advance

**Comment by BrainRift** [comment]
I am on Chrome and it is working fine for me.  Sometimes a little patience is required for it to load on the screen.  I am using standard javascript.  I wish I had more information.

**Comment by elena139** [comment]
Thank you for replying. I already have Chrome but it's not working on any browser. I can't even press the 'play' simply not working. I have a simple WordPress site and this is the code I've added on my site in the head

<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'http://www.tmysite.com/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', '4e59...myapi']);

owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);

(function() {
    var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
    owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
    _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
    var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>

</script>

Also when I inspect element on play button is shows unexpected token error "<" and "&" and inside my code I don't have any error (validated the code too).

Final question to open Heatmap overlay I need to go to visit details -> visit clickstream but interesting thing is that I can only open subpages and not the main page. Any thoughts on this?

Many thanks

**Comment by elena139** [comment]
This is the code

<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'http://www.mysite.com/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', '4e59...myapi]);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);

(function() {
    var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
    owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
    _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
    var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>

**Comment by padams** [comment]
Works for me too. If you can provide more info or errors from the OWA log file and browser console please reopen.
