### ISSUE TITLE
install.php is still partially operational after the configuration is finished

### ISSUE THREAD

**Issue by alexlehm** [padams/Open-Web-Analytics#43]
The install page is still working even though the installation is already finished. It would be better to have the complete script disabled if the configuration is finished and deny the script.
The operation is partially disabled (a new user can be entered but is not created), but it is possible to create new tracking sites, which like doesn't cause any harm, still it would be better if that is limited to the admin users.
As an example, take a look at the page on the demo system at http://demo.openwebanalytics.com/owa/install.php

**Comment by padams** [comment]
This was a regression. see: https://github.com/padams/Open-Web-Analytics/commit/523a87688053abaa81f6b8f1a9e5744774e10d41
 and try a reinstall.
