### ISSUE TITLE
OWL 1.6.2 does not track any visits

### ISSUE THREAD

**Issue by phulc310** [padams/Open-Web-Analytics#431]
Good evening everybody,

I have three websites running two of which are based on bludit. 
On a different domain I aim to collect the statistics about these websites. I have pasted the tracking codes into the templates php and/or javascript. But the dashboard does not show any reaction. 
![OWA](https://user-images.githubusercontent.com/40473941/71022456-cfe79a00-2100-11ea-9d8a-ecbfcc7da285.jpg)

Would you mind giving me a hint? What goes wrong?

**Comment by sysfu** [comment]
Visit one of the problem sites with your browser and open the developer tools to find clues.

I did this on the 181-berlin.de site and noticed the following error:

`(index):218 GET https://owa.fasshauer.org/modules/base/js/owa.tracker-combined-min.js net::ERR_CERT_COMMON_NAME_INVALID`

For https://architektendepping.de/ I found the following errors

`owa.tracker-combined-min.js:1 Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
css:1 Failed to load resource: the server responded with a status of 400 ()`

**Comment by padams** [comment]
Not reproducible. please reopen with a specific bug.

**Comment by phulc310** [comment]
Danke. Das SSL-Zertifikat war's.
Grüße ...
