### ISSUE TITLE
Some notice and warning on ubuntu 18.04 php7.3

### ISSUE THREAD

**Issue by alebalweb** [padams/Open-Web-Analytics#432]
On installation
_Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /var/www/owa/owa_lib.php on line 476

Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /var/www/owa/owa_lib.php on line 476

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, bool given in /var/www/owa/plugins/db/owa_db_mysql.php on line 220_

On index page (header)
_Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /var/www/owa/owa_lib.php on line 476_

**Comment by padams** [comment]
fixed in master.
