### ISSUE TITLE
WordPress plugin installation stuck at "Some Modules need to create or update their database tables"

### ISSUE THREAD

**Issue by sysfu** [padams/Open-Web-Analytics#433]
Fresh install of OWA 1.6.2 plugin on a current version WordPress site gets stuck at the "Some Modules need to create or update their database tables" message when accessing the plugin.

This is on a cpanel system where shell access is not permitted. I tried deactivating the OWA plugin, dropping all the owa_ prefix tables via PHPadmin, and then reactivating the plugin, but the same problem occurs.

Why do database tables need an update after immediately after being created by the plugin?

Environment:

Hosting Package | Small Business
Server Name | ds26
cPanel Version | 84.0 (build 18)
Apache Version | 2.4.41
PHP Version | 7.3.12
MySQL Version | 10.3.21-MariaDB
Architecture | x86_64
Operating System | linux
Shared IP Address | 66.160.181.53
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.16.3
Kernel Version | 3.10.0-1062.7.1.el7.x86_64

**Comment by sysfu** [comment]
I had the hosting provider run the php command but it did not appear to have any effect, see video.

![OWA-db-update-error](https://user-images.githubusercontent.com/829699/71921244-56f6c380-313d-11ea-856c-d47f25f6fc4b.gif)

Here is the hosting provider's response.

```
Presumably, it was the cli.php located in
/home/username/public_html/wp-content/plugins/owa/cli.php

I ran that and it produced no output:

root@cpanelhost [~/public_html/wp-content/plugins/owa]# php cli.php
cmd=update
```

**Comment by padams** [comment]
Are you using the code in master?

Have you turned on debugging and looked in the errors log file?

**Comment by sysfu** [comment]
I was using the 1.6.2 release.

Uploading the latest code from master resolved the issue, thank you.
