### ISSUE TITLE
After install can can still access to install.php page

### ISSUE THREAD

**Issue by pinq-** [padams/Open-Web-Analytics#434]
after I installed OWA and it looked like it works fine, I can sitll access to owa/install.php and add random pages to follow list. Actually I can access with browser to any file in owa folder. I removed owa folder and reinstalled it, but didn't help. Any ideas why is it so.

**Comment by sysfu** [comment]
I am unable to reproduce the issue with the lastest version of OWA from master.

**Comment by pinq-** [comment]
Is it possible to manually to block access or set the install ready?

**Comment by padams** [comment]
it should do that automatically if the install was successful.
