### ISSUE TITLE
OW for WP: ' gets transformed to &#039; in J-Script

### ISSUE THREAD

**Issue by znrR** [padams/Open-Web-Analytics#435]
Hey Peter and others, firstly thanks for that great piece of software. We are so happy to have replaced Google Analytics with it to no longer provide our visitors data to them. Also really cool that it is GDPR compliant, thanks for that!

I tried to track down the following issue on my own, but couldn't figure out whats happening with my limited skills and also searched all around but couldn't find others to whom its happening too:

The built in feature of the Wordpress Plugin to insert the Tracker J-Script transforms (?) parts of the J-Script wrongly. Instead of ' it uses  `&#039;` but not everywhere, 'just' for the pageview, click and indom commands. The other ' chars are just as they should be, but with that `&#039;` chars the tracking is not working.

```
var owa_baseUrl = 'https://www.XXXXXXXX.de/wp-content/plugins/owa/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setApiEndpoint', 'https://www.XXXX.de/index.php?owa_apiAction']);
owa_cmds.push(['setSiteId', 'XXXXXX']);
owa_cmds.push( ['setPageProperties', {"page_url":"https:\/\/www.XXXXXX.de\/","guid":"XXXXXX","timestamp":1578447488,"page_type":"Page","page_title":"","site_id":"XXXXX"}] );owa_cmds.push([&#039;trackPageView&#039;]);
owa_cmds.push([&#039;trackClicks&#039;]);
owa_cmds.push([&#039;trackDomStream&#039;]);

```

We are using PHP 7.2, latest WP and latest version of OWA. Maybe someone of you folks can point me in the right direction of whats happening or even has a solution for it? For the time being i manually inserted a second version of the j-script which works for now but is not very elegant to have that exceptions online...

Best from Berlin, Stefan

**Comment by padams** [comment]
try the commit i just added. It contains a renovation of the WP plugin that might fix your issue.

**Comment by znrR** [comment]
Hi Peter, the j-script now works like a charm!  👍🏼👍🏼 thanks for the fast response & fix!

On another note I recognised that the page type gets now statically(?) set to `owa_cmds.push(['setPageType', 'Page' ]); ` but this information does currently not arrive in the admin UI.

**Comment by padams** [comment]
OWA doesn’t update the page/document dimension. Delete the row for it in the owa_document table and retrack.

**Comment by padams** [comment]
Closing.

**Comment by znrR** [comment]
Same thing as in https://github.com/padams/Open-Web-Analytics/issues/436 - deleting the row is not sufficient since it gets not re-created. Manually added Page to all Pages and that works for now.
