### ISSUE TITLE
OW  for WP: Index.php (WP Startpage) is not showing up with / in Clickstream

### ISSUE THREAD

**Issue by znrR** [padams/Open-Web-Analytics#436]
Hey guys, just a minor thingy thats strange and seams to be differently on the  demo site to ours: In the clickstream our Homepage (or / or index.php - the page that is set in WP as startpage) gets displayed without any URL - the demo installation shows a / for that. In the settings interface i have not entered index.php in "default page", bit it having it in there or not has no effect on that.

Any clue how i can get the / in there? please see attached pic and thanks for any hints!

Best from Berlin, Stefan

<img width="513" alt="Screenshot 2020-01-08 at 03 11 45" src="https://user-images.githubusercontent.com/59607366/71944725-04f98080-31c5-11ea-94f9-b770eee22922.png">

**Comment by padams** [comment]
Good catch. try the fix i just pushed for this.

**Comment by znrR** [comment]
Hi Peter, I replaced all 3 files that you updated yesterday but the / still  does not appear for the startpage in clickstream for new visits... is there anything other I need to do to than replacing the 3 files to make your fix work? Thanks and best from Berlin! if theres a param which is not ignored, they show up.. Its not a big deal but would be nice to have the /

Best, Stefan
PS: If you want more bug reports, just tiny things like broken images and stuff, let me know.

**Comment by padams** [comment]
It’s likely because there is a row in the document table for that page already.

OWA does not currently update its dimensions so it just stays set to the values presented when the page is first recorded.

I suggest manually deleting the row for that page in the db and then have OWA track that page all over again.

Yes, please file any and all _new_ bugs or update existing tickets of old ones.

**Comment by znrR** [comment]
Just a short followup on this, I deleted the DB row for the page, but OWA does not create a new one for it when tracked again :-/ in the UI it shows the request, but has alle information fields blank. not sure if its a malfunction that deleted rows get not re-created..maybe there some other reference a some place? however, I then went back to backup and added the / manually to the row which works for now :)

**Comment by padams** [comment]
Do you have object caching turned on? If so you may need to delete the cache folder for the owa_document entity as well.

**Comment by znrR** [comment]
indeed, the cache is on! its a bit scary to me to fiddle in the mysql, is it ok to just use the "flush cache" feature in the admin UI? will it cause trouble with my manually edited rows? 😬

**Comment by padams** [comment]
Use the CLI to flush the cache. It has nothing to do with the DB. It’s just files stored in the file system. 

To remove it manually you just delete the folder for owa_document inside the cache folder within owa-data/caches/1.

**Comment by znrR** [comment]
CLI ;-) Will give it a try with pretty GUI SFTP client in a minute!

**Comment by znrR** [comment]
Good News: Deleting Row and Cache lead to newly created row (and also to new cache folder)
Bad News: / still missing in the fresh one :-/

**Comment by padams** [comment]
I just tested this and it works for me. are you sure you are using the latest code in master?

**Comment by padams** [comment]
also turn on development login i the config file and look at the errors log file to see exactly what's happening when OWA processes the request for that page. The errors log file will show you what OWA is doing to each tracking param before storing them in the DB.

**Comment by znrR** [comment]
Hi Peter, I am pretty confident that i have the recent files... although i only replaced the 3 files that you changed and not everything. i hope that's not the problem?! i was afraid of overwriting conf-files by just downloading everything and replacing it on the server.

If i need to update everything, please advice me if theres anything other than owa-config.php to keep..

 let me know if you want me to send the error-log (its quite some data for just one request, wow..) and maybe its not smart to post the errorlog public on the web?

heres what i found in the errorlog and found relevant.

Here the / is alive as URI:
```
00:30:40 2020-01-11 30082 [debug_log] Filter: owa_trackingEventHelpers::derivePageUri. Value passed:  
00:30:40 2020-01-11 30082 [debug_log] Filter: owa_trackingEventHelpers::derivePageUri. Value returned: / 

```

But at 

`00:30:41 2020-01-11 30082 [debug_log] Dispatching base.page_request event with properties: Array`

its already lost:

```
.
.
[msec] => 0.64634700
[page_uri] => 
[is_repeat_visitor] => 1
.
.
```

and its gets then not inserted to the DB:

`00:30:41 2020-01-11 30082 [debug_log] Query: INSERT into owa_document (id, url, uri, page_title, page_type) VALUES ('1534249307', 'https://www.blahblahmyurl.de', '', 'Schweinhund Bikes Berlin | Custom Builds &amp; Modern Classics', 'Page') `

**Comment by padams** [comment]
owa-conf.php is the only config file. Everything else should be replaced. Try that as I cant reproduce this in my end...

**Comment by znrR** [comment]
oh my... yes that helped :-) sorry for stealing your time :-/
