### ISSUE TITLE
wp_plugin.php needs version number bumped to 1.6.4

### ISSUE THREAD

**Issue by sysfu** [padams/Open-Web-Analytics#439]
wp_plugin.php needs version number bumped to 1.6.4

/*
Plugin Name: Open Web Analytics
Plugin URI: http://www.openwebanalytics.com
Description: This plugin enables Wordpress blog owners to use the Open Web Analytics Framework.
Author: Peter Adams
**Version: v1.6.0**
Author URI: http://www.openwebanalytics.com
*/

**Comment by padams** [comment]
I'm going to bump this version to 2.0 as soon as I'm done overhauling it and then let the plugin version diverge with OWA's version. Reason being is that the WordPress plugin should really be distributed separately via the WordPress plugin repository.
