### ISSUE TITLE
Removing admin records from OWA reports

### ISSUE THREAD

**Issue by andrew5555** [padams/Open-Web-Analytics#44]
I am attempting to block my own visits from showing in the reports inside OWA. I see where I can enter an IP address to ignore, but my ISP keeps changing my IP. So, new records keep appearing for my own site visits. 

Is there anyway I can delete the records associated with a user (me). For example, when I go to unique user page in OWA, I see what appears to be a user id of: 1418384573097102200

Is there a way to somehow delete these visitor records, even if I need to go into to phpmyadmin and delete records from there? I am hesitate to do this without clarification first, as I don't won't to screw something up. Thanks for any suggestions. 

Also, a great feature would be to have a "delete this user's records" button on each individual user's page - this way, if you see your own records (obvious when you can see restricted pages you have accessed), all records could be easily deleted. Could also be helpful for deleting other admins that don't have access to OWA and which you don't know the ip of (remote chat operators, etc).

**Comment by padams** [comment]
That feature would be very very expensive. 

More feasible would be to check for the existence of the OWA u cookie and not track. That would be a very simple JavaScript wrapper or module on the server side.

--
Peter Adams

**Comment by andrew5555** [comment]
Thank you for the reply. Any ideas on implementing the JavaScript wrapper or module? This is over my head. Is this something that could be accomplished for a fee? 

I looked into Chrome Browser settings out of curiosity. It appears you can only block cookie tracking for a whole site, not for a specific cookie on a site: ( 

Also, if I have the visitor such as "1418384573097102200" - is there a recommended method of hard deleted all the records for this user in phpmyadmin (a specific table, etc)? 

Thanks for any suggestions.

**Comment by padams** [comment]
ha. This feature was actually already implemented. All you have to do is set "Log Requests From Named Users" to off in your Admin settings. This will stop OWA from logging any OWA admin user.
