### ISSUE TITLE
Regenerate preview image for website?

### ISSUE THREAD

**Issue by BloodyIron** [padams/Open-Web-Analytics#441]
So I just rolled out a new website replacing an existing one, and this is with a brand new OWA setup. However, OWA generated the thumbnail of the old website, and not the new one. I want to regenerate it with the new website.

I tried deleting it and re-adding it, but it kept the old thumbnail.

How do I get it to regenerate with the new site, and how often does it automatically do this itself?

**Comment by Maaiins** [comment]
The project uses the wordpress mshot, so it should update automatically.

Example:
https://s.wordpress.com/mshots/v1/https%3A%2F%2Fwww.google.com%2F?w=150

**Comment by BloodyIron** [comment]
How often does it regen? (time period)

**Comment by Maaiins** [comment]
I don´t really know that. In my case it took about 24h. Don´t forget to refresh your site cache, your browser may cache the image.

**Comment by padams** [comment]
Yeah this is up to folks at WordPress how long they cache those images.

**Comment by BloodyIron** [comment]
I don't use Word Press though...

**Comment by padams** [comment]
It’s a free web service. You don’t have to use WordPress in order to create the images.
