### ISSUE TITLE
Does OWA need to be publicly reachable?

### ISSUE THREAD

**Issue by BloodyIron** [padams/Open-Web-Analytics#442]
When I setup Open Web Analytics, does the URL for OWA need to be reachable publicly?

I currently have it setup so you can only reach OWA internally, and I get stats, but I'm seeing a google preview small error, and I don't know if I _need_ to make the OWA FQDN and website fully available publicly for it to work or not.

Please advise.

**Comment by timetravlr** [comment]
I have the same question. Internally, we are able to get metrics in OWA if we test web sites from internal systems. But from another network... no metrics. The web sites are on the DMZ so they are able to be reached by an internal and an external IP.

**Comment by padams** [comment]
OWA requires the use of a fully qualified domain name for its cookies.

**Comment by BloodyIron** [comment]
> Perhaps we need to have a dedicated IP for the OWA server on the DMZ so we can run the javascript snippet.

I bet you can also accomplish this with a reverse-proxy to share a specific IP, without having to put the OWA host in a DMZ (which reduces security of that system).
