### ISSUE TITLE
What are all these (not set) fields

### ISSUE THREAD

**Issue by demandspringbill** [padams/Open-Web-Analytics#444]
I see a lot of (not set) fields in my installation. I thought I could glean the fields based on the demo site, but the demo has the same thing.
Sorry to be so obtuse, but what are these (not set) fields, and how can I either populate them or remove them?
Thanks
<img width="476" alt="Screen Shot 2020-01-12 at 4 07 50 PM" src="https://user-images.githubusercontent.com/58176874/72225678-1ab8ce00-3556-11ea-98b1-b81f6ba55b20.png">

**Comment by znrR** [comment]
Hey there, the first one next to the icon I assume is the username, never saw that filled though. the  second and third are city and state (if you have the geolocation plugin installed). to install geolocation you need to follow this guide https://github.com/padams/Open-Web-Analytics/wiki/Maxmind-GeoIP-Module - in short: download a DB from maxmind after regsitering for free, place it at the right spot and then enable the plugin in settings. 
<img width="171" alt="Screenshot 2020-01-13 at 23 42 06" src="https://user-images.githubusercontent.com/59607366/72298695-188e6680-365f-11ea-99ba-4f446955254f.png"> 
Nice "home" pagetype btw, do you set it manually or does iOWA set that on its own in your install?

**Comment by demandspringbill** [comment]
Thank you! That was very helpful.
