### ISSUE TITLE
Cannot log in to OWA with chrome

### ISSUE THREAD

**Issue by pyuyu** [padams/Open-Web-Analytics#452]
Cannot log in to OWA with chrome. Typing is complete and clicking Login does not respond. I can log in in firefox.
The server log is:
```
[Fri Feb  7 16:41:21 2020] 127.0.0.1:50691 [302]: /index.php?owa_do=base.loginForm&owa_go=http%3A%2F%2F127.0.0.1%2F&
[Fri Feb  7 16:41:21 2020] 127.0.0.1:50692 [302]: /
[Fri Feb  7 16:41:21 2020] 127.0.0.1:50694 [200]: /index.php?owa_do=base.loginForm&owa_go=http%3A%2F%2F127.0.0.1%2F&
```
[report gif](https://pyuyu-1253816789.cos.ap-beijing.myqcloud.com/uPic/login.gif)

**Comment by Maaiins** [comment]
Please take a look at: https://github.com/padams/Open-Web-Analytics/wiki/Installation

My installation is working fine, so it´s not a general problem.

**Comment by padams** [comment]
Same here. Odd version of Chrome maybe or a Chrome plugin issue? closing but re-open if you can debug more.
