### ISSUE TITLE
Already installed asking to install again

### ISSUE THREAD

**Issue by droidman85** [padams/Open-Web-Analytics#454]
I installed Open Web Analytics for a whyle now and after about a month i went to login and take a look at the stats and i'm presented with the install page, asking me to add websites to monitor. if i try to add a website i already added it gives me an error saying exactly that the website is already configured.
mysql is not running on strict mode.
i checked the issue with 3 different browsers including firefox with 100% cookies history and cache deleted.

[link to the installation](http://analytics.protectedcloudhost.com/mystats/)

**Comment by Maaiins** [comment]
When I open the page there´s no install wizard anymore.

**Comment by padams** [comment]
same here. closing but please reopen if you can debug your install.
