### ISSUE TITLE
Mediawiki special page get internal error

### ISSUE THREAD

**Issue by ed29** [padams/Open-Web-Analytics#455]
Hi:

I install owa(master) to extensions/owa for mediawiki 1.33.1 by wiki's guides,but the special page can't be visited,it show internal error like this:

[aebee5da53f78bba7046730c] /wiki/Special:%E7%89%B9%E6%AE%8A%E9%A1%B5%E9%9D%A2 Error from line 498 of /home/ed/ed29_com/extensions/owa/mw_plugin.php: Call to undefined method SpecialPage::SpecialPage()

Backtrace:

#0 /home/ed/ed29_com/includes/specialpage/SpecialPageFactory.php(396): SpecialOwa->__construct()
#1 /home/ed/ed29_com/includes/specialpage/SpecialPageFactory.php(426): MediaWiki\Special\SpecialPageFactory->getPage()
#2 /home/ed/ed29_com/includes/specials/SpecialSpecialpages.php(56): MediaWiki\Special\SpecialPageFactory->getUsablePages()
#3 /home/ed/ed29_com/includes/specials/SpecialSpecialpages.php(44): SpecialSpecialpages->getPageGroups()
#4 /home/ed/ed29_com/includes/specialpage/SpecialPage.php(569): SpecialSpecialpages->execute()
#5 /home/ed/ed29_com/includes/specialpage/SpecialPageFactory.php(558): SpecialPage->run()
#6 /home/ed/ed29_com/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath()
#7 /home/ed/ed29_com/includes/MediaWiki.php(865): MediaWiki->performRequest()
#8 /home/ed/ed29_com/includes/MediaWiki.php(515): MediaWiki->main()
#9 /home/ed/ed29_com/index.php(42): MediaWiki->run()
#10 {main}

**Comment by padams** [comment]
It's likely that the mediawiki plugin is using some old methods that are out of date with the current version of Mediawiki. I'll take a look at a patch if anyone debugs.

**Comment by ed29** [comment]
OK


 
---Original---

**Comment by padams** [comment]
dupe with #460
