### ISSUE TITLE
set page path and referrer with php tracker manually

### ISSUE THREAD

**Issue by Andiministrator** [padams/Open-Web-Analytics#457]
Is there a way with PHP Tracker to set the page path and referrer of a page manually?
Something like
$owa->setPagePath('/my/path');
?

**Comment by padams** [comment]
page_url yes. HTTP_REFERER no. 

Use the setGlobalEventProperty method.

**Comment by Maaiins** [comment]
You can set the page path like this:
```
$owa = new owa_php();
$owa->setProperty('page_url', '/my/path');
```
