### ISSUE TITLE
Intrusive Recurring requests log.php and blank.php

### ISSUE THREAD

**Issue by hirako2000** [padams/Open-Web-Analytics#46]
Hello,

As reported on issue #34, Those requests for the domstream tracking degrades the end user experience. I noticed this issue a couple of years back and assumed this would be fixed. It apparently works as designed.

Is it possible to revisit this feature to make the POST request asynchronous ? it would make the tracking totally transparent to the user. At the moment browsers shows indicators as if the page was reloading.

thanks.

**Comment by padams** [comment]
The only way I could get a cross domain POST to work on all browsers was to dynamically build a form within an frame and submit that.

The reason it needed to be a POST in the first was to deal with the request length.

There might better ways to do this with more modern browsers or maybe I missed something regarding the silencing if the form submit.

--
Peter Adams

**Comment by hirako2000** [comment]
Would that be an appropriate solution, for POST requests as the request body indeed can be pretty large.

http://stackoverflow.com/questions/298745/how-do-i-send-a-cross-domain-post-request-via-javascript

**Comment by padams** [comment]
Yes but i don't believe it is widely supported by all browsers yet....

**Comment by fragmadata** [comment]
@hirako2000 , can I know what kind of degradation did you notice? Did the UI become unresponsive?

**Comment by hirako2000** [comment]
No, it is responsive. The issue is that the browser shows as if the page is loading every few seconds (with mouse tracking).
The degradation is that users are under the impression they clicked somewhere or are navigating out of the page.

**Comment by fragmadata** [comment]
@hirako2000, Thanks for your response. This is helpful.
