### ISSUE TITLE
OWA Registering page views but not updating site metrics graph or headline figures

### ISSUE THREAD

**Issue by sixtillnine** [padams/Open-Web-Analytics#467]
After a semi successful test installation of OWA in a directory on my domain. I installed a fresh version under a subdomain. 

The subdomain version is registering page views (they appear in the tables), but not updating the site metrics graph (shows 'No data is available for this time period'), nor any of the figures on the dashboard or within the boxes beneath the site metrics.

Has anyone else encountered this and come up with a fix?

**Comment by Maaiins** [comment]
Got a similar issue with campaigns, but still have no clue what´s the problem. Try to clear the cache via the administration panel. Maybe a caching problem

**Comment by sixtillnine** [comment]
Thanks Maaiins, I looked this morning and the data was showing OK.

After you mentioned caching - I'm beginning to thinks its an issue with lite speed on my server and not OWA.
