### ISSUE TITLE
OWA Wordpress plugin "You do not have sufficient permissions to access this page."

### ISSUE THREAD

**Issue by cpsyctc** [padams/Open-Web-Analytics#48]
I seem to have successfully installed the latest OWA for WP plugin (as of today, 9.i.15) and activated the plugin in WP and I seemed to be able to change the config and there is now an "Analytics" item in the dashboard and that seems to show that the site is now being tracked but when I click on pretty much any link there that is about the reporting I simply get this message:
   "You do not have sufficient permissions to access this page."
Can someone help me out with this?  TIA, Chris

**Comment by padams** [comment]
You need to have full admin rights in wordpress.
Also the wordpress Install must not be multisite.

**Comment by cpsyctc** [comment]
Many thanks, 

I am an admin and as far as I know have all rights and the WP installation is a single site. 

Any other thoughts? 

Chris 

----- Original Message -----

> From: "padams" <notifications@github.com>
> To: "padams/Open-Web-Analytics" <Open-Web-Analytics@noreply.github.com>
> Cc: "cpsyctc" <cstweb@psyctc.org>
> Sent: Friday, 9 January, 2015 5:04:47 PM
> Subject: Re: [Open-Web-Analytics] OWA Wordpress plugin "You do not have
> sufficient permissions to access this page." (#48)

> You need to have full admin rights in wordpress.
> Also the wordpress Install must not be multisite.

**Comment by cpearson3** [comment]
Has this issue been resolved? I installed the plugin on a fresh Wordpress deployment hosted on Cloud9 and am receiving the same error when going to the Settings page. 

Any help would be greatly appreciated. Thanks.

- Clarence

**Comment by padams** [comment]
This is very  likely now fixed in master.
