### ISSUE TITLE
tracking by image

### ISSUE THREAD

**Issue by joubertredrat** [padams/Open-Web-Analytics#49]
Hi guys,

I'm testing owa here and I saw that don't have tracking by image option.

I tried to track using this example https://gist.github.com/joubertredrat/6b49b07ed460074091a1 but don't work.

Anyone knows if have this option? If not, I can try to develop this.

**Comment by padams** [comment]
There are two tracker clients that you can use:

1. JavaScript tracker. This uses JavaScript to output an img tag for the tracking call. You can grab the JavaScript tag for your site from the site roster within the OWA interface.

2. The PHP tracker which does the tracking server side (relying on cookies).

--
Peter Adams
