### ISSUE TITLE
suggest:keep the user-agent parser updated 

### ISSUE THREAD

**Issue by ed29** [padams/Open-Web-Analytics#490]
Hi:

Althought the user-agent is important for dig data,but it is alway changing,i mean that it's created and abandoned.So,I suggest to think about to use a third part lib to deal with it.So the data of analytics will look more real and rich,updated.Something like this:https://github.com/matomo-org/device-detector

**Comment by padams** [comment]
We already use a third party library called User Agent Parser (https://github.com/ua-parser/uap-core). The library yo mention is nearly identical in the fact that it relies on updating the underlying data files periodically. 

We don't have a CLI command yet to update the data file but others have been able to. See #298 .

I'm going ot close this as we already have #477 to track the development of a feature for this.

**Comment by ed29** [comment]
I got it,thank you.


 
---Original---
