### ISSUE TITLE
Run owa locally using Joomla and wampserver

### ISSUE THREAD

**Issue by gituserfirst** [padams/Open-Web-Analytics#50]
I try to run the openwebanalytics software locally under wampserver and joomla using the instructions of this video https://www.youtube.com/watch?v=Cj-d8HJYH2k.

I have created the db.

I have insert the owa file under the joomla site.

I type in my browser the path for the file http://localhost/openwebanalytics/owa/install.php and press the start button.

In the next step I get this error but I can insert the data for the db.

I press the button for the next step and I get only warnings.

What could be possible wrong with the process?

**Comment by padams** [comment]
what error are you getting?

**Comment by gituserfirst** [comment]
![1](https://cloud.githubusercontent.com/assets/9978383/5707588/af7eb586-9a92-11e4-92f1-df7b10c01f6d.png)

**Comment by gituserfirst** [comment]
this is the results from the second step but under this i can include the configuration with db but when i go to the next step i get more like the previous

**Comment by padams** [comment]
which version of php are you running?
try setting your php error reporting to ignore warnings.

-P-

**Comment by gituserfirst** [comment]
I am running 5.5.12 version. The error in the image is also a warning?

Because in the third step I can't complite the installation.

**Comment by gituserfirst** [comment]
http://www.filedropper.com/step3

**Comment by padams** [comment]
that’s part of the issue as OWA does not yet support PHP 5.5. You can try to make it work but PHP 5 on Windows, is not tested yet.

**Comment by gituserfirst** [comment]
With which version of php do you recommend to run owa?

As I can understand I can't make it work

**Comment by padams** [comment]
php 5.2 or 5.3. 

5.4 should be ok as well.

-P-

**Comment by gituserfirst** [comment]
I will try this and I will come back to you in some minutes

**Comment by gituserfirst** [comment]
Unfortunatelly I can't run it using an older version of wampserver with php 5.4 because the latest version of Joomla! I think have an issue.

Could be possible to provide an update for the php 5.5 version?

**Comment by gituserfirst** [comment]
Is it possible to provide an update for owa in the next days for newer version of PHP 5.5, 5.6?

**Comment by padams** [comment]
This should be fixed now as we are fixing bugs for php 7.4 now...
