### ISSUE TITLE
No graphics

### ISSUE THREAD

**Issue by WieZoek** [padams/Open-Web-Analytics#51]
Hi,
We did a clean install on our server. Seems to be oke but we do not see any graphs?

**Comment by severfire** [comment]
I do have same issue. No metrics displayed.

**Comment by padams** [comment]
It's most certainly a permissions issue on the server. Look at the HTTP requests in a debugger like firebug. Chances are they are failing.

**Comment by severfire** [comment]
looks like it was .htaccess that was folder below (with oxwall rules), that was overwriting everything above...
