### ISSUE TITLE
notifications on every event tracked

### ISSUE THREAD

**Issue by sangra4l** [padams/Open-Web-Analytics#53]
hi,
is it possible to inform a web app on my site server every time the owa tool tracks an event?

**Comment by padams** [comment]
Yes. OWA has several filter hooks that you can use to trigger custom code.

**Comment by sangra4l** [comment]
Could you direct me in to make a call to a custom Url every time a click is performed?

**Comment by padams** [comment]
Take a look at hello module for an example on how to write a module. hooking into the  "post_processed_tracking_event" filter is likely what you need. it is fired on every tracking event.
