### ISSUE TITLE
Performance Tuning

### ISSUE THREAD

**Issue by jagdish-nasit** [padams/Open-Web-Analytics#54]
Hi,

I am observing performance issue in dahboard & reports, its taking either too long or doesn't appear 
![dashbaord](https://cloud.githubusercontent.com/assets/2486967/5952958/9d7ddaac-a7a7-11e4-885b-52bf6fe21d7b.PNG)

Database has 3 months of data to it.

Is there any performance tuning or Indexing guidelines ? I went through MySQL status in phpMyAdmin interface and few parameters are in red,  indicating slow query or full table scan.

Any pointers if somebody has already done this exercise.

**Comment by thebennos** [comment]
It is more a Database question then an OWA question. 
Performance of your database depends on data and enviroment variables. 
Example: 
When you have 1 mio entries and mysql config is standard config, mean no imporvemt for indizes and .. 
then your Query can takes minutes. 

With the right mysql config you can speed it up. 

post your my.cnf here and you get some suggestions ti improve it.

**Comment by pratham2003** [comment]
I'm having same issues with just 1-2 weeks of data..
Almost everything takes ages to load.
http://pastebin.com/6HkxpEnF

**Comment by padams** [comment]
Take a look at MySQL slow query log and see which queries are hanging it up.

Also how many rows are in each table?

**Comment by pratham2003** [comment]
3170326 rows in owa_domstream currently.

mtop reports that its copying to temporary table.

From HHVM log. - slow queries
[Sun Aug  9 14:42:07 2015] [hphp] [15847:7fd995fff700:30:000001] [] SlowTimer [300100ms] at runtime/ext_mysql: slow query: SELECT * FROM owa_domstream WHERE domstream_guid = '1438796244757486608'   ORDER BY timestamp ASC

[Thu Aug 13 22:18:05 2015] [hphp] [15847:7fd995fff700:67:000001] [] SlowTimer [153765ms] at runtime/ext_mysql: slow query: SELECT domstream_guid, max(timestamp) as timestamp, page_url, duration, document_id FROM owa_domst
ream WHERE yyyymmdd BETWEEN '20150715' AND '20150813' AND site_id = 'e205d2512f1665981e1f6ad797c73a60' GROUP BY domstream_guid  ORDER BY timestamp DESC LIMIT 500

**Comment by padams** [comment]
yeah. there’s some code at work here that needs optimizing.
You could do a SQL describe on one of those queries and see if an index might help.
