### ISSUE TITLE
I can't get past the login page, even with good credentials.

### ISSUE THREAD

**Issue by logicaloctopus** [padams/Open-Web-Analytics#55]
I have gone through installation a number of times and I keep getting stuck in the same spot. I can't get past the login screen.

Here's what I have done:
I remove all prior database tables and recreate an empty database (in MySql)
I grant access to the a new database for use by OpenWebAnalytics
I untar OpenWebAnalytics into an html folder on our apache server (I've tried v1.5.7 and v1.5.0)
I chown the entire folder and contents to apache (so it has write access)
I navigate to http://{server_ip}/owa/ and click the 'Lets get started' button
I fill in the form about our database settings and click the 'Continue' button
I fill in the form about default site & user info and click the 'Continue' button
It says 'Success!' and echos back my username and password.
At this point I check my database and see it has created the tables.
I click the 'Login and generate a site tracker' button.
On the login page I type the username ('admin') and password and click the 'Login' button.

All it does it regenerate the login page, but goes nowhere else.

If I type in bad credentials it tells me 'Login Failed'
When I type good credentials, the message is absent, but I am still stuck on the login page.

I have gone through the installation a number of times checking to see if I have missed anything.
I have checked the server error logs and there is nothing that indicates any problems.

What have I done wrong?

**Comment by padams** [comment]
Try running under a fully qualified domain name and not an IP address.

--
Peter Adams

**Comment by logicaloctopus** [comment]
Yes, that's the difference.  Working now. Thanks so much.
