### ISSUE TITLE
Blank screen for a reporting tab on tracked site

### ISSUE THREAD

**Issue by aakarsha** [padams/Open-Web-Analytics#58]
I installed OWA -1.5.7. I am getting blank screen for reporting when I go to tracked sites. I can't access my dashboard. 

Can somebody help me out with the problem?

**Comment by Mike1977** [comment]
same issue here. It seems that NoScript declare something about OWA as cross-site-scripting and denys som operations... OWA then do not work properly and try so send an report... 
its a weired behavior...

**Comment by padams** [comment]
Are you running under a fully qualified domain name? A FQDN is required. Localhost or an IP will not work.

Also what errors if any are you seeing in the console?

**Comment by aakarsha** [comment]
It worked for me after changing Mysql to non-script mode. Thanks!
