### ISSUE TITLE
No Visit Clickstream

### ISSUE THREAD

**Issue by virsonebillo** [padams/Open-Web-Analytics#61]
Just installed OWA 1.5.7. Can someone help me as to why there are no links displayed at the Visit Clickstream? 

For example when I click on Visit Detail, I can see that there are time frames but there are no links in it.
I wan to know if the heatmap tool is working.

**Comment by dhruwal** [comment]
Did you add tracking code to the website you want to track?
Also heatmap can be seen on FireFox browser.
