### ISSUE TITLE
Strict Standards: Non-static method owa_sanitize::cleanInput() should not be called statically

### ISSUE THREAD

**Issue by eunarede** [padams/Open-Web-Analytics#62]
After installation wen try to login I receive this message error (version 1.5.7)

>Strict Standards: Non-static method owa_sanitize::cleanInput() should not be called statically in /www/owa/modules/base/classes/sanitize.php on line 329

>Warning: Cannot modify header information - headers already sent by (output started at /www/owa/modules/base/classes/sanitize.php:329) in /www/owa/owa_auth.php on line 332

>Warning: Cannot modify header information - headers already sent by (output started at /www/owa/modules/base/classes/sanitize.php:329) in /www/owa/owa_auth.php on line 333

>Warning: Cannot modify header information - headers already sent by (output started at /www/owa/modules/base/classes/sanitize.php:329) in /www/owa/owa_lib.php on line 569

>Warning: Cannot modify header information - headers already sent by (output started at /www/owa/modules/base/classes/sanitize.php:329) in /www/owa/owa_lib.php on line 570

**Comment by dhruwal** [comment]
For time being I commented error_reporting in php.ini and then it works.
Hopefully developers figures out what is causing that.

**Comment by padams** [comment]
This is fixed in master.

**Comment by mkmobi** [comment]
getting same issue when installed using softcalous
please help me to solve the issue
