### ISSUE TITLE
Error Activating WordPress Plugin

### ISSUE THREAD

**Issue by xtremetoonz** [padams/Open-Web-Analytics#63]
I'm getting the following error when trying to activate my OWA WordPress Plugin (from apache logs)

[Sun Mar 15 10:52:37 2015] [error] [client 24.211.197.189] PHP Warning:  fopen(/var/www/site.org/wp-content/plugins/owa/owa-config.php): failed to open stream: Permission denied in /var/www/site.org/wp-content/plugins/owa/modules/base/classes/settings.php on line 776, referer: http://site.org/wp-admin/plugins.php?error=true&plugin=owa%2Fwp_plugin.php&_error_nonce=1f2c0c4aff
[Sun Mar 15 10:52:37 2015] [error] [client 24.211.197.189] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/site.org/wp-content/plugins/owa/modules/base/classes/settings.php on line 799, referer: http://site.org/wp-admin/plugins.php?error=true&plugin=owa%2Fwp_plugin.php&_error_nonce=1f2c0c4aff

This repeats quite a few times then:

[Sun Mar 15 10:52:37 2015] [error] [client 24.211.197.189] PHP Warning:  chmod(): No such file or directory in /var/www/site.org/wp-content/plugins/owa/modules/base/classes/settings.php on line 804, referer: http://site.org/wp-admin/plugins.php?error=true&plugin=owa%2Fwp_plugin.php&_error_nonce=1f2c0c4aff
[Sun Mar 15 10:52:37 2015] [error] [client 24.211.197.189] PHP Warning:  require_once(/var/www/site.org/wp-content/plugins/owa/owa-config.php): failed to open stream: No such file or directory in /var/www/site.org/wp-content/plugins/owa/modules/base/classes/settings.php on line 806, referer: http://site.org/wp-admin/plugins.php?error=true&plugin=owa%2Fwp_plugin.php&_error_nonce=1f2c0c4aff

Line 804 seems to refer to a OWA_DIR variable in the owa-config.php file which I only have in the root of the OWA server site, not the site I'm attempting to monitor with the WordPress plugin.

Dylan

**Comment by padams** [comment]
The entire OWA download package needs to be put in the wp plugins folder, not just the plugin file.

See the install wiki page on github

**Comment by xtremetoonz** [comment]
I installed from the WordPress plugins page. Below are my 
wp-content/plugins/owa/ files/folders:

-rw-r--r--  1 bdrweb bdrweb   209 Mar 15 10:43 Callbacks.inc
-rw-r--r--  1 bdrweb bdrweb  1244 Mar 15 10:43 action.php
-rw-r--r--  1 bdrweb bdrweb  1281 Mar 15 10:43 api.php
-rw-r--r--  1 bdrweb bdrweb  2107 Mar 15 10:43 cli.php
drwxr-xr-x  2 bdrweb bdrweb  4096 Mar 15 10:43 conf
-rw-r--r--  1 bdrweb bdrweb  1270 Mar 15 10:43 daemon.php
-rw-r--r--  1 bdrweb bdrweb  9992 Mar 15 10:43 eventQueue.php
drwxr-xr-x  6 bdrweb bdrweb  4096 Mar 15 10:43 includes
-rw-r--r--  1 bdrweb bdrweb  1322 Mar 15 10:43 index.php
-rw-r--r--  1 bdrweb bdrweb  5380 Mar 15 10:43 ini_db.php
-rw-r--r--  1 bdrweb bdrweb  1628 Mar 15 10:43 install.php
-rw-r--r--  1 bdrweb bdrweb  1293 Mar 15 10:43 log.php
-rw-r--r--  1 bdrweb bdrweb 13123 Mar 15 10:43 module.inc
drwxr-xr-x  5 bdrweb bdrweb  4096 Mar 15 10:44 modules
-rw-r--r--  1 bdrweb bdrweb 15711 Mar 15 10:44 mw_plugin.php
-rw-r--r--  1 bdrweb bdrweb  2462 Mar 15 10:44 owa-config-dist.php
drwxr-xr-x  4 bdrweb bdrweb  4096 Mar 15 10:44 owa-data
-rw-r--r--  1 bdrweb bdrweb  1327 Mar 15 10:44 owa_adminController.php
-rw-r--r--  1 bdrweb bdrweb  8802 Mar 15 10:44 owa_auth.php
-rw-r--r--  1 bdrweb bdrweb  3039 Mar 15 10:44 owa_base.php
-rw-r--r--  1 bdrweb bdrweb  9160 Mar 15 10:44 owa_caller.php
-rw-r--r--  1 bdrweb bdrweb 12398 Mar 15 10:44 owa_controller.php
-rw-r--r--  1 bdrweb bdrweb 35182 Mar 15 10:44 owa_coreAPI.php
-rw-r--r--  1 bdrweb bdrweb 21688 Mar 15 10:44 owa_db.php
-rw-r--r--  1 bdrweb bdrweb 14749 Mar 15 10:44 owa_entity.php
-rw-r--r--  1 bdrweb bdrweb  1755 Mar 15 10:44 owa_env.php
-rw-r--r--  1 bdrweb bdrweb  9032 Mar 15 10:44 owa_httpRequest.php
-rw-r--r--  1 bdrweb bdrweb  2484 Mar 15 10:44 owa_install.php
-rw-r--r--  1 bdrweb bdrweb 26927 Mar 15 10:44 owa_lib.php
-rw-r--r--  1 bdrweb bdrweb  1542 Mar 15 10:44 owa_location.php
-rw-r--r--  1 bdrweb bdrweb  5564 Mar 15 10:44 owa_metric.php
-rw-r--r--  1 bdrweb bdrweb 18397 Mar 15 10:44 owa_module.php
-rw-r--r--  1 bdrweb bdrweb  1481 Mar 15 10:44 owa_mw.php
-rw-r--r--  1 bdrweb bdrweb  5629 Mar 15 10:44 owa_news.php
-rw-r--r--  1 bdrweb bdrweb  2034 Mar 15 10:44 owa_observer.php
-rw-r--r--  1 bdrweb bdrweb  1451 Mar 15 10:44 owa_php.php
-rw-r--r--  1 bdrweb bdrweb  4515 Mar 15 10:44 owa_reportController.php
-rw-r--r--  1 bdrweb bdrweb  7496 Mar 15 10:44 owa_requestContainer.php
-rw-r--r--  1 bdrweb bdrweb 22675 Mar 15 10:44 owa_template.php
-rw-r--r--  1 bdrweb bdrweb 18378 Mar 15 10:44 owa_view.php
-rw-r--r--  1 bdrweb bdrweb  2267 Mar 15 10:44 owa_wp.php
drwxr-xr-x  5 bdrweb bdrweb  4096 Mar 15 10:44 plugins
-rw-r--r--  1 bdrweb bdrweb  1519 Mar 15 10:44 queue.php
-rw-r--r--  1 bdrweb bdrweb   671 Mar 15 10:44 readme.txt
-rw-r--r--  1 bdrweb bdrweb 15395 Mar 15 10:44 wp_plugin.php

Consequently I tried:
rm -r /var/www/site.org/wp-content/plugins/owa/*
cp -R /var/www/owa.domain.com/* 
/var/www/site.org/wp-content/plugins/owa/. where owa.domain.com is the 
OWA server content.

Dylan

padams wrote:

**Comment by padams** [comment]
Can you try just uploading the Iowa directory into wp-content/plugins without going through the WordPress GUI?

**Comment by padams** [comment]
Should be fixed in master. reopen if you are still seeing specific errors.
