### ISSUE TITLE
OWA statistics

### ISSUE THREAD

**Issue by madhavip** [padams/Open-Web-Analytics#65]
Hi,

 I need some info on whether OWA reports can be exported, if OWA tracks website perfomance,browser statistics,error/error count for webpages while accessing. Also i would like to know more details on the heatmaps. Can anyone provide me details on these, if we can track them using OWA.

Thanks,
Madhavi

**Comment by padams** [comment]
You can export data via the API. See the wiki for a list of metrics and dimensions available in OWA. heat maps show the clicks visitors make on a webpage.
