### ISSUE TITLE
How does one add OWA tracking code to Mediawiki?

### ISSUE THREAD

**Issue by purecanuck** [padams/Open-Web-Analytics#67]
The instructions found here: http://wiki.openwebanalytics.com/index.php?title=Installation
seem to be to add a standalone OWA into Mediawiki. I simply want to add JavaScript/tracking code into my mediawiki installation, so I can get it reporting on my stats/sites roster OWA instance.

**Comment by padams** [comment]
Sadly you will have to edit the "skin" used on your media wiki. If you are using mono book (the default) then add the code to /wiki/skins/MonoBook.php and that should work.
