### ISSUE TITLE
Site is up but am getting no data or analytics

### ISSUE THREAD

**Issue by Slouis61** [padams/Open-Web-Analytics#68]
I was using  version 1.56 on our old Production server with NO issues. We currently migrated to a New Server a bit more robust and Installed 1.57. The installation goes in with out a hitch or any issues whatsoever. The site is displayed however there are never ANY STATS.. Any help would be greatly appreciated.

I am not getting any errors on entry!

**Comment by Slouis61** [comment]
I think I have tried everything. Its probably something pretty dumb!.. I have checked permissions and server config from server to server.

**Comment by padams** [comment]
Fire up a javasscript debugger like Firebug and see whats happening to the tracking requests.
They may not be reaching the server if there are no stats.

Alternatively turn on debugging mode in your config file and see what the errors log has to say.

**Comment by ramondiego** [comment]
Hi, I'm having the same problem. I did the tests suggested, but not this returning me no errors.

**Comment by padams** [comment]
This is not a generalized issue any longer so I'm going to close. Just open a new issue if you are still having problems with the code in master.
