### ISSUE TITLE
Email Campaign Tracking

### ISSUE THREAD

**Issue by arniesaha** [padams/Open-Web-Analytics#69]
Hello!

I've just setup owa on one my domains, and exploring the features. Great tool!

But, I'm a little confused on the implementation of email campaigns.
I've refered this https://github.com/padams/Open-Web-Analytics/wiki/Campaign-Tracking

But, I'm unclear of the path, do I need to implement the tracking code in a separate script?

I need to configure email campaigns to track users that come from mass emailers and actually place an order on the site.

Thanks,
Arnab

**Comment by padams** [comment]
add the tracking codes to the links in your email and the OWA tracker javascript running on your web pages will pick it up.

**Comment by arniesaha** [comment]
Got it! Thanks!
