### ISSUE TITLE
Using magic quote gpc.

### ISSUE THREAD

**Issue by mohdaef** [padams/Open-Web-Analytics#7]
Hi,

I have tried to install OWA on a shared server, per consequent I cannot access or modify php.ini file.
Moreover I have tried to dynamically modify it on php page or in htaccess without any success.
What effect are induced on "domstreams" modules due to magic quote gpc extension enabled?
Is it possible to upgrade source code for unsecuring input data (reverse magic quote gpc action) in "domstreams" module ? (depending on how domstreams work, I don't know it)

**Comment by padams** [comment]
what version of PHP are you running that has magic quotes enabled? also what error are you seeing?

**Comment by padams** [comment]
Closing as no one else has reported this.
