### ISSUE TITLE
Maxmind GeoIP issue OWA 1.5.7 new install.

### ISSUE THREAD

**Issue by SpeedyRider** [padams/Open-Web-Analytics#70]
I did exactly as written here http://wiki.openwebanalytics.com/index.php?title=Maxmind_GeoIP

I created maxmind directory with the GeoLiteCity.dat file inside owa-data dir  /path_to_owa/owa-data/maxmind/GeoLiteCity.dat

Maxmind GeoIP Module is Active in the Administration > Modules > Maxmind GeoIP > Deactivate

I'm getting Country (no set) & Country Code (UNKNOWN COUNTRY?) stats

I need Country & Visitor IP address. Without Country IP stats   OWA is worthless.  
Any suggestions how to fix this problem? Thanks!

**Comment by padams** [comment]
Looks like maxmind changed the format of their DB. Two options here:

1. You can use the "Legacy" CityLite DB format that MaxMind still makes available.

2. You can check out he code in master which is now updated to work with the new DB format.

**Comment by SpeedyRider** [comment]
"2. You can check out the code in master which is now updated to work with the new DB format." 
Updated the Master Code.  Works like a charm.  Thank You Peter!

**Comment by padams** [comment]
you may need to pull it once more as i just committed a change to prevent hostip from resolving the location right after maxmind ;)

**Comment by SpeedyRider** [comment]
I just pull it once more Thanks!

**Comment by thob** [comment]
I downloaded from GH today but don't get any geo data. Any idea?
