### ISSUE TITLE
Javascript Tracker: Async 'setCustomVar'

### ISSUE THREAD

**Issue by jezsimmons** [padams/Open-Web-Analytics#72]
Hi,

Is the following construct correct for setting OWA Custom Variables in the Javascript Tracker?

owa_cmds.push(['setCustomVar', 'slot', 'name', 'value','scope']);

 I can't see any documentation regarding this.

Thanks
Jez

**Comment by padams** [comment]
Looks like that page didn't make it over to the github wiki. Here it is on the old wiki:

http://wiki.openwebanalytics.com/index.php?title=Custom_Variables

**Comment by derekshull** [comment]
The link provided above has a 404.  I have the same question though is the syntax correct?

owa_cmds.push(['setCustomVar', 'slot', 'name', 'value','scope']);

**Comment by padams** [comment]
Here's the new link: https://github.com/padams/Open-Web-Analytics/wiki/Tracker

**Comment by derekshull** [comment]
Yes but it doesn't give the owa_mds.push option.  It just has `setCustomVar( slot, name, value, scope )`.

**Comment by padams** [comment]
owa_cmds.push(['setCustomVar', 'slot', 'name', 'value','scope']); 

is the correct syntax using the async tracker.
