### ISSUE TITLE
reset password issue

### ISSUE THREAD

**Issue by pdemichele** [padams/Open-Web-Analytics#74]
hi there,

I've installed owa on a docker platform
the system works fine but I've a problem with users management

these the steps:
- Administrator - User management - Add new user
- I create the user following the criteria
- then edit user section, I press the button: change password for this user
- I post my email and press: request new password

in the top-left I see: Could not instantiate mail function.
in /var/log/nginx/error.log I see:
2015/04/29 18:04:01 [error] 415#0: *39 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: page_title in /var/www/owa/modules/base/templates/wrapper_public.tpl on line 6" while reading response header from upstream, client: 10.129.134.7, server: sub.domain.ext, request: "GET /index.php?owa_do=base.passwordResetForm HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "sub.domain.ext", referrer: "http://sub.domain.ext/index.php?owa_do=base.usersProfile&owa_edit=1&owa_user_id=arpa"

I need to install some MTA? I need to do anything else?
in this situation I'm not able to create another one user with restricted privileges

someone can help me?
thanks in advance
regards

**Comment by websoul67** [comment]
Is there any resolution to this?

**Comment by CainCook** [comment]
has this issue been resolved ?
please just enable password / account creation from within the admin management interface instead of sending email with password changes.. what happens if we cant access an account mail for whatever reason .. there is no other means of user account management regarding passwords otherwise and is entirely reliant on this send mail method ..

**Comment by deanq** [comment]
This project must be dead. oh well...

**Comment by padams** [comment]
It's an issue with how you have php configured to send mail. OWA does require the ability to send mail for user accounts.
