### ISSUE TITLE
owa causes to many connections. problems with hoster

### ISSUE THREAD

**Issue by madminxl** [padams/Open-Web-Analytics#75]
hello,
i made a wordpress site which is featured from tv.  http://yvonne-mouhlen.de and got yesterday a lot of traffic.the webhoster has blocked for the 2. timme the webspace, because of to many connections:
i think its caused from owa. the ip adress belongs to  http://www.hostip.info/ which is integrated in owa. what can i do now? how to disable this oder reduce connections?

in:
/htdocs/owa/modules/base/classes

is a file hostip.php  here you see a request to the ip adress: see below

here the logs from the webhoster: (Verbindungen means Connections)

Summary of all Connections 5355x

Connections Protocol: (1x insgesamt)
TCP => 5355x

Verbinungen nach Port: (1x insgesamt)
80 => 5355x

Connections to Target Server : (2x different IP-Nummer)
162.220.62.158 => 5353x (US, NA)
188.125.66.104 => 2x (IE, EU)

Connections to target Countrys: (2x different contrysr)
US => 5353x (United States)
IE => 2x (Ireland)

Connections to continents : (2x different continents)
NA => 5353x (North America)
EU => 2x (Europe)

_Log translated_

**Comment by padams** [comment]
turn off geo-location lookups from the settings admin page.
