### ISSUE TITLE
Cant see heatmap on a page with 150k+ views 

### ISSUE THREAD

**Issue by pratham2003** [padams/Open-Web-Analytics#76]
I see the following error 
stderr: PHP Notice:  Undefined offset: 3 
in owa_httpRequest.php on line 251 .. I think it isn't related tho..

The heatmap loads on the homepage.

Does Log Domstreams setting affect recording of data for heatmaps?
Also I notice that even tho I have Log domstreams turned off there are still some domstreams being recorded.

What I feel the problem could be is that there is so much data that the query doesn't run at all? or something like that? Any way to find out what the issue could be?

**Comment by pratham2003** [comment]
I figured out the problem but not the cause..
The document_id had changed for some reason..
The new document_id which was being used in the link to heatmap in the dashboard had a negative value and only had 1 click registered.

OWA records urls with query parameters and hashtags separately if I'm not wrong. Is there any way to make it consider several URLs at once just for the heatmap?

The URL and counts displayed in the dashboard are correct, but for some reason the document_id in the URL which I click to view the heatmap is wrong..
I can view the heatmap by manually editing the document_id in the URL with the document_id with most counts found by running the following query.

select document_id, count(*) as 'count' from owa_click where document_id in (select id from owa_document where page_title like 'Starting part of the page title%') group by document_id order by `count` desc

**Comment by padams** [comment]
You can set url params to ignore in settings. Highly suggest you do that for any session or visitor oriented params your app uses.

**Comment by pratham2003** [comment]
The link which you click to view the heatmap has a owa_document_id query parameter in it.
Gets it value.. its a long number.. it could be negative so keep a look out for that.. let me know if its negative.

So.. you get that run this query on the OWA database after replacing THE_DOCUMENT_ID with the actual owa_document_id value. If you see the data then the data is being recorded.
SELECT * FROM owa_click WHERE document_id = THE_DOCUMENT_ID

It could be possible that there are duplicates entries in the owa_document table for a single URL.
Try running the following query to find that.
SELECT id, url, count(id) as 'count' FROM owa_document GROUP BY url ORDER BY count DESC

By the way, have you moved the OWA installation from one server to another?
I faced a similar issue when i moved the OWA from one server to another.

**Comment by padams** [comment]
Documents are unique by url and are also unique to that table. Make sure you are striping off any session params from your URL (in OWA settings for the site) or else every page view is gong to be a unique document.

And yes if you change domains that will Also change the uniqueness of the URLs.
