### ISSUE TITLE
High number of clicks on the left side in heatmaps?

### ISSUE THREAD

**Issue by pratham2003** [padams/Open-Web-Analytics#77]
Concentrations like these appear in the extreme left side of almost every active page.
http://i.imgur.com/1vsmiiq.png

Any idea what these could be?
I'm guessing these are either mobile/tablet related..
I tried applying a filter by modifying the javascript to only plot the points with page_width greater than 1200 but they still appear.
(data[i].page_width >= 1200)

**Comment by padams** [comment]
not sure. but the User agent and dom_id and dom tag get recorded with each click. you could query and find out.
