### ISSUE TITLE
Heatmap overlay does not work

### ISSUE THREAD

**Issue by Seppe0021** [padams/Open-Web-Analytics#79]
I'm using OWA and when I open the heatmap overlay of a page,no dots are shown.
Not even when I click on the "play" button in the top right corner.
It simply does not seem to work.
Should I ad something to my code? ( I found this in the wiki:To create a heatmap:
//create the object
var heatmap = new owa.heatmap();
heatmap.generate(); 
If I have to ad something to my code , where should I put it?
Even more helpful would be if someone could give me the example code
Or is there an other reason why it does not work for me?
Thanks in advance

**Comment by pratham2003** [comment]
Hmm I faced a similar problem..
Have you tried refreshing the heatmap page? If refresh doesn't work try copying the link into a new tab instead of refreshing.. Try this a few times and let me know if it works for you..
I think there are some problems with pages that have sections which load via ajax..
If the above works I'll share a small change with you which delays loading the OWA heatmap code which gives the page time to complete loading.

**Comment by Seppe0021** [comment]
Dear pratham2003,
I've just tried both of your suggestions,none of them work.
Still no dots

**Comment by pratham2003** [comment]
Hi Seppe,
I accidentally deleted the long reply I wrong for you :(

Just a quick question, have you moved your OWA installation? I had too, and I think thats what caused a similar issue on mine. https://github.com/padams/Open-Web-Analytics/issues/76#issuecomment-99092193
Please check out my reply on this issue as I feel you are in the same case as me..

To verify that you need to find if your OWA has created duplicates for the exact same URL.
You can do that by running the following query which will show you if there are any duplicates for the single URL.
SELECT id, url, count(id) as 'count' FROM owa_document GROUP BY url ORDER BY count DESC
A count of anything more than 1 should mean a problem.

owa_document[id] is related to owa_click[document_id].
So could also run the following query after replacing THE_URL_YOU_FOUND with the url you find in the previous query.
SELECT a.id, url, count(a.id) FROM owa_document as `a` LEFT JOIN owa_click as `b` ON a.id = b.document_id  WHERE a.url = "THE_URL_YOU_FOUND" GROUP BY a.id

After you find out which of the duplicate document_ids have only 1 row in the owa_click table and delete it from owa_document table, that will cause OWA to generate the correct URL. In my case it was the negative document_id.

**Comment by Seppe0021** [comment]
Hi Pratham,
Thank you for your reply.
What you are writing here is complete Chinese for me.
I'm a complete novice at this.
Where should I run the query? How should I do this?What id must I select?etc..

**Comment by pratham2003** [comment]
Do you have access to phpMyAdmin?

If yes you would probably use that to run the queries.. But if you have no experience with this then I suggest that you do not go ahead with this and wait for official patch around this issue.

**Comment by Seppe0021** [comment]
Hi Pratham,
I have acces to phpMyAdmin
I just ran the first line you wrote in your comment (SELECT id, url, count(id) as 'count' FROM owa_document GROUP BY url ORDER BY count DESC)
All the url's have a count of 1
When I opened my database in phpMyAdmin,I noticed on the left things like owa_domstream, owa_clicks, owa_document,owa_request, owa_referer etc., but I don't see anything like owa_heatmap or something like that.
Should there not also be something like owa_heatmap or owa_heatmapovelay or something like that? 
Is there something missing?

**Comment by pratham2003** [comment]
Okay.
OWA just records clicks in owa_clicks and uses javascript to plot those clicks on the overlay using ajax, javascript and html's canvas to generate the heatmap. So there is nothing missing.

Btw, I forgot to ask, which browser are you using or have tried using? Try Firefox if you haven't already.

Can you also open the web inspector and look for any possible errors in the console tab?
https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Open_the_Inspector

If there are no errors there then run the following query to get a list of URLs along with the number of recorded clicks for that URL to find out if there is actually any clicks which were recorded. (If there is lot of data the query might take some time to finish executing)

SELECT a.id, count(b.id) as 'No. of clicks', url  FROM owa_document as a LEFT JOIN owa_click as b ON a.id = b.document_id GROUP BY a.id ORDER BY `No. of clicks` DESC

or to find a count for a specific URL you can get the URL from the query which you ran earlier (the one you mentioned in your last message) and replace the INSERT_YOUR_URL_HERE in the following query with the actual URL (it must match exactly).

SELECT id, count(id) 'Number of clicks' FROM owa_click WHERE document_id = (SELECT id FROM owa_document WHERE url = "INSERT_YOUR_URL_HERE");

**Comment by Seppe0021** [comment]
Dear pratham,
I used maxthon and I used Firefox to see the heatmap, in both browsers no results
When I run the first line in your last comment, I get the following error message: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'clicks DESC LIMIT 0, 30' at line 1"
When I run the second line in your comment and I replace "INSERT_YOUR_URL_HERE" by the URL of the page I want the check I get a result of 170 clicks(it gives a large id number followed by the number of clicks which is 170)

**Comment by pratham2003** [comment]
If it says it has 170 click then it should display it.
Any specific errors in the web inspector?
Does the document_id in the heatmap URL match the long number (id) returned by the query? (just making sure)

And opps the ` got interpreted as formatting.
I have corrected the query in my previous comment and also mentioned it in this comment.

    SELECT a.id, count(b.id) as 'No. of clicks', url  FROM owa_document as a LEFT JOIN owa_click as b ON a.id = b.document_id GROUP BY a.id ORDER BY `No. of clicks` DESC

**Comment by Seppe0021** [comment]
Dear pratham,
No errors after starting the inspector and refreshing the page
When I run your corrected code,the id number of the page is 1512532314 and it says that there are 170clicks.
Also in the owa_document the id number of the page is 1512532314
When I run the second line of code again -> ( SELECT id, count(id) 'Number of clicks' FROM owa_click WHERE document_id = (SELECT id FROM owa_document WHERE url = "INSERT_YOUR_URL_HERE")
it again says there are 170 clicks but the id number is way longer 1429110112684635371

**Comment by pratham2003** [comment]
1429110112684635371 would be the id for the click and not the document itself.

Hmm if there are no errors then there is not much I could do without having a look a it..
Anything in the PHP error_log?

**Comment by Seppe0021** [comment]
Where can I find that?

**Comment by Seppe0021** [comment]
Dear pratham,
I found this using "browserconsole" in the developer toolbar .
Gebruik van getAttributeNode() wordt niet meer ondersteund. Gebruik in plaats daarvan getAttribute().      owa.reporting-combined-min.js:500:0
 Gebruik van getPreventDefault() wordt niet meer ondersteund. Gebruik in plaats daarvan defaultPrevented.   owa.reporting-combined-min.js:501:0
 Gebruik van getAttributeNode() wordt niet meer ondersteund. Gebruik in plaats daarvan getAttribute().      owa.reporting-combined-min.js:500:0
 Gebruik van getPreventDefault() wordt niet meer ondersteund. Gebruik in plaats daarvan defaultPrevented.   owa.reporting-combined-min.js:500:0
It's in Dutch and it says:

Use of getAttributeNode() is no longer supported.Use getAttribute() instead.      owa.reporting-combined-min.js:500:0
Use of getPreventDefault() is no longer supported.Use defaultPrevented instead.   owa.reporting-combined-min.js:500:0
Use of getAttributeNode() is no longer supported.Use getAttribute() instead.      owa.reporting-combined-min.js:500:0
Use of getPreventDefault() is no longer supported.Use defaultPrevented instead.   owa.reporting-combined-min.js:500:0

**Comment by augmentplus** [comment]
Hi, 

iam new for OWA , where can i find heatmap option?

**Comment by Seppe0021** [comment]
Click on a visitor's "visit detail"
Now you see "Visit Clickstream"
Click on the page you want to see.
Now you see below " related reports" with "heatmap overlay, domstreams, domclicks"
If you click on one of them it will open the item
For heatmap overlay and domstreams, when opened, click on the play button in the upper right corner.

**Comment by augmentplus** [comment]
Hi Seppe0021,

yes now i found the solution , Thank you for your answer .
