### ISSUE TITLE
Wordpress Plugin settings

### ISSUE THREAD

**Issue by i-am-so-lame** [padams/Open-Web-Analytics#80]
Hello, I've just installed OWA as a plugin in Wordpress 4.2.2 and the problem is, that I cannot change options by clicking 'Update configuration' button, the page only refreshes and default settings stay unchanged.

BTW your wiki page seems to be incomplete https://github.com/padams/Open-Web-Analytics/wiki/Installation :-1: 

Please help,
Best regards :+1:

**Comment by dac2020** [comment]
OWA 1.5.7/1.5.8, I have a similar issue where when I go to Settings/OWA, the settings always seem to have been reset. However, once you click on Administration, your settings will show up.

**Comment by mbolis** [comment]
I noticed the same behavior on OWA 1.6.2

**Comment by padams** [comment]
This is not a generalized issue. Closing unless you can provide more details like what browser you are using, and version of php, etc.
