### ISSUE TITLE
Unable to install OWA 1.5.7 with SQL Server 2008

### ISSUE THREAD

**Issue by TomBrady** [padams/Open-Web-Analytics#84]
Trying to upgrade our install to OWA 1.5.7 on a Windows IIS hitting against SQL Server 2008.

Using PHP 5.3 also (same set up as older OWA installation).

I have a brand new empty database for testing & am getting Entity Installation failed errors which appears to be a SQL issue, but the not sure how this can be if it is the same environment as the original installation?

I’ve enclosed the DB plug-in being used for SQL Server that was originally used for the previous installation.

Somewhat a newbie at PHP which is not helping!   ;-}

---

06:48:41 05/28/15 19388 [debug] Query: CREATE TABLE IF NOT EXISTS owa_commerce_transaction_fact (id BIGINT PRIMARY KEY, visitor_id BIGINT, session_id BIGINT, INDEX (session_id), site_id VARCHAR(255), INDEX (site_id), referer_id BIGINT, ua_id BIGINT, host_id BIGINT, os_id BIGINT, location_id BIGINT, referring_search_term_id BIGINT, timestamp INT, yyyymmdd INT, INDEX (yyyymmdd), year INT, month INT, day TINYINT(2), dayofweek VARCHAR(10), dayofyear INT, weekofyear INT, last_req BIGINT, ip_address VARCHAR(255), is_new_visitor TINYINT(1), is_repeat_visitor TINYINT(1), language VARCHAR(255), days_since_prior_session INT, days_since_first_session INT, num_prior_sessions INT, medium VARCHAR(255), source_id BIGINT, ad_id BIGINT, campaign_id BIGINT, user_name VARCHAR(255), cv1_name VARCHAR(255), cv1_value VARCHAR(255), cv2_name VARCHAR(255), cv2_value VARCHAR(255), cv3_name VARCHAR(255), cv3_value VARCHAR(255), cv4_name VARCHAR(255), cv4_value VARCHAR(255), cv5_name VARCHAR(255), cv5_value VARCHAR(255), document_id BIGINT, order_id VARCHAR(255), INDEX (order_id), order_source VARCHAR(255), gateway VARCHAR(255), total_revenue BIGINT, tax_revenue BIGINT, shipping_revenue BIGINT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [debug] A SQL Server error occured. Error: (156) [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near the keyword 'IF'.. Query: CREATE TABLE IF NOT EXISTS owa_commerce_transaction_fact (id BIGINT PRIMARY KEY, visitor_id BIGINT, session_id BIGINT, INDEX (session_id), site_id VARCHAR(255), INDEX (site_id), referer_id BIGINT, ua_id BIGINT, host_id BIGINT, os_id BIGINT, location_id BIGINT, referring_search_term_id BIGINT, timestamp INT, yyyymmdd INT, INDEX (yyyymmdd), year INT, month INT, day TINYINT(2), dayofweek VARCHAR(10), dayofyear INT, weekofyear INT, last_req BIGINT, ip_address VARCHAR(255), is_new_visitor TINYINT(1), is_repeat_visitor TINYINT(1), language VARCHAR(255), days_since_prior_session INT, days_since_first_session INT, num_prior_sessions INT, medium VARCHAR(255), source_id BIGINT, ad_id BIGINT, campaign_id BIGINT, user_name VARCHAR(255), cv1_name VARCHAR(255), cv1_value VARCHAR(255), cv2_name VARCHAR(255), cv2_value VARCHAR(255), cv3_name VARCHAR(255), cv3_value VARCHAR(255), cv4_name VARCHAR(255), cv4_value VARCHAR(255), cv5_name VARCHAR(255), cv5_value VARCHAR(255), document_id BIGINT, order_id VARCHAR(255), INDEX (order_id), order_source VARCHAR(255), gateway VARCHAR(255), total_revenue BIGINT, tax_revenue BIGINT, shipping_revenue BIGINT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [debug] A SQL Server error occured. Error: (102) [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near 'owa_commerce_transaction_fact'.. Query: CREATE TABLE IF NOT EXISTS owa_commerce_transaction_fact (id BIGINT PRIMARY KEY, visitor_id BIGINT, session_id BIGINT, INDEX (session_id), site_id VARCHAR(255), INDEX (site_id), referer_id BIGINT, ua_id BIGINT, host_id BIGINT, os_id BIGINT, location_id BIGINT, referring_search_term_id BIGINT, timestamp INT, yyyymmdd INT, INDEX (yyyymmdd), year INT, month INT, day TINYINT(2), dayofweek VARCHAR(10), dayofyear INT, weekofyear INT, last_req BIGINT, ip_address VARCHAR(255), is_new_visitor TINYINT(1), is_repeat_visitor TINYINT(1), language VARCHAR(255), days_since_prior_session INT, days_since_first_session INT, num_prior_sessions INT, medium VARCHAR(255), source_id BIGINT, ad_id BIGINT, campaign_id BIGINT, user_name VARCHAR(255), cv1_name VARCHAR(255), cv1_value VARCHAR(255), cv2_name VARCHAR(255), cv2_value VARCHAR(255), cv3_name VARCHAR(255), cv3_value VARCHAR(255), cv4_name VARCHAR(255), cv4_value VARCHAR(255), cv5_name VARCHAR(255), cv5_value VARCHAR(255), document_id BIGINT, order_id VARCHAR(255), INDEX (order_id), order_source VARCHAR(255), gateway VARCHAR(255), total_revenue BIGINT, tax_revenue BIGINT, shipping_revenue BIGINT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [notice] owa_commerce_transaction_fact Table Creation Failed.
06:48:41 05/28/15 19388 [notice] Entity Installation Failed.
06:48:41 05/28/15 19388 [debug] Query: CREATE TABLE IF NOT EXISTS owa_commerce_line_item_fact (id BIGINT PRIMARY KEY, visitor_id BIGINT, session_id BIGINT, INDEX (session_id), site_id VARCHAR(255), INDEX (site_id), referer_id BIGINT, ua_id BIGINT, host_id BIGINT, os_id BIGINT, location_id BIGINT, referring_search_term_id BIGINT, timestamp INT, yyyymmdd INT, INDEX (yyyymmdd), year INT, month INT, day TINYINT(2), dayofweek VARCHAR(10), dayofyear INT, weekofyear INT, last_req BIGINT, ip_address VARCHAR(255), is_new_visitor TINYINT(1), is_repeat_visitor TINYINT(1), language VARCHAR(255), days_since_prior_session INT, days_since_first_session INT, num_prior_sessions INT, medium VARCHAR(255), source_id BIGINT, ad_id BIGINT, campaign_id BIGINT, user_name VARCHAR(255), cv1_name VARCHAR(255), cv1_value VARCHAR(255), cv2_name VARCHAR(255), cv2_value VARCHAR(255), cv3_name VARCHAR(255), cv3_value VARCHAR(255), cv4_name VARCHAR(255), cv4_value VARCHAR(255), cv5_name VARCHAR(255), cv5_value VARCHAR(255), document_id BIGINT, order_id VARCHAR(255), INDEX (order_id), sku VARCHAR(255), product_name VARCHAR(255), category VARCHAR(255), unit_price BIGINT, quantity INT, item_revenue BIGINT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [debug] A SQL Server error occured. Error: (156) [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near the keyword 'IF'.. Query: CREATE TABLE IF NOT EXISTS owa_commerce_line_item_fact (id BIGINT PRIMARY KEY, visitor_id BIGINT, session_id BIGINT, INDEX (session_id), site_id VARCHAR(255), INDEX (site_id), referer_id BIGINT, ua_id BIGINT, host_id BIGINT, os_id BIGINT, location_id BIGINT, referring_search_term_id BIGINT, timestamp INT, yyyymmdd INT, INDEX (yyyymmdd), year INT, month INT, day TINYINT(2), dayofweek VARCHAR(10), dayofyear INT, weekofyear INT, last_req BIGINT, ip_address VARCHAR(255), is_new_visitor TINYINT(1), is_repeat_visitor TINYINT(1), language VARCHAR(255), days_since_prior_session INT, days_since_first_session INT, num_prior_sessions INT, medium VARCHAR(255), source_id BIGINT, ad_id BIGINT, campaign_id BIGINT, user_name VARCHAR(255), cv1_name VARCHAR(255), cv1_value VARCHAR(255), cv2_name VARCHAR(255), cv2_value VARCHAR(255), cv3_name VARCHAR(255), cv3_value VARCHAR(255), cv4_name VARCHAR(255), cv4_value VARCHAR(255), cv5_name VARCHAR(255), cv5_value VARCHAR(255), document_id BIGINT, order_id VARCHAR(255), INDEX (order_id), sku VARCHAR(255), product_name VARCHAR(255), category VARCHAR(255), unit_price BIGINT, quantity INT, item_revenue BIGINT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [debug] A SQL Server error occured. Error: (102) [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near 'owa_commerce_line_item_fact'.. Query: CREATE TABLE IF NOT EXISTS owa_commerce_line_item_fact (id BIGINT PRIMARY KEY, visitor_id BIGINT, session_id BIGINT, INDEX (session_id), site_id VARCHAR(255), INDEX (site_id), referer_id BIGINT, ua_id BIGINT, host_id BIGINT, os_id BIGINT, location_id BIGINT, referring_search_term_id BIGINT, timestamp INT, yyyymmdd INT, INDEX (yyyymmdd), year INT, month INT, day TINYINT(2), dayofweek VARCHAR(10), dayofyear INT, weekofyear INT, last_req BIGINT, ip_address VARCHAR(255), is_new_visitor TINYINT(1), is_repeat_visitor TINYINT(1), language VARCHAR(255), days_since_prior_session INT, days_since_first_session INT, num_prior_sessions INT, medium VARCHAR(255), source_id BIGINT, ad_id BIGINT, campaign_id BIGINT, user_name VARCHAR(255), cv1_name VARCHAR(255), cv1_value VARCHAR(255), cv2_name VARCHAR(255), cv2_value VARCHAR(255), cv3_name VARCHAR(255), cv3_value VARCHAR(255), cv4_name VARCHAR(255), cv4_value VARCHAR(255), cv5_name VARCHAR(255), cv5_value VARCHAR(255), document_id BIGINT, order_id VARCHAR(255), INDEX (order_id), sku VARCHAR(255), product_name VARCHAR(255), category VARCHAR(255), unit_price BIGINT, quantity INT, item_revenue BIGINT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [notice] owa_commerce_line_item_fact Table Creation Failed.
06:48:41 05/28/15 19388 [notice] Entity Installation Failed.
06:48:41 05/28/15 19388 [debug] Query: CREATE TABLE IF NOT EXISTS owa_queue_item (id BIGINT PRIMARY KEY, event_type VARCHAR(255), priority INT, status VARCHAR(255), event BLOB, insertion_datestamp TIMESTAMP, insertion_timestamp INT, handled_timestamp INT, last_attempt_timestamp INT, not_before_timestamp INT, failed_attempt_count INT, is_assigned TINYINT(1), last_error_msg VARCHAR(255), handled_by VARCHAR(255), handler_duration INT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [debug] A SQL Server error occured. Error: (156) [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near the keyword 'IF'.. Query: CREATE TABLE IF NOT EXISTS owa_queue_item (id BIGINT PRIMARY KEY, event_type VARCHAR(255), priority INT, status VARCHAR(255), event BLOB, insertion_datestamp TIMESTAMP, insertion_timestamp INT, handled_timestamp INT, last_attempt_timestamp INT, not_before_timestamp INT, failed_attempt_count INT, is_assigned TINYINT(1), last_error_msg VARCHAR(255), handled_by VARCHAR(255), handler_duration INT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [debug] A SQL Server error occured. Error: (102) [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near 'owa_queue_item'.. Query: CREATE TABLE IF NOT EXISTS owa_queue_item (id BIGINT PRIMARY KEY, event_type VARCHAR(255), priority INT, status VARCHAR(255), event BLOB, insertion_datestamp TIMESTAMP, insertion_timestamp INT, handled_timestamp INT, last_attempt_timestamp INT, not_before_timestamp INT, failed_attempt_count INT, is_assigned TINYINT(1), last_error_msg VARCHAR(255), handled_by VARCHAR(255), handler_duration INT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [notice] owa_queue_item Table Creation Failed.
06:48:41 05/28/15 19388 [notice] Entity Installation Failed.
06:48:41 05/28/15 19388 [debug] Query: CREATE TABLE IF NOT EXISTS owa_site_user (site_id BIGINT, user_id INT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [debug] A SQL Server error occured. Error: (156) [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near the keyword 'IF'.. Query: CREATE TABLE IF NOT EXISTS owa_site_user (site_id BIGINT, user_id INT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [debug] A SQL Server error occured. Error: (102) [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near 'owa_site_user'.. Query: CREATE TABLE IF NOT EXISTS owa_site_user (site_id BIGINT, user_id INT) ENGINE = INNODB CHARACTER SET = utf8
06:48:41 05/28/15 19388 [notice] owa_site_user Table Creation Failed.
06:48:41 05/28/15 19388 [notice] Entity Installation Failed.
06:48:41 05/28/15 19388 [notice] Installation failed.
06:48:41 05/28/15 19388 [debug] Assembling view: owa_installView
06:48:41 05/28/15 19388 [debug] Total session time: 0.40062117576599
06:48:41 05/28/15 19388 [debug] goodbye from OWA

**Comment by TomBrady** [comment]
owa_db_sqlsrv.php (from Git repository)

<?php

//
// Open Web Analytics - An Open Source Web Analytics Framework
//
// Copyright 2006 Peter Adams. All rights reserved.
//
// Licensed under GPL v2.0 http://www.gnu.org/copyleft/gpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// $Id$
//


define('OWA_DTD_BIGINT', 'BIGINT'); 
define('OWA_DTD_INT', 'INT');
define('OWA_DTD_TINYINT', 'TINYINT(1)');
define('OWA_DTD_TINYINT2', 'TINYINT(2)');
define('OWA_DTD_TINYINT4', 'TINYINT(4)');
define('OWA_DTD_SERIAL', 'IDENTITY');
define('OWA_DTD_PRIMARY_KEY', 'PRIMARY KEY');
define('OWA_DTD_VARCHAR10', 'VARCHAR(10)');
define('OWA_DTD_VARCHAR255', 'VARCHAR(255)');
define('OWA_DTD_VARCHAR', 'VARCHAR(%s)');
define('OWA_DTD_TEXT', 'TEXT');
define('OWA_DTD_BOOLEAN', 'TINYINT(1)');
define('OWA_DTD_TIMESTAMP', 'TIMESTAMP');
define('OWA_DTD_BLOB', 'BLOB');
define('OWA_DTD_INDEX', 'KEY');
define('OWA_DTD_AUTO_INCREMENT', 'AUTO_INCREMENT');
define('OWA_DTD_NOT_NULL', 'NOT NULL');
define('OWA_DTD_UNIQUE', 'PRIMARY KEY(%s)');
define('OWA_SQL_ADD_COLUMN', 'ALTER TABLE %s ADD %s %s');   
define('OWA_SQL_DROP_COLUMN', 'ALTER TABLE %s DROP %s');
define('OWA_SQL_RENAME_COLUMN', 'ALTER TABLE %s CHANGE %s %s %s'); 
define('OWA_SQL_MODIFY_COLUMN', 'ALTER TABLE %s MODIFY %s %s'); 
define('OWA_SQL_RENAME_TABLE', 'ALTER TABLE %s RENAME %s'); 
define('OWA_SQL_CREATE_TABLE', 'CREATE TABLE IF NOT EXISTS %s (%s) %s'); 
define('OWA_SQL_DROP_TABLE', 'DROP TABLE IF EXISTS %s');  
define('OWA_SQL_INSERT_ROW', 'INSERT into %s (%s) VALUES (%s)');
define('OWA_SQL_UPDATE_ROW', 'UPDATE %s SET %s %s');
define('OWA_SQL_DELETE_ROW', "DELETE from %s %s");
define('OWA_SQL_CREATE_INDEX', 'CREATE INDEX %s ON %s (%s)');
define('OWA_SQL_DROP_INDEX', 'DROP INDEX %s ON %s');
define('OWA_SQL_INDEX', 'INDEX (%s)');
define('OWA_SQL_BEGIN_TRANSACTION', 'BEGIN TRANS');
define('OWA_SQL_END_TRANSACTION', 'COMMIT TRANS');
define('OWA_DTD_TABLE_TYPE', 'ENGINE = %s');
define('OWA_DTD_TABLE_TYPE_DEFAULT', 'INNODB');
define('OWA_DTD_TABLE_TYPE_DISK', 'INNODB');
define('OWA_DTD_TABLE_TYPE_MEMORY', 'MEMORY');
define('OWA_SQL_ALTER_TABLE_TYPE', 'ALTER TABLE %s ENGINE = %s');
define('OWA_SQL_JOIN_LEFT_OUTER', 'LEFT OUTER JOIN');
define('OWA_SQL_JOIN_LEFT_INNER', 'LEFT INNER JOIN');
define('OWA_SQL_JOIN_RIGHT_OUTER', 'RIGHT OUTER JOIN');
define('OWA_SQL_JOIN_RIGHT_INNER', 'RIGHT INNER JOIN');
define('OWA_SQL_JOIN', 'JOIN');
define('OWA_SQL_DESCENDING', 'DESC');
define('OWA_SQL_ASCENDING', 'ASC');
define('OWA_SQL_REGEXP', 'REGEXP');
define('OWA_SQL_NOTREGEXP', 'NOT REGEXP');
define('OWA_SQL_LIKE', 'LIKE');
define('OWA_SQL_ADD_INDEX', 'ALTER TABLE %s ADD INDEX (%s) %s');
define('OWA_SQL_COUNT', 'COUNT(%s)');
define('OWA_SQL_SUM', 'SUM(%s)');
define('OWA_SQL_ROUND', 'ROUND(%s,0)');
define('OWA_SQL_AVERAGE', 'AVG(%s)');
define('OWA_SQL_DISTINCT', 'DISTINCT %s');
define('OWA_SQL_DIVISION', '(%s / %s)');
define('OWA_DTD_CHARACTER_ENCODING_UTF8', 'utf8');
define('OWA_DTD_TABLE_CHARACTER_ENCODING', 'CHARACTER SET = %s');


/**
 * MySQL Data Access Class
 * 
 * @author      Peter Adams <peter@openwebanalytics.com>
 * @copyright   Copyright &copy; 2006 Peter Adams <peter@openwebanalytics.com>
 * @license     http://www.gnu.org/copyleft/gpl.html GPL v2.0
 * @category    owa
 * @package     owa
 * @version		$Revision$	      
 * @since		owa 1.0.0
 */
class owa_db_sqlsrv extends owa_db {

	
	function connect() {
	
		if (!$this->connection) {
			
			if ($this->getConnectionParam('persistant')) {
				
				$this->connection = sqlsrv_connect(
					$this->getConnectionParam('host'),
					array("Database"=>$this->getConnectionParam('name'), 
					"UID"=>$this->getConnectionParam('user'),
					"PWD"=>$this->getConnectionParam('password'))
	    		);
	    		
			} else {
				
				$this->connection = sqlsrv_connect(
					$this->getConnectionParam('host'),
					array("Database"=>$this->getConnectionParam('name'), 
					"UID"=>$this->getConnectionParam('user'),
					"PWD"=>$this->getConnectionParam('password'))
	    		);
			}
			
			//$this->database_selection = mysql_select_db($this->getConnectionParam('name'), $this->connection);
			//
			//if (function_exists('mysql_set_charset')) {
			//	mysql_set_charset('utf8',$this->connection);
			//} else {
			//	$this->query("SET NAMES 'utf8'");
			//}
			
		}
			
			
		if (!$this->connection) {
			$this->e->alert('Could not connect to database.');
			if( ($errors = sqlsrv_errors() ) != null) {
				foreach($errors as $error) {
					$this->e->debug(sprintf('A SQL Server error occured. Error: (%s) %s.',
					$error[ 'code'],
					$error[ 'message']));
				}
			}
			$this->connection_status = false;
			return false;
		} else {
			$this->connection_status = true;
			return true;
		}
	}
	
	
	/**
	 * Database Query
	 *
	 * @param 	string $sql
	 * @access 	public
	 * 
	 */
	function query($sql) {
  
  		if ($this->connection_status == false):
  		owa_coreAPI::profile($this, __FUNCTION__, __LINE__);
  			$this->connect();
  		owa_coreAPI::profile($this, __FUNCTION__, __LINE__);
  		endif;
  
  		owa_coreAPI::profile($this, __FUNCTION__, __LINE__);
		$this->e->debug(sprintf('Query: %s', $sql));
		
		$this->result = '';
		$this->new_result = '';	
		
		if (!empty($this->new_result)):
			sqlsrv_free_stmt($this->new_result);
		endif;
		owa_coreAPI::profile($this, __FUNCTION__, __LINE__, $sql);
		$result = @sqlsrv_query($this->connection, $sql);
		
		owa_coreAPI::profile($this, __FUNCTION__, __LINE__);			
		// Log Errors
		 if( ($errors = sqlsrv_errors() ) != null) {
			foreach($errors as $error) {
				$this->e->debug(sprintf('A SQL Server error occured. Error: (%s) %s. Query: %s',
				$error[ 'code'],
				$error[ 'message'],
				$sql));
			}
		}		
		owa_coreAPI::profile($this, __FUNCTION__, __LINE__);
		$this->new_result = $result;
		
		return $this->new_result;
		
	}
	
	function close() {
		
		@sqlsrv_close($this->connection);
		return;
		
	}
	
	/**
	 * Fetch result set array
	 *
	 * @param 	string $sql
	 * @return 	array
	 * @access  public
	 */
	function get_results($sql) {
	
		if ($sql):
			$this->query($sql);
		endif;
	
		$num_rows = 0;
		
		while ( $row = @sqlsrv_fetch_array($this->new_result,SQLSRV_FETCH_ASSOC) ) {
			$this->result[$num_rows] = $row;
			$num_rows++;
		}
		
		if ($this->result):
					
			return $this->result;
			
		else:
			return null;
		endif;
	}
	
	/**
	 * Fetch Single Row
	 *
	 * @param string $sql
	 * @return array
	 */
	function get_row($sql) {
		
		$this->query($sql);
		
		//print_r($this->result);
		$row = @sqlsrv_fetch_array($this->new_result,SQLSRV_FETCH_ASSOC);
		
		return $row;
	}
	
	/**
	 * Prepares and escapes string
	 *
	 * @param string $string
	 * @return string
	 */
	function prepare($string) {
		
		if ($this->connection_status == false):
  			$this->connect();
  		endif;
		
		$pattern = "/'/"; 
		$replacement = "''"; 
		
		return preg_replace($pattern, $replacement, $string);
		
		
	}
	
	function getAffectedRows() {
		
		return sqlsrv_rows_affected($this->new_result);
	}
}

?>

**Comment by padams** [comment]
SQL Server is not a supported database.
OWA only supports MySQL.
