### ISSUE TITLE
Cannot get PHP data access API to work.

### ISSUE THREAD

**Issue by theantichris** [padams/Open-Web-Analytics#85]
I'm following the example here: https://github.com/padams/Open-Web-Analytics/wiki/Data-Access-API

The documentation does not mention what file(s) to include to properly bootstrap the API for use with PHP and not REST.

**Comment by theantichris** [comment]
I think I found that I need to include owa_php.php but with that and the example in the wiki I'm getting "No API Method Found."

**Comment by theantichris** [comment]
It looks like an instance of owa_php needs to created prior to trying to access the data API. Does this need to be included in the wiki?

**Comment by padams** [comment]
Yes. You need an instance of OWA instantiated. Then after you have that you can execute the REST APIS using the executeApiCommand coreAPI method like so:

$rs = owa_coreAPI::executeApiCommand( array(
			
			'do'				=> ‘getResultSet',
			'siteId'			=> ’somesiteid',
			'page'			=> '',
			'startDate'		=> '',
			'endDate'			=> '',
			'period'			=> '',
			'resultsPerPage'	=> 10 ) 
);

The params in the array are the ones in the doco for the REST call.
