### ISSUE TITLE
Cloudflare and CDN IP

### ISSUE THREAD

**Issue by IQuant** [padams/Open-Web-Analytics#87]
Where or what would I modify to pick up the actual user IP when the sites are being served by CDN? 

Example of code used in other PHP applications:

// Cloudflare CDN **\* Add This Code ***
if ($_SERVER["HTTP_CF_CONNECTING_IP"]) {
$_SERVER["REMOTE_ADDR"] = $_SERVER["HTTP_CF_CONNECTING_IP"];
}

**Comment by padams** [comment]
Would would have to create a custom module that registered a filter function for the ip_address property.

See the maxmind module for an example on how to setup a module and register a filter function.
