### ISSUE TITLE
Is there a delay in OWA's writing of the web analytics data to the database?

### ISSUE THREAD

**Issue by TomBrady** [padams/Open-Web-Analytics#88]
Hey All,

When I direct query the database for stats from todays date back 7 days, there is no result set returned.
Does OWA have a queue or delay in the writing of the web analytics data to the database?

Thanks,
Bill

**Comment by padams** [comment]
only if you explicitly set it to queue events in your config file. Otherwise it writes to the DB synchronously.

**Comment by TomBrady** [comment]
Thanks so much…

Keep up the great work!
