### ISSUE TITLE
Unique visitors issue in Chrome

### ISSUE THREAD

**Issue by sushrut87** [padams/Open-Web-Analytics#89]
I have installed Open Web Analytics 1.5.7. When I track the site using IE, Mozilla Firefox, Safari browser I get the number of unique visitor correctly. It tracks different visit of the user at different times.

But when I browse the site using chrome, any time I request new page, it is being tracked as a new visit. So number of unique visitors is very high.

Also, I see new visitor as 100% in the chart, where as there are repeated users which can be tracked using IE/Firefox browsers.

What can be the issue here? Any configuration is required?

**Comment by JessDsouza** [comment]
Ensure that you have entered the code properly. Actually I'm working with Google analytics & having  same issue I reinstall it but still there is some problem occurring in it. Now its dashboard showing me zero page view.

**Comment by padams** [comment]
It's possible that the user have the do not track setting turned on or a cookie setting that does not allow for persistent cookies to be set.

**Comment by coiltap** [comment]
I also have this issue, no matter what browser the user is on.  All page views are counted as unique users.
