### ISSUE TITLE
Installation problem - owa_db_yourdbtypegoeshere

### ISSUE THREAD

**Issue by csselo** [padams/Open-Web-Analytics#91]
hi

After owa-config renamed and instalation page was filled.
it went empty page.

and error

[Wed Jun 24 16:23:07.015596 2015] [:error] [pid 1770] [client 127.0.0.1:35995] PHP Warning:  require_once(/var/www/html/owa/plugins/db/owa_db_yourdbtypegoeshere.php): failed to open stream: No such file or directory in /var/www/html/owa/owa_coreAPI.php on line 66
[Wed Jun 24 16:23:07.015635 2015] [:error] [pid 1770] [client 127.0.0.1:35995] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owa/plugins/db/owa_db_yourdbtypegoeshere.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/owa/owa_coreAPI.php on line 66
[Wed Jun 24 16:23:11.856705 2015] [:error] [pid 3884] [client 127.0.0.1:35996] PHP Warning:  require_once(/var/www/html/owa/plugins/db/owa_db_yourdbtypegoeshere.php): failed to open stream: No such file or directory in /var/www/html/owa/owa_coreAPI.php on line 66

also mysql is selected.

**Comment by padams** [comment]
Replace the "yourdbtypegoeshere" with "mysql" in your config file.

**Comment by csselo** [comment]
Database Schema Installation failed. Please check the error log file for more details.

I looked at the appache log. nothing found

**Comment by csselo** [comment]
Ok. it finished.

I am in login screen .
username ? pswd ?

**Comment by csselo** [comment]
there is an innodb problem.

finised.

**Comment by alx1969** [comment]
I am getting the same error, I click on 'Let's get started' on the first screen, I fill in site domain, email address and password on next screen then when I click on continue I get ;database schema installation failed. Please check error log for more details. I am using Centos 7 and mariadb 10.1.

**Comment by padams** [comment]
You would need to provide login from the owa and PHP error logs for anyone to help debug this. That said I think this issue is now fixed in master.
