### ISSUE TITLE
login in my host

### ISSUE THREAD

**Issue by csselo** [padams/Open-Web-Analytics#92]
hi

I installed perfectly in my localhost but in my server I couldnt.
http://178.62.209.239/owa/ (login screen u: admin p:selo1980)

I changed owa config

define('OWA_DB_TYPE', 'mysql'); // options: mysql
define('OWA_DB_NAME', 'owa'); // name of the database
define('OWA_DB_HOST', 'localhost'); // host name of the server housing the database
define('OWA_DB_USER', 'root'); // database user
define('OWA_DB_PASSWORD', 'XXXXXX'); // database user's password

define('OWA_PUBLIC_URL', 'http://XXXXXX/owa/');  

db is created.

but I couldnt pass the login screen.
it refeshes and it asks again.
http://178.62.209.239/owa/ (login screen u: admin p:selo1980)

**Comment by csselo** [comment]
solved.

there is a chrome bug.

ff is ok.

**Comment by padams** [comment]
You must run OWA on a server with a fully qualified domain name. Not an IP address.

Also, you should never put passwords in a issue post like you did here as these pages are public!

**Comment by padams** [comment]
Closing chrome is issue is in #210
