### ISSUE TITLE
"Delay First Hit" doesn't work.

### ISSUE THREAD

**Issue by gezegond** [padams/Open-Web-Analytics#95]
When I set "Delay First Hit" option to "On" in settings menu and click "Update Configuration", it says "Options Saved" but "Delay First Hit" goes back to "Off". I can change other settings but "Delay First Hit" doesn't change.

**Comment by padams** [comment]
yeah that needs to be  removed as that feature has been deprecated.

**Comment by padams** [comment]
removed rom master.
