### ISSUE TITLE
Is there any way to see the number of visits from a certain domain?

### ISSUE THREAD

**Issue by carpat** [padams/Open-Web-Analytics#96]
Hey!

Our management wants to know how many visits we get from a certain domain. At first I thought this would show up in "Traffic -> Referring Web Sites", but either that page is used for a different purpose or isn't implemented yet. There doesn't seem to be any documentation about that feature.

So, is there any way to see the number of visits from a certain domain?

**Comment by padams** [comment]
You don't get traffic from domains. You can get traffic from hosts (which are really ISP network gateways). Just add hosts as a secondary dimension in reporting.
