### ISSUE TITLE
OWA module install and configure problem

### ISSUE THREAD

**Issue by przemekchelsea** [padams/Open-Web-Analytics#98]
I have a drupal site and i installed the owa module on it.
I cant find a good manual how to install and configure it properly.

Readme.txt from from the owa module on drupal says
# Installation

1)\* Copy the 'owa' module directory in to your Drupal
sites/all/modules directory as usual.
# Usage
## 2)In the settings page enter your Open Web Analytics SiteID and the Open Web Analytics installation url.

after installing owa module on drupal the 1) step is ok
I dont know where to find the SiteID and which url to write on the settings page.
Do i have to download and copy also all the owa folder to the owa folder on drupal?
What i have to do exactly??

**Comment by padams** [comment]
That drupal module is not part of the OWA project. sorry.
